(function(g){var window=this;'use strict';var LM=function(e){e.publish("cardstatechange",e.U3()&&e.Eo()?1:0)},$6=function(e,k){var v=g.LE(k),F=v?k:arguments;
for(v=v?0:1;v<F.length;v++){if(e==null)return;e=e[F[v]]}return e},DSg=function(e){var k=g.Vr(e);
e=g.gN(e);return new g.aB(k.x,k.y,e.width,e.height)},ydL=function(e,k,v){var F;
return F=g.qs(e,k,function(){g.Y5(F);v.apply(e,arguments)},{})},Y6=function(e){e=g.qM(e);
delete OA[e];g.mL(OA)&&qC&&qC.stop()},POy=function(){qC||(qC=new g.Y1(function(){M7y()},20));
var e=qC;e.isActive()||e.start()},M7y=function(){var e=g.ih();
g.YV(OA,function(k){aZn(k,e)});
g.mL(OA)||POy()},ZP=function(e,k,v,F){g.IM.call(this);
if(!Array.isArray(e)||!Array.isArray(k))throw Error("Start and end parameters must be arrays");if(e.length!=k.length)throw Error("Start and end points must be the same length");this.V=e;this.X=k;this.duration=v;this.U=F;this.coords=[];this.progress=this.K=0;this.A=null},aZn=function(e,k){k<e.startTime&&(e.endTime=k+e.endTime-e.startTime,e.startTime=k);
e.progress=(k-e.startTime)/(e.endTime-e.startTime);e.progress>1&&(e.progress=1);e.K=1E3/(k-e.A);e.A=k;hQn(e,e.progress);e.progress==1?(e.W=0,Y6(e),e.onFinish(),e.iy()):e.isPlaying()&&e.B9()},hQn=function(e,k){typeof e.U==="function"&&(k=e.U(k));
e.coords=Array(e.V.length);for(let v=0;v<e.V.length;v++)e.coords[v]=(e.X[v]-e.V[v])*k+e.V[v]},USp=function(e,k){g.lo.call(this,e);
this.coords=k.coords;this.x=k.coords[0];this.y=k.coords[1];this.z=k.coords[2];this.duration=k.duration;this.progress=k.progress;this.fps=k.K;this.state=k.W},w3=function(e,k,v,F,K){ZP.call(this,k,v,F,K);
this.element=e},iI=function(e,k,v,F,K){if(k.length!=2||v.length!=2)throw Error("Start and end points must be 2D");
w3.call(this,e,k,v,F,K)},AdJ=function(e){return Math.pow(e,3)},COK=function(e){return 3*e*e-2*e*e*e},NC=function(e){return e.baseUrl||null},x6=function(e,k){return g.fE(g.DH(e,k),v=>!!v)},oq4=function(e,k,v){function F(Bc){var MM=Bc.hovercardButton;
if(!MM)return null;MM=MM.subscribeButtonRenderer;if(!MM)return null;var og=G(MM.unsubscribedButtonText),xY=G(MM.subscribedButtonText);if(MM.subscribed){var NM=G(MM.subscriberCountWithUnsubscribeText);var Qn=G(MM.subscriberCountText)}else NM=G(MM.subscriberCountText),Qn=G(MM.subscriberCountWithSubscribeText);var yn=null;return Bc.signinEndpoint&&((yn=$6(Bc,"signinEndpoint","webNavigationEndpointData","url"))||(yn=g.y(MM.signInEndpoint?.commandMetadata,g.OE)?.url),!yn)?null:og&&(xY||yn)?{subscribed:MM.subscribed,
subscribeText:og,subscribeCount:NM,unsubscribeText:xY,unsubscribeCount:Qn,enabled:MM.enabled,signinUrl:yn,classic:Bc.useClassicSubscribeButton}:null}
function K(Bc){if(Bc){var MM=[],og=Bc.videoId;og&&MM.push("v="+og);(og=Bc.playlistId)&&MM.push("list="+og);(Bc=Bc.startTimeSeconds)&&MM.push("t="+Bc);return"/watch?"+MM.join("&")}}
function G(Bc){if(!Bc)return null;var MM=Bc.simpleText;return MM?MM:Bc.runs?g.DH(Bc.runs,og=>og.text).join(""):null}
k=k.endscreenElementRenderer;if(!k)return null;var t=k.style,V=k.endpoint||{},T=null,H=null,z=!1,X=null,S=null,R=null,J=null,Z=!1,B=null,l=null,f=null,D=null,P=null,kQ=null;if(t==="VIDEO")g.y(V,g.vZ)?T=g.y(V,g.vZ).url:(kQ=g.y(V,g.pw),T=K(kQ)),H=!1,X=e,k.thumbnailOverlays?(z=k.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,S=G(z.text),z=z.style==="LIVE"):S=G(k.videoDuration);else if(t==="PLAYLIST")g.y(V,g.vZ)?T=g.y(V,g.vZ).url:(kQ=g.y(V,g.pw),T=K(kQ)),H=!1,X=e,R=G(k.playlistLength);else if(t===
"CHANNEL"){if(Z=$6(V,"browseEndpoint","browseId"))J=Z,T=`/channel/${J}`;H=!1;X="new";(Z=!!k.isSubscribe)?B=F(k):l=G(k.subscribersText)}else t==="WEBSITE"?((f=$6(V,"urlEndpoint","url"))&&(T=f),H=!0,X="new",f=k.icon.thumbnails[0].url):t==="CREATOR_MERCHANDISE"&&(k.productPrice&&(D=G(k.productPrice)),k.additionalFeesText&&(P=G(k.additionalFeesText)),(H=$6(V,"urlEndpoint","url"))&&(T=H),H=!0,X="new");e=$6(k,"title","accessibility","accessibilityData","label");var nE=k.endpoint?k.endpoint.clickTrackingParams:
null,wZ="";if(k.metadata){let Bc=G(k.metadata);Bc&&(wZ=Bc)}return{id:`element-${v}`,type:t,title:G(k.title),metadata:wZ,callToAction:G(k.callToAction),XK:k.image,iconUrl:f,left:Number(k.left),width:Number(k.width),top:Number(k.top),aspectRatio:Number(k.aspectRatio),startMs:Math.floor(Number(k.startMs)),endMs:Math.floor(Number(k.endMs)),videoDuration:S,ZR:z,playlistLength:R,channelId:J,subscribeButton:B,subscribersText:l,isSubscribe:Z,targetUrl:T||null,pk:H,sessionData:nE?{itct:nE}:null,Og:X,cv:e?
e:null,isPlaceholder:k.isPlaceholder,impressionUrls:x6(k.impressionUrls||[],NC),mM:x6(k.hovercardShowUrls||[],NC),clickUrls:x6(V.loggingUrls||[],NC),visualElement:g.mu(k.trackingParams),productPrice:D,additionalFeesText:P,watchEndpoint:kQ||null}},r3=function(e,k){var v={startMs:Math.floor(Number(e.startMs)),
impressionUrls:x6(e.impressionUrls||[],NC),elements:x6(e.elements||[],(F,K)=>oq4(k,F,K))};
e.trackingParams&&(v.visualElement=g.mu(e.trackingParams));return v},cL=function(e){return e.player.G().playerStyle==="creator-endscreen-editor"},bT7=function(e){return e.player.getVideoData().Vd?"current":e.C?"new":"current"},sA=function(e,k,v=!0){e.player.Ku("creatorendscreen");
e.Y&&(e.Y.dispose(),e.Y=null,e.U.dispose(),e.U=null);for(var F of Object.values(e.V))F.dispose();e.V={};e.K={};e.D.length>0&&(e.D.forEach(K=>{K.dispose()}),e.D.length=0);
e.W&&(g.sI(e.W,"ytp-ce-element-show"),e.W.setAttribute("aria-hidden","true"));e.X=0;if((e.endscreen=k)&&k.elements){v&&ej7(e);v=[];F=new g.tO(k.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});v.push(F);e.player.G().Y||(e.Y=new g.C({L:"div",Z:"ytp-ce-shadow"}),g.Au(e.player,e.Y.element,4),e.U=new g.y9(e.Y,200));for(F=0;F<k.elements.length;++F){let K=k.elements[F],G=koU(e,K);if(!G){g.kL(new g.PN("buildEndscreenElement null",K));continue}e.V[K.id]=G;e.K[K.id]=K;g.Au(e.player,
G.element,4);let t=new g.tO(K.startMs,K.endMs,{id:"ytp-ce-element-"+K.id,namespace:"creatorendscreen"});v.push(t);vPK(e,G,K)}e.player.j3(v);e.CV()}},FjK=function(e){var k=e.player.getVideoData(),v=k.videoId;
e.A&&e.A.abort();v={method:"POST",onFinish:K=>{var G=e.A=null;K.status===200&&(K=K.responseText,K.substring(0,3)===")]}"&&(K=K.substring(3),G=JSON.parse(K),G=r3(G,bT7(e))));sA(e,G)},
urlParams:{v},withCredentials:!0};e.C&&(v.urlParams.ptype="embedded");var F=k.fM;F&&(v.postParams={ad_tracking:F});if(k=g.YMh(k))if(k=g.My(k),k=g.ld(k))e.A=g.wa(k,v)},ej7=function(e){var k=g.yf(),v=g.MV();
v&&k&&e.endscreen.visualElement&&g.Ka(g.WA)(void 0,v,k,e.endscreen.visualElement)},koU=function(e,k){var v=null;
switch(k.type){case "VIDEO":e={L:"div",M3:["ytp-ce-element","ytp-ce-video"],B:{tabindex:"0","aria-label":k.cv||"","aria-hidden":"true"},S:[{L:"div",Z:"ytp-ce-element-shadow"},{L:"div",Z:"ytp-ce-covering-image",B:BL(k)},{L:"div",Z:"ytp-ce-covering-shadow-top"},{L:"a",Z:"ytp-ce-covering-overlay",B:{href:jt(e,k.targetUrl),tabindex:"-1"},S:[{L:"div",M3:["ytp-ce-video-title","ytp-webkit-ellipsis"],B:{dir:g.yw(k.title||"")},Ui:k.title},{L:"div",Z:k.ZR?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
Ui:k.videoDuration||void 0}]}]};v=new g.C(e);break;case "PLAYLIST":e={L:"div",M3:["ytp-ce-element","ytp-ce-playlist"],B:{tabindex:"0","aria-label":k.cv||"","aria-hidden":"true"},S:[{L:"div",Z:"ytp-ce-element-shadow"},{L:"div",Z:"ytp-ce-covering-image",B:BL(k)},{L:"div",Z:"ytp-ce-covering-shadow-top"},{L:"a",Z:"ytp-ce-covering-overlay",B:{href:jt(e,k.targetUrl),tabindex:"-1"},S:[{L:"div",M3:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],B:{dir:g.yw(k.title||"")},Ui:k.title},{L:"div",Z:"ytp-ce-playlist-count",
S:[{L:"div",Z:"ytp-ce-playlist-icon"},{L:"div",Z:"ytp-ce-playlist-count-text",Ui:k.playlistLength||void 0}]}]}]};v=new g.C(e);break;case "CHANNEL":v={L:"div",M3:["ytp-ce-element","ytp-ce-channel",k.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],B:{tabindex:"0","aria-label":k.cv||"","aria-hidden":"true"},S:[{L:"div",Z:"ytp-ce-element-shadow"},{L:"div",Z:"ytp-ce-expanding-overlay",S:[{L:"div",Z:"ytp-ce-expanding-overlay-hider"},{L:"div",Z:"ytp-ce-expanding-overlay-background"},{L:"div",Z:"ytp-ce-expanding-overlay-content",
S:[{L:"div",Z:"ytp-ce-expanding-overlay-body",S:[{L:"div",Z:"ytp-ce-expanding-overlay-body-padding",S:[{L:"a",M3:["ytp-ce-channel-title","ytp-ce-link"],B:{href:jt(e,k.targetUrl),target:"_blank",tabindex:"-1",dir:g.yw(k.title||"")},Ui:k.title},k.subscribeButton?{L:"div",Z:"ytp-ce-subscribe-container",S:[{L:"div",Z:"ytp-ce-channel-subscribe"}]}:"",k.subscribersText?{L:"div",Z:"ytp-ce-channel-subscribers-text",B:k.cv?{"aria-hidden":"true"}:{},Ui:k.subscribersText}:"",k.metadata?{L:"div",M3:["ytp-ce-channel-metadata",
"yt-ui-ellipsis","yt-ui-ellipsis-3"],Ui:k.metadata}:""]}]}]}]},{L:"div",Z:"ytp-ce-expanding-image",B:BL(k)}]};v=new g.C(v);let K=g.ez(document,"div","ytp-ce-channel-subscribe",v.element)[0];if(k.subscribeButton&&k.channelId){g.Qw(K,"ytp-ce-subscribe-button");let G;if(e.player.G().Y){var F=null;G=k.sessionData.itct}else F="endscreen",G=null;F=new g.Pd(k.subscribeButton.subscribeText,k.subscribeButton.subscribeCount,k.subscribeButton.unsubscribeText,k.subscribeButton.unsubscribeCount,!!k.subscribeButton.enabled,
!!k.subscribeButton.classic,k.channelId,!!k.subscribeButton.subscribed,F,G,e.player,!1);K.appendChild(F.element);e.D.push(F)}break;case "WEBSITE":e={L:"div",M3:["ytp-ce-element","ytp-ce-website"],B:{tabindex:"0","aria-label":k.cv||"","aria-hidden":"true"},S:[{L:"div",Z:"ytp-ce-element-shadow"},{L:"div",Z:"ytp-ce-expanding-overlay",S:[{L:"div",Z:"ytp-ce-expanding-overlay-hider"},{L:"div",Z:"ytp-ce-expanding-overlay-background"},{L:"div",Z:"ytp-ce-expanding-overlay-content",S:[{L:"div",Z:"ytp-ce-expanding-overlay-body",
S:[{L:"div",Z:"ytp-ce-expanding-overlay-body-padding",S:[{L:"div",Z:"ytp-ce-website-title",B:{dir:g.yw(k.title||"")},Ui:k.title},{L:"div",Z:"ytp-ce-website-metadata",Ui:k.metadata},{L:"a",M3:["ytp-ce-website-goto","ytp-ce-link"],B:{href:jt(e,k.targetUrl),target:"_blank",tabindex:"-1"},Ui:k.callToAction}]}]}]}]},{L:"div",Z:"ytp-ce-expanding-image",B:BL(k)},{L:"div",Z:"ytp-ce-expanding-icon",B:Kjg(k.iconUrl)}]};v=new g.C(e);break;case "CREATOR_MERCHANDISE":v="",k.productPrice&&(v={L:"div",Z:"ytp-ce-merchandise-price-container",
S:[{L:"div",Z:"ytp-ce-merchandise-price",Ui:k.productPrice}]},k.additionalFeesText&&v.S.push({L:"div",Z:"ytp-ce-merchandise-additional-fees",Ui:k.additionalFeesText})),e={L:"div",M3:["ytp-ce-element","ytp-ce-merchandise"],B:{tabindex:"0","aria-label":k.cv||"","aria-hidden":"true"},S:[{L:"div",Z:"ytp-ce-element-shadow"},{L:"div",Z:"ytp-ce-expanding-overlay",S:[{L:"div",Z:"ytp-ce-expanding-overlay-hider"},{L:"div",Z:"ytp-ce-expanding-overlay-background"},{L:"div",Z:"ytp-ce-expanding-overlay-content",
S:[{L:"div",Z:"ytp-ce-expanding-overlay-body",S:[{L:"div",Z:"ytp-ce-expanding-overlay-body-padding",S:[{L:"div",Z:"ytp-ce-merchandise-title",B:{dir:g.yw(k.title||"")},Ui:k.title},v,{L:"div",Z:"ytp-ce-merchandise-metadata",Ui:k.metadata},{L:"a",M3:["ytp-ce-merchandise-goto","ytp-ce-link"],B:{href:jt(e,k.targetUrl),target:"_blank",tabindex:"-1"},Ui:k.callToAction}]}]}]}]},{L:"div",Z:"ytp-ce-expanding-image",B:BL(k)},{L:"div",Z:"ytp-ce-merchandise-invideo-cta-container",S:[{L:"div",Z:"ytp-ce-merchandise-invideo-cta",
Ui:k.callToAction||void 0}]}]},v=new g.C(e)}k.isPlaceholder&&g.Qw(v.element,"ytp-ce-placeholder");return v},vPK=function(e,k,v){function F(){t(1)}
function K(){t(-1)}
k.listen("mouseenter",()=>{Ip(e,k,v)});
k.listen("mouseleave",()=>{uI(e,k,v)});
e.player.G().Y||k.listen("click",()=>{g.Qw(k.element,"ytp-ce-element-hover")});
k.listen("click",V=>{Gou(e,v,V)});
k.listen("keypress",V=>{Gou(e,v,V)});
k.listen("focus",()=>{Ip(e,k,v)});
k.listen("blur",()=>{uI(e,k,v)});
k.listen("touchstart",()=>{Ip(e,k,v)});
var G=g.kD("ytp-ce-expanding-overlay-hider",k.element);G&&k.N(G,"touchstart",V=>{V.stopPropagation();g.sI(k.element,"ytp-ce-element-hover");g.sI(k.element,"ytp-ce-force-expand")});
k.listen("keydown",V=>{e.YV=V.keyCode===9&&!V.shiftKey});
var t=V=>{e.X+=V;e.X>0?(g.Qw(k.element,"ytp-ce-force-expand"),lI(e,v.id,!0)):(g.sI(k.element,"ytp-ce-force-expand"),g.sI(k.element,"ytp-ce-element-hover"),lI(e,v.id,!1))};
G=V=>{V&&(k.listen("blur",()=>{V.style.display!="none"&&e.YV&&V.focus()}),k.N(V,"focus",F),k.N(V,"blur",K))};
G(g.kD("ytp-sb-subscribe",k.element));G(g.kD("ytp-sb-unsubscribe",k.element));k.listen("focus",F);k.listen("blur",K)},m4=function(e,k,v){function F(){G||(K++,K===k.length&&(t.stop(),v&&v()))}
if(!k||k.length===0||cL(e))v&&v();else{k=tdK(e,k);var K=0,G=!1,t=new g.Y1(()=>{G=!0;v&&v()},1E3,e);
t.start();for(e=0;e<k.length;e++)g.X7(k[e],F)}},BL=function(e){if(e.XK)var k=e.XK.thumbnails;
return Kjg(k?k[k.length-1].url:null)},jt=function(e,k){e=e.player.G();
if(k){if(k.startsWith("//"))return e.protocol+":"+k;if(k.startsWith("/"))return g.iB(e)+k}else return"";return k},Kjg=function(e){return e?{style:"background-image: url("+e+")"}:{}},Ip=function(e,k,v){g.rS(k.element,"ytp-ce-element-hover")||(v.type==="VIDEO"||v.type==="PLAYLIST"?g.Qw(k.element,"ytp-ce-element-hover"):e.player.G().Y?(new g.Y1(()=>{g.Qw(k.element,"ytp-ce-element-hover")},200)).start():g.Qw(k.element,"ytp-ce-element-hover"),m4(e,v.mM),lI(e,v.id,!0))},uI=function(e,k,v){g.sI(k.element,
"ytp-ce-element-hover");
g.sI(k.element,"ytp-ce-force-expand");lI(e,v.id,!1)},Gou=function(e,k,v){if(k.targetUrl&&(!v||v.type!=="keypress"||v.keyCode===13)){for(var F=v.target;F&&!g.rS(F,"ytp-ce-element");){g.rS(F,"subscribe-label")&&fM(e,k);
if(g.rS(F,"ytp-ce-channel-subscribe"))return;F=F.parentElement||null}if(!F||g.rS(F,"ytp-ce-element-hover")){v.preventDefault();v.stopPropagation();if(F=e.V[k.id])uI(e,F,k),F.element.blur();if(v.ctrlKey||v.metaKey||k.Og==="new")fM(e,k),e.player.sendVideoStatsEngageEvent(17,void 0),e.player.pauseVideo(),v=g.My(jt(e,k.targetUrl)),v=g.ld(v),g.Y7(v,void 0,k.sessionData);else{let K=g.JF(e.player.G())||e.player.getVideoData().Vd,G=()=>{var t=jt(e,k.targetUrl),V=k.sessionData,T=k.watchEndpoint,H=g.Hv(t);
K&&H&&(H.v||H.list)?e.player.GJ(H.v,V,H.list,!1,void 0,T||void 0):g.qE(t,V)};
fM(e,k,()=>{e.player.sendVideoStatsEngageEvent(17,G)})}}}},lI=function(e,k,v){e.Y&&(v?e.U.show():e.U.hide());
for(let F of Object.keys(e.V))F!==k&&g.jA(e.V[F].element,"ytp-ce-element-shadow-show",v)},fM=function(e,k,v){m4(e,k.clickUrls,v);
(e=g.MV())&&k.pk&&g.Zt(e,k.visualElement)},tdK=function(e,k){var v=e.player.getVideoData().clientPlaybackNonce;
e=e.player.getCurrentTime().toFixed(2);v={CPN:v,AD_CPN:v,MT:e};e=[];for(let F=0;F<k.length;F++)e.push(Vdy(k[F],v));return e},Vdy=function(e,k){return e.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,v=>{var F=unescape(v);
F=F.substring(1,F.length-1);return k[F]?escape(k[F]):v})},Tfx=function(e){return typeof e==="string"?e:""},DP=function(e,k,v){for(let F in k)if(k[F]===e)return e;
return v},yA=function(e){if(!e)return null;
var k=g.My(Tfx(e.value));k=g.ld(k);if(!k)return null;var v=DP(e.target,H_J,"current");if(v==null)e=null;else{var F=e.show_link_icon;e=new zj4(k,v,F==="true"||F==="false"?F==="true":!0,e.pause_on_navigation!=null?e.pause_on_navigation:!0)}return e},RjJ=function(e){if(!e)return null;
var k=DP(e.type,XEL),v=DP(e.trigger,S4x);e=e.url;e=Array.isArray(e)&&e.length?e[0]:e;e=yA(e?e:null);return k?new gPn(k,v,e):null},WjS=function(e,k){return g.Ay(e.action,k)},MC=function(e,k){e="background-image: url("+e+");";
var v=[];k&&v.push(k);return{L:"div",Z:"iv-card-image",B:{style:e},S:v}},ap=function(e){return e.customMessage?PL("div","iv-card-message",e.customMessage):""},hN=function(e){if(!e.metaInfo||e.metaInfo.length===0)return"";
var k=[];for(let v of e.metaInfo)k.push(PL("li","",v));return{L:"ul",Z:"iv-card-meta-info",S:k}},UA=function(e,k,v,F){if(F)for(let K of k)e.W(K,F,v.id,v.sessionData,v.KE.click,5)},PL=function(e,k,v){k?typeof k==="string"?k={"class":k}:Array.isArray(k)&&(k={"class":k.join(" ")}):k={};
k.dir=g.yw(v);return{L:e,B:k,Ui:v}},nPJ=function(e){if(!e.customMessage)return"";
var k=["iv-card-action","iv-card-primary-link"],v={};e.jI&&(k.push("iv-card-action-icon"),v.style="background-image: url("+e.jI+");");v.dir=g.yw(e.customMessage);var F=[{L:"span",Ui:e.customMessage}];e.showLinkIcon&&(F.push("\u00a0"),F.push({L:"span",Z:"iv-card-link-icon"}));return{L:"div",M3:k,B:v,S:F}},dzg=function(e){var k;
(k=e)&&!(k=e.length>1?e.charAt(0)==="/"&&e.charAt(1)!=="/":e==="/")&&(k=e.replace(/^(https?:)?\/\//,"").split("/",1),k=!k||k.length<1||!k[0]?[]:k[0].toLowerCase().split(".").reverse(),k=k[0]==="com"&&k[1]==="youtube"||k[0]==="be"&&k[1]==="youtu");return k?e.indexOf("/redirect?")===-1:!1},EPx=function(e,k){return k?k:dzg(e)?"current":"new"},AN=function(e,k,v,F,K,G,t){e.context.W.listen(k,"click",V=>{e.Fk(v,F,K,G||[],t||0,V)});
e.context.W.listen(k,"touchstart",()=>{e.Cd=!1});
e.context.W.listen(k,"touchmove",()=>{e.Cd=!0})},J27=function(e){if(g.y(e,g.vZ)?.url)return g.y(e,g.vZ).url;
if((e=g.y(e,g.pw))&&e.videoId){let k="/watch?v="+e.videoId;e.playlistId&&(k+="&list="+e.playlistId);e.index&&(k+="&index="+e.index);e.startTimeSeconds&&(k+="&t="+e.startTimeSeconds);return k}return null},CM=function(e,k,v){return{Fv:(e.impressionLoggingUrlsV2s||[]).map(F=>F.baseUrl||""),
click:(v.loggingUrls||[]).map(F=>F.baseUrl||""),
close:(k.dismissLoggingUrlsV2s||[]).map(F=>F.baseUrl||""),
us:(k.impressionLoggingUrlsV2s||[]).map(F=>F.baseUrl||""),
UV:(k.clickLoggingUrlsV2s||[]).map(F=>F.baseUrl||"")}},ka=function(e,k){if(k.onClickCommand&&g.y(k.onClickCommand,g.PbQ)?.targetId==="engagement-panel-error-corrections"){e.j=k;
var v=!0}else v=!1;if(!v||pEx(e,k))if(v=LjJ(e,k)){var F={nm:k,EU:v.element,MU:!1};if(k.onClickCommand)e.J.O("web_infocards_teaser_show_logging_fix")&&(e.HX||O_U(e),op(e,k.id),v=e.findLastIndex(F),g.Xp(e.cards,v,0,F));else{e.isInitialized||$zV(e);op(e,k.id);let K=e.findLastIndex(F);g.Xp(e.cards,K,0,F);v.Kd(e.V,K);e.rX()}k.autoOpen?e.addCueRange(k.startMs,0x8000000000000,k.id,()=>{e.Y||(e.W=F,bI(e),q4U(e,F),e_(e,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(v=e.context.J.getCurrentTime()*1E3,v<5E3&&v>k.startMs&&
Y4x(e,F),e.addCueRange(k.startMs,k.startMs+1,k.id,()=>{Y4x(e,F)}),bI(e))}},v9=function(e){e.Y&&(e.cw.hide(),e.R1.V(),g.sI(e.context.J.getRootNode(),g.E$.IV_DRAWER_OPEN),e.Y=!1,LM(e.J),e.U&&e.U.stop(),e.U=new g.Y1(()=>{e.iu&&(e.iu.focus(),e.iu=null)},330),e.U.start())},Z_x=function(e,k){k=k.data;
k.autoOpenMs&&e.addCueRange(k.autoOpenMs,0x8000000000000,"",()=>{e_(e,"YOUTUBE_DRAWER_AUTO_OPEN")});
k.autoCloseMs&&e.addCueRange(k.autoCloseMs,0x8000000000000,"",()=>{v9(e)});
var v=k.headerText;g.Jv(e.Uj,v);e.D&&e.D.setAttribute("data-tooltip-title",v);k.eventId&&(e.eventId=k.eventId);e.Jz=g.mu(k.trackingParams);e.X=g.mu(k.closeTrackingParams);e.oM=g.mu(k.iconTrackingParams)},FL=function(e,k,v){var F=-1,K=-1;
for(let G=0;G<e.length;G++){if(e[G].height===k||e[G].width===v)return e[G];((e[G].height||0)<k||(e[G].width||0)<v)&&(F<0||(e[F].height||0)<(e[G].height||0)||(e[F].width||0)<(e[G].width||0))?F=G:((e[G].height||0)>=k||(e[G].width||0)>=v)&&(K<0||(e[K].height||0)>(e[G].height||0)||(e[K].width||0)>(e[G].width||0))&&(K=G)}return e[K>=0?K:F]},KQ=function(e,k,v,F){return{feature:v.feature?v.feature:"cards",
src_vid:e.context.videoData.videoId,annotation_id:k,ei:e.context.videoData.eventId||"",itct:F.trackingParams||""}},wEu=function(e,k){var v=k.cardId?k.cardId:`cr:${e.K}`,F=e.J.G().experiments.Ei("enable_error_corrections_infocard_web_client");
if(!k.content&&k.teaser.simpleCardTeaserRenderer&&F){F=k.teaser.simpleCardTeaserRenderer;var K=k.icon?k.icon.infoCardIconRenderer:null;if(F.channelAvatar&&F.channelAvatar.thumbnails&&F.channelAvatar.thumbnails.length>0)var G=FL(F.channelAvatar.thumbnails,22,22).url;k={id:v,timestamp:e.K,type:"simple",teaserText:g.sl(F.message),teaserDurationMs:Number(k.cueRanges[0].teaserDurationMs),startMs:Number(k.cueRanges[0].startCardActiveMs),autoOpen:!!k.autoOpen,sessionData:{},sponsored:!1,KE:{},cB:null,CE:F.trackingParams?
g.mu(F.trackingParams):null,oM:K&&K.trackingParams?g.mu(K.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,jI:null,title:"",customMessage:"",url:null,onClickCommand:F.onTapCommand||null,Zu:G};ka(e,k)}else if(k.content?.simpleCardContentRenderer){if(!k.cueRanges.length)return;G=k.content?.simpleCardContentRenderer;F=k.teaser.simpleCardTeaserRenderer;K=k.icon?k.icon.infoCardIconRenderer:null;k={id:v,timestamp:e.K,type:"simple",teaserText:g.sl(F.message),teaserDurationMs:Number(k.cueRanges[0].teaserDurationMs),
startMs:Number(k.cueRanges[0].startCardActiveMs),autoOpen:!!k.autoOpen,sessionData:KQ(e,v,k,G),sponsored:!1,KE:CM(G,F,G.command),cB:G.trackingParams?g.mu(G.trackingParams):null,CE:F.trackingParams?g.mu(F.trackingParams):null,oM:K&&K.trackingParams?g.mu(K.trackingParams):null,imageUrl:FL(G.image.thumbnails,290,290).url,displayDomain:G.displayDomain?g.sl(G.displayDomain):null,showLinkIcon:!!G.showLinkIcon,jI:null,title:G.title?g.sl(G.title):"",customMessage:G.callToAction?g.sl(G.callToAction):"",url:g.y(G.command,
g.vZ).url?yA({pause_on_navigation:!e.context.videoData.isLivePlayback,target:"new",value:g.y(G.command,g.vZ).url}):null,onClickCommand:null};ka(e,k)}else if(k.content?.collaboratorInfoCardContentRenderer){if(!k.cueRanges.length)return;G=k.content?.collaboratorInfoCardContentRenderer;F=k.teaser.simpleCardTeaserRenderer;K=k.icon?k.icon.infoCardIconRenderer:null;k={id:v,timestamp:e.K,type:"collaborator",teaserText:g.sl(F.message),teaserDurationMs:Number(k.cueRanges[0].teaserDurationMs),startMs:Number(k.cueRanges[0].startCardActiveMs),
autoOpen:!!k.autoOpen,sessionData:KQ(e,v,k,G),sponsored:!1,KE:CM(G,F,G.endpoint),cB:G.trackingParams?g.mu(G.trackingParams):null,CE:F.trackingParams?g.mu(F.trackingParams):null,oM:K&&K.trackingParams?g.mu(K.trackingParams):null,channelId:g.y(G.endpoint,g.ps).browseId,customMessage:G.customText?g.sl(G.customText):null,profileImageUrl:FL(G.channelAvatar.thumbnails,290,290).url,title:G.channelName?g.sl(G.channelName):"",metaInfo:[G.subscriberCountText?g.sl(G.subscriberCountText):""],url:yA({pause_on_navigation:!e.context.videoData.isLivePlayback,
target:"new",value:g.y(G.endpoint,g.ps).canonicalBaseUrl?g.y(G.endpoint,g.ps).canonicalBaseUrl:`/channel/${g.y(G.endpoint,g.ps).browseId}`}),onClickCommand:null};ka(e,k)}else if(k.content?.playlistInfoCardContentRenderer){if(!k.cueRanges.length)return;G=k.content?.playlistInfoCardContentRenderer;F=k.teaser.simpleCardTeaserRenderer;K=k.icon?k.icon.infoCardIconRenderer:null;k={id:v,timestamp:e.K,type:"playlist",teaserText:g.sl(F.message),teaserDurationMs:Number(k.cueRanges[0].teaserDurationMs),startMs:Number(k.cueRanges[0].startCardActiveMs),
autoOpen:!!k.autoOpen,sessionData:KQ(e,v,k,G),sponsored:!1,KE:CM(G,F,G.action),cB:G.trackingParams?g.mu(G.trackingParams):null,CE:F.trackingParams?g.mu(F.trackingParams):null,oM:K&&K.trackingParams?g.mu(K.trackingParams):null,hc:FL(G.playlistThumbnail.thumbnails,258,290).url,customMessage:G.customMessage?g.sl(G.customMessage):null,playlistVideoCount:g.sl(G.playlistVideoCount),title:G.playlistTitle?g.sl(G.playlistTitle):"",metaInfo:[G.channelName?g.sl(G.channelName):"",G.videoCountText?g.sl(G.videoCountText):
""],url:yA({pause_on_navigation:!e.context.videoData.isLivePlayback,target:"new",value:J27(G.action)}),onClickCommand:null};ka(e,k)}else if(k.content?.videoInfoCardContentRenderer){if(!k.cueRanges.length)return;G=k.content?.videoInfoCardContentRenderer;F=k.teaser.simpleCardTeaserRenderer;K=k.icon?k.icon.infoCardIconRenderer:null;k={id:v,timestamp:e.K,type:"video",teaserText:g.sl(F.message),teaserDurationMs:Number(k.cueRanges[0].teaserDurationMs),startMs:Number(k.cueRanges[0].startCardActiveMs),autoOpen:!!k.autoOpen,
sessionData:KQ(e,v,k,G),sponsored:!1,KE:CM(G,F,G.action),cB:G.trackingParams?g.mu(G.trackingParams):null,CE:F.trackingParams?g.mu(F.trackingParams):null,oM:K&&K.trackingParams?g.mu(K.trackingParams):null,hc:FL(G.videoThumbnail.thumbnails,258,290).url,videoDuration:G.lengthString?g.sl(G.lengthString):null,customMessage:G.customMessage?g.sl(G.customMessage):null,title:G.videoTitle?g.sl(G.videoTitle):"",metaInfo:[G.channelName?g.sl(G.channelName):"",G.viewCountText?g.sl(G.viewCountText):""],isLiveNow:!!G.badge,
url:yA({pause_on_navigation:!e.context.videoData.isLivePlayback,target:"new",value:J27(G.action)}),onClickCommand:null};ka(e,k)}e.K++},i_L=function(e,k){return g.Ay(e.cards,v=>v.nm.id===k)},bI=function(e){g.jA(e.J.getRootNode(),"ytp-cards-shopping-active",Nfg(e))},op=function(e,k){if(k=i_L(e,k))k===e.W&&(e.W=null),e.J.removeCueRange(k.nm.id),g.dV(k.EU),g.vS(e.cards,k),e.rX(),bI(e)},e_=function(e,k,v){if(!e.Y){e.cw.show();
e.mH=new g.Y1(()=>{g.Qw(e.context.J.getRootNode(),g.E$.IV_DRAWER_OPEN)},0);
e.mH.start();e.R1.N(e.V,"mousewheel",K=>{e.Hw.start();K.preventDefault();K=K||window.event;var G=0;K.type=="MozMousePixelScroll"?G=0==(K.axis==K.HORIZONTAL_AXIS)?K.detail:0:window.opera?G=K.detail:G=K.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?K.wheelDeltaY/-30:K.wheelDeltaY/-1.2:K.wheelDelta/-1.6:K.wheelDeltaY/-3;if(K=G)e.V.scrollTop+=K});
e.Y=!0;var F=g.MV();F&&e.Jz&&e.X&&g.q_(F,[e.Jz,e.X]);k={TRIGGER_TYPE:k};for(let K of e.cards)K.MU||(K.MU=!0,xzU(e.context.logger,K.nm.KE.Fv,k)),F&&g.q_(F,[K.nm.cB]);LM(e.J);v&&(e.U=new g.Y1(()=>{e.iu=e.D;e.WX.focus()},330),e.U.start())}},$zV=function(e){g.cW(e.Jq(),[g.E$.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.Au(e.J,e.A,5);e.bq();e.D=g.kD("ytp-cards-button",e.J.getRootNode());e.WX=g.kD("iv-drawer-close-button",e.A);e.isInitialized=!0},O_U=function(e){e.YV.push(g.Za("iv-teaser-shown",e.oH,e));
e.YV.push(g.Za("iv-teaser-hidden",e.j4,e));e.YV.push(g.Za("iv-teaser-clicked",e.IH,e));e.HX=!0},pEx=function(e,k){e.j=k;
var v=e.J.getVideoData();if(!v)return!1;v=g.hF(v.getWatchNextResponse());if(v?.markersMap)for(let K=0;v?.markersMap.length>K;K++){var F=v?.markersMap[K];if(F.key==="ERROR_CORRECTION_MARKERS"&&(F=F.value?.markers)&&F.length>0)return k.startMs=g.y(F[0],g.qY0)?.timeRangeStartMillis||0,e.j=null,!0}return!1},LjJ=function(e,k){switch(k.type){case "simple":e=e.Az;
var v=k.displayDomain?{L:"div",Z:"iv-card-image-text",Ui:k.displayDomain}:void 0;var F=nPJ(k);v={L:"div",M3:["iv-card"],S:[{L:"a",Z:"iv-click-target",B:{href:k.url?k.url.W()||"":""},S:[MC(k.imageUrl,v),{L:"div",Z:"iv-card-content",S:[PL("h2",void 0,k.title),F]}]}]};v=new g.C(v);UA(e,g.bW("iv-click-target",v.element),k,k.url);k=v;break;case "collaborator":e=e.Az;v={L:"div",M3:["iv-card","iv-card-channel"],S:[{L:"a",M3:["iv-click-target"],B:{href:k.url.W()||"","data-ytid":k.channelId},S:[MC(k.profileImageUrl),
{L:"div",Z:"iv-card-content",S:[ap(k),{L:"h2",Z:"iv-card-primary-link",Ui:k.title},hN(k)]}]}]};v=new g.C(v);UA(e,g.bW("iv-click-target",v.element),k,k.url);k=v;break;case "playlist":e=e.Az;v={L:"div",M3:["iv-card","iv-card-playlist"],S:[{L:"a",Z:"iv-click-target",B:{href:k.url.W()||""},S:[MC(k.hc,{L:"div",Z:"iv-card-image-overlay",S:[{L:"span",Z:"iv-card-playlist-video-count",Ui:k.playlistVideoCount}]}),{L:"div",Z:"iv-card-content",S:[ap(k),PL("h2","iv-card-primary-link",k.title),hN(k)]}]}]};v=new g.C(v);
UA(e,g.bW("iv-click-target",v.element),k,k.url);k=v;break;case "productListing":e=e.Az;var K=k.offers.length!=0;v=["iv-card"];F="";var G=nPJ(k);K&&(v.push("iv-card-product-listing"),F="iv-card-primary-link",G=k.offers[0],K=[],G.price&&K.push({L:"div",Z:"iv-card-offer-price",Ui:G.price}),G.merchant&&K.push({L:"div",Z:"iv-card-offer-merchant",Ui:G.merchant}),G={L:"div",S:K});K=k.url?k.url.W()||"":"";v={L:"div",M3:v,B:{tabindex:"0"},S:[{L:"a",M3:["iv-card-image","iv-click-target"],B:{style:"background-image: url("+
k.imageUrl+");",href:K,"aria-hidden":"true",tabindex:"-1"}},{L:"div",Z:"iv-card-content",S:[k.sponsored?{L:"div",Z:"iv-card-sponsored",S:["Sponsored",{L:"div",Z:"iv-ad-info-container",S:[{L:"div",Z:"iv-ad-info",Ui:"{{adInfo}}"},{L:"div",Z:"iv-ad-info-icon-container",S:[{L:"div",Z:"iv-ad-info-icon"},{L:"div",Z:"iv-ad-info-callout"}]}]}]}:"",{L:"a",Z:"iv-click-target",B:{href:K},S:[PL("h2",F,k.title),G]}]}]};v=new g.C(v);F=g.Sz("span");g.Jv(F,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
v.setContent(F,"adInfo");UA(e,g.bW("iv-click-target",v.element),k,k.url);k=v;break;case "video":e=e.Az;v=k.isLiveNow?{L:"span",M3:["yt-badge","yt-badge-live"],Ui:"LIVE NOW"}:null;v={L:"div",M3:["iv-card","iv-card-video"],S:[{L:"a",Z:"iv-click-target",B:{href:k.url?.W()||""},S:[MC(k.hc,k.videoDuration?{L:"span",Z:"iv-card-video-duration",Ui:k.videoDuration}:void 0),{L:"div",Z:"iv-card-content",S:[ap(k),PL("h2","iv-card-primary-link",k.title),hN(k),v]}]}]};v=new g.C(v);UA(e,g.bW("iv-click-target",v.element),
k,k.url);k=v;break;default:return null}return k},Y4x=function(e,k){if(!g.rS(e.J.getRootNode(),"ytp-cards-teaser-shown")){if(e.W!==k){var v=g.MV(),F=e.W?e.W.nm.oM:e.oM;
v&&F&&g.YL(v,[F]);e.W=k;bI(e)}(v=e.isInitialized&&e.Jq().style.display=="none")||(v=e.context.J.getPlayerState(),F=v===0&&e.context.J.getCurrentTime()===0,v=!(v===1||v===3||F));v||k.nm.teaserDurationMs&&e.J.ZO(!0,{teaserText:k.nm.teaserText,durationMs:k.nm.teaserDurationMs,onClickCommand:k.nm.onClickCommand,Zu:k.nm.Zu??null});e.SQ.isActive()||((!e.Y||!e.Hw.isActive()&&e.I1)&&q4U(e,k),e.SQ.start(910+k.nm.teaserDurationMs))}},Nfg=function(e){return e.W?e.W.nm.type==="productListing":e.J.O("enable_wn_infocards")?
!!e.cards?.length&&g.hy(e.cards,k=>k.nm.type==="productListing"):g.hy(e.cards,k=>k.nm.type==="productListing")},q4U=function(e,k){e.C.w9?(k=new ZP([0,
e.V.scrollTop],[0,k.EU.offsetTop],600,COK),e.context.Y.listen(k,"animate",v=>{e.V.scrollTop=v.y}),e.context.Y.listen(k,"finish",v=>{e.V.scrollTop=v.y}),k.play()):(e.C.xv(!0),e.V.scrollTop=k.EU.offsetTop,e.C.xv(!1))},G8=function(e){return e.W&&e.W.nm?e.W.nm:e.cards[0]&&e.cards[0].nm?e.cards[0].nm:null},r2n=function(e){var k=e.annotation.data;
"start_ms"in k&&"end_ms"in k&&e.addCueRange(Number(k.start_ms),Number(k.end_ms),e.annotation.id,()=>{e.show()},()=>{e.hide()})},QE7=function(e,k){var v=DSg(k).width;
g.GC(k,v);v=new iI(k,[v,k.offsetTop],[v-v,k.offsetTop],200,AdJ);g.w(e,v);e.context.Y.listen(v,"begin",()=>{g.RF(k,!0)});
v.play()},tw=function(e,k,v){v.stopPropagation();
c2J(e);sES(e,k);e.W.focus()},BfV=function(e){var k=e.annotation.data;
if(e.annotation.style==="cta")var v=6;else if(e.annotation.style==="video"||e.annotation.style==="playlist")v=7;e.K=k.collapsedelay_ms||e.K;var F=["iv-promo","iv-promo-inactive"];e.Jq().setAttribute("aria-hidden","true");e.Jq().setAttribute("aria-label","Promotion");e.Jq().tabIndex=0;var K=e.annotation.a7(),G=k.image_url;if(G){var t=e.createElement({L:"div",M3:["iv-promo-img","iv-click-target"]});G=e.createElement({L:"img",B:{src:G,"aria-hidden":"true"}});t.appendChild(G);k.video_duration&&!k.is_live?
(G=e.createElement({L:"span",Z:"iv-promo-video-duration",Ui:k.video_duration}),t.appendChild(G)):k.playlist_length&&(G=e.createElement({L:"span",Z:"iv-promo-playlist-length",Ui:k.playlist_length.toString()}),t.appendChild(G));K&&AN(e,t,K,e.annotation.id,k.session_data,void 0,v)}K?(G=e.createElement({L:"a",Z:"iv-promo-txt"}),g.hA(G,K.W()),e.W=G):e.W=e.createElement({L:"div",Z:"iv-promo-txt"});switch(e.annotation.style){case "cta":case "website":var V=e.createElement({L:"p",S:[{L:"strong",Ui:k.text_line_1}]});
var T=e.createElement({L:"p",S:[{L:"span",Z:"iv-promo-link",Ui:k.text_line_2}]});if(G=k.text_line_3){F.push("iv-promo-website-card-cta-redesign");var H=e.createElement({L:"button",M3:["iv-promo-round-expand-icon","ytp-button"]});G=e.createElement({L:"button",M3:["iv-button","iv-promo-button"],S:[{L:"span",Z:"iv-button-content",Ui:G}]});var z=e.createElement({L:"div",Z:"iv-promo-button-container"});z.appendChild(G);K&&AN(e,e.Jq(),K,e.annotation.id,k.session_data,void 0,v)}g.Qw(e.W,"iv-click-target");
K&&AN(e,e.W,K,e.annotation.id,k.session_data,void 0,v);break;case "playlist":case "video":V=e.createElement({L:"p",S:[{L:"span",Ui:k.text_line_1}]}),T=e.createElement({L:"p",S:[{L:"strong",Ui:k.text_line_2}]}),k.is_live&&(V=T,T=e.createElement({L:"span",M3:["yt-badge","iv-promo-badge-live"],Ui:"LIVE NOW"})),g.Qw(e.W,"iv-click-target"),K&&AN(e,e.W,K,e.annotation.id,k.session_data,void 0,v),F.push("iv-promo-video")}V&&e.W.appendChild(V);T&&e.W.appendChild(T);e.X.appendChild(e.W);z&&e.X.appendChild(z);
v=e.createElement({L:"div",Z:"iv-promo-actions"});e.V=e.createElement({L:"button",M3:["iv-promo-expand","ytp-button"]});e.V.title="Expand";e.context.W.listen(e.V,"click",X=>{tw(e,5E3,X)});
v.appendChild(e.V);g.RF(e.V,!1);e.context.W.listen(e.Jq(),"mouseover",e.Hw,e);e.context.W.listen(e.Jq(),"mouseout",e.Az,e);e.context.W.listen(e.Jq(),"touchend",X=>{tw(e,5E3,X)});
e.Y=e.createElement({L:"button",M3:["iv-promo-close","ytp-button"]});e.Y.title="Close";e.context.W.listen(e.Y,"click",e.annotation.style==="cta"&&k.text_line_3?e.j:e.YV,e);v.appendChild(e.Y);g.cW(e.Jq(),F);t&&(g.RB(e.Jq(),t),H&&t.appendChild(H));g.RB(e.Jq(),e.X);g.RB(e.Jq(),v)},Vl=function(e){e.A&&(g.Rg.clearTimeout(e.A),e.A=null)},c2J=function(e){e.U.stop();
e.isCollapsed&&(g.BW(e.Jq(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),e.isCollapsed=!1,e.W&&e.W.removeAttribute("aria-hidden"),g.RF(e.V,!1),g.RF(e.Y,!0))},sES=function(e,k){e.A||(e.A=g.lp(function(){Vl(this);
jEy(this)},k,e))},jEy=function(e){e.isCollapsed||e.D||e.A||(g.Qw(e.Jq(),"iv-promo-collapsed"),e.isCollapsed=!0,e.U.start())},xzU=function(e,k,v){k&&(v?T8(e,k.map(F=>g.WW(F,v))):T8(e,k))},T8=function(e,k,v,F){var K=1,G=void 0,t=-1;
if(v){let V=!1;G=()=>{K--;K||V||(clearTimeout(t),V=!0,v())};
t=setTimeout(()=>{V=!0;v()},1E3)}for(let V of k||[])K++,g.X7(V,G);
F&&(K++,F!==0&&e.J.sendVideoStatsEngageEvent(F,G))},I3U=function(e){return e==="annotation-editor"||e==="live-dashboard"},uRU=function(e){e.A&&(e.player.removeEventListener("videodatachange",e.A),e.A=null)},l3V=function(e){e=e.createElement({L:"div",
M3:["annotation","annotation-type-custom"]});g.RF(e,!1);return e},z8=function(e,k){var v=!1,F=k.getElementsByTagName("annotations");
if(F&&!(F.length<1)&&(F=F[0].getAttribute("itct"))){var K=g.MV();if(K){var G=g.yf();G&&g.Ka(g.R_)(void 0,K,G,[g.mu(F)])}}k=k.getElementsByTagName("annotation");for(F=0;F<k.length;F++){var t=mzL(e,k[F]);K=null;try{a:{if(!t){K=null;break a}var V=t.id;G=/.+/;let R=typeof V==="string"&&G!=null&&V!=null&&V.match(G)?V:"",J=DP(t.type,f37),Z=DP(t.style,Dz4),B=Tfx(t.data),l=B.length!==0?JSON.parse(B):{};b:{var T=t.action;G=RjJ;if(T==null){var H=null;break b}if(g.LE(T)){t=[];for(let D of T){let P=G(D);P&&t.push(P)}H=
t;break b}let f=G(T);H=f?[f]:[]}G=H;K=R&&J?new y2L(R,J,Z,G,l):null}}catch(R){}if(K)if(K.type==="branding"||K.type==="promotion"){G=e;t=K;var z=l3V(G),X=null;switch(t.type){case "branding":if(G.player.G().i4)break;G.player.O("web_player_overlay_positioned_layout")?(z.setAttribute("data-overlay-order","11"),G.player.nj(z,4,!0)):G.V.element.appendChild(z);X=new MdK(z,H9(G),t);break;case "promotion":g.Au(G.player,z,4),X=new PSV(z,H9(G),t)}X&&X.Vp();X&&(g.w(e,X),e.K[K.id]=X)}else if(K.type==="card"||K.type===
"drawer"){e.W||(e.W=a37(e),g.w(e,e.W));if(K.type==="card"){z=e.W;var S=(v=K)&&v.data&&v.data.card_type;K=v.data;if(S)switch(G=K.tracking||{},G={Fv:G.impression,click:G.click,close:G.close,us:G.teaser_impression,UV:G.teaser_click},t=K.tracking_params||{},X=null,S){case "collaborator":v={id:v.id,timestamp:K.timestamp||0,type:K.card_type,teaserText:K.teaser_text,teaserDurationMs:K.teaser_duration_ms,startMs:K.start_ms,autoOpen:K.auto_open||!1,sessionData:K.session_data||{},sponsored:K.sponsored||!1,
KE:G,cB:t.card?g.mu(t.card):null,CE:t.teaser?g.mu(t.teaser):null,oM:t.icon?g.mu(t.icon):null,channelId:K.channel_id,customMessage:K.custom_message?K.custom_message:null,profileImageUrl:K.image_url,title:K.title,metaInfo:K.meta_info,url:yA({pause_on_navigation:K.pause_on_navigation,target:K.target||"new",value:K.url}),onClickCommand:null};ka(z,v);break;case "playlist":v={id:v.id,timestamp:K.timestamp||0,type:K.card_type,teaserText:K.teaser_text,teaserDurationMs:K.teaser_duration_ms,startMs:K.start_ms,
autoOpen:K.auto_open||!1,sessionData:K.session_data||{},sponsored:K.sponsored||!1,KE:G,cB:t.card?g.mu(t.card):null,CE:t.teaser?g.mu(t.teaser):null,oM:t.icon?g.mu(t.icon):null,hc:K.image_url,playlistVideoCount:K.playlist_video_count,customMessage:K.custom_message?K.custom_message:null,title:K.title,metaInfo:K.meta_info,url:yA({pause_on_navigation:K.pause_on_navigation,target:K.target||"new",value:K.url}),onClickCommand:null};ka(z,v);break;case "productListing":K.signin_url&&(X=yA({target:"current",
value:K.signin_url}));S=[];let R=K.offers||[];for(let J=0;J<R.length;J++)S.push(new hjy(g.J$(R[J].merchant),g.J$(R[J].price)));v={id:v.id,timestamp:K.timestamp||0,type:K.card_type,teaserText:K.teaser_text,teaserDurationMs:K.teaser_duration_ms,startMs:K.start_ms,autoOpen:K.auto_open||!1,sessionData:K.session_data||{},sponsored:K.sponsored||!1,KE:G,cB:t.card?g.mu(t.card):null,CE:t.teaser?g.mu(t.teaser):null,oM:t.icon?g.mu(t.icon):null,imageUrl:K.image_url,displayDomain:K.display_domain?K.display_domain:
null,showLinkIcon:!!K.show_link_icon,jI:K.button_icon_url?K.button_icon_url:null,title:K.title,customMessage:K.custom_message?K.custom_message:null,url:yA({pause_on_navigation:K.pause_on_navigation,target:K.target||"new",value:K.url}),Iwu:X,iLu:K.signin_title?K.signin_title:void 0,rWH:K.signin_message?K.signin_message:void 0,offers:S,onClickCommand:null};ka(z,v);break;case "simple":v={id:v.id,timestamp:K.timestamp||0,type:K.card_type,teaserText:K.teaser_text,teaserDurationMs:K.teaser_duration_ms,
startMs:K.start_ms,autoOpen:K.auto_open||!1,sessionData:K.session_data||{},sponsored:K.sponsored||!1,KE:G,cB:t.card?g.mu(t.card):null,CE:t.teaser?g.mu(t.teaser):null,oM:t.icon?g.mu(t.icon):null,imageUrl:K.image_url,displayDomain:K.display_domain?K.display_domain:null,showLinkIcon:!!K.show_link_icon,jI:K.button_icon_url?K.button_icon_url:null,title:K.title,customMessage:K.custom_message?K.custom_message:null,url:yA({pause_on_navigation:K.pause_on_navigation,target:K.target||"new",value:K.url}),onClickCommand:null};
ka(z,v);break;case "video":v={id:v.id,timestamp:K.timestamp||0,type:K.card_type,teaserText:K.teaser_text,teaserDurationMs:K.teaser_duration_ms,startMs:K.start_ms,autoOpen:K.auto_open||!1,sessionData:K.session_data||{},sponsored:K.sponsored||!1,KE:G,cB:t.card?g.mu(t.card):null,CE:t.teaser?g.mu(t.teaser):null,oM:t.icon?g.mu(t.icon):null,hc:K.image_url,videoDuration:K.video_duration||null,customMessage:K.custom_message?K.custom_message:null,title:K.title,metaInfo:K.meta_info,isLiveNow:!!K.is_live_now,
url:yA({pause_on_navigation:K.pause_on_navigation,target:K.target||"new",value:K.url}),onClickCommand:null},ka(z,v)}}else Z_x(e.W,K);v=!0}}v&&(LM(e.player),e.C())},Uzn=function(e){var k=e.player.G();
e=e.player.getVideoData();return(k.annotationsLoadPolicy||e.annotationsLoadPolicy)===1&&!e.MK||k.I1.get(e.videoId)||e.jv()||g.X5(e)?!0:!1},A2U=function(e,k){k=!k.isCued()&&!k.W(1024);
e.V.xv(k);e.Y.xv(k)},eJp=function(e,k){var v=k.videoId,F=G=>{var t=e.loadNumber;
e.X=null;e.loaded&&e.loadNumber===t&&e.player.getVideoData().videoId===v&&(G=g.da(G)&&G.responseXML?G.responseXML:null)&&(z8(e,G),g.Qw(e.player.getRootNode(),"iv-module-loaded"))};
g.C9()&&(F=CSK(e,F));var K={format:"XML",onFinish:F,onError:()=>{e.X=null},
urlParams:{}};k.isPharma&&(K.urlParams.pharma="1");K.method="POST";K.withCredentials=!0;(F=e.player.G().I1.get(v))&&oPK(K,F);F=F&&F.qW;if(!k.TR||F)e.A=()=>{if(!e.j)e.onVideoDataChange(K);var G=e.player.getVideoData();G?.be()&&!e.YV&&b_x(e,G)},e.player.addEventListener("videodatachange",e.A)},XL=function(e,k){var v=!1;
e.W||(e.W=a37(e),g.w(e,e.W));for(var F of k.cards||[])F.cardRenderer&&(wEu(e.W,F.cardRenderer),v=!0);v&&(e.player.getVideoData()?.be()||(v=e.W,F=k.headerText?g.sl(k.headerText):"",g.Jv(v.Uj,F),v.D&&v.D.setAttribute("data-tooltip-title",F),v.context.videoData.eventId&&(v.eventId=v.context.videoData.eventId),v.Jz=k.trackingParams?g.mu(k.trackingParams):null,v.X=k.closeButton.infoCardIconRenderer.trackingParams?g.mu(k.closeButton.infoCardIconRenderer.trackingParams):null,v.oM=k.icon.infoCardIconRenderer.trackingParams?
g.mu(k.icon.infoCardIconRenderer.trackingParams):null,e.C()),LM(e.player))},b_x=function(e,k){if(k=k.getWatchNextResponse()?.cards?.cardCollectionRenderer)e.YV=!0,XL(e,k),k.headerText&&e.VC&&(k=g.sl(k.headerText),e.VC.setAttribute("data-tooltip-title",k))},CSK=function(e,k){return(...v)=>{e.bu()||e.Vp.push(g.dS.gI(()=>{k(...v)}))}},oPK=function(e,k){e.method="POST";
e.postParams=e.postParams||{};k.qW&&(e.postParams.ic_coll=k.qW);k.jP&&(e.postParams.ic_track=k.jP)},mzL=function(e,k){var v={};
for(var F of k.attributes)v[F.name]=F.nodeValue;for(F=0;F<k.childNodes.length;F++){let G=k.childNodes[F];if(!g.$Q(G)||G.nodeType!=1)continue;var K=void 0;if(v[G.tagName])K=v[G.tagName];else if(G.tagName==="data"){G.childNodes.length>0&&(K=G.childNodes[0].nodeValue,v[G.tagName]=typeof K==="string"?K.trim():K);continue}else K=[],v[G.tagName]=K;G&&G.tagName==="TEXT"?G.childNodes.length===1&&G.childNodes[0].nodeType===3?K.push(G.childNodes[0].nodeValue):K.push(""):G&&K.push(mzL(e,G))}return v},H9=function(e){if(!e.D){let k=
new kOg(e);
g.w(e,k);let v=new g.Fx(e);g.w(e,v);e.D=new v_4(k,v,e.player.G(),e.player.getVideoData(),e.logger,e.player,e.i4)}return e.D},FOy=function(e){var k=e.player.getVideoData();
if(k.wO){var v=e.player.G().I1.get(k.videoId);if(v){var F={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:(K,G,t)=>{K=e.loadNumber;G=k.videoId;e.loaded&&e.loadNumber===K&&e.player.getVideoData().videoId===G&&(t=g.da(t)&&t.responseXML?t.responseXML:null)&&z8(e,t)}};
g.C9()&&(F.onFinish=CSK(e,F.onFinish));F.postParams={ic_only:"1"};oPK(F,v);e.j=!0;g.wa(k.wO,F)}}},a37=function(e){var k=new g.C({L:"div"});
g.RF(k.element,!1);var v=new KOS(e.player,k.element,H9(e));g.w(v,k);k.Kd(e.V.element);v.Vp();return v},GOL=function(e,k,v,F,K){if(!e.player.G().i4){var G=[];
k.navigationEndpoint&&g.y(k.navigationEndpoint,g.ps)&&g.y(k.navigationEndpoint,g.ps).browseId&&G.push(new gPn("openUrl","click",new zj4(`/channel/${g.y(k.navigationEndpoint,g.ps).browseId}`,"new",!0,!0)));var t=k.watermark.thumbnails[0];F={channel_name:k.channelName,end_ms:k.endTimeMs,image_height:t.height,image_type:1,image_url:t.url,image_width:t.width,is_mobile:!1,session_data:{annotation_id:v,ei:K,feature:"iv",itct:k.trackingParams,src_vid:F},start_ms:k.startTimeMs};if(k.subscribeButton&&g.y(k.subscribeButton,
g.IL)){F.channel_id=g.y(k.subscribeButton,g.IL).channelId;k=g.y(k.subscribeButton,g.IL);t=K=null;k.subscribed?(k.subscriberCountWithUnsubscribeText&&(K=g.sl(k.subscriberCountWithUnsubscribeText)),k.subscriberCountText&&(t=g.sl(k.subscriberCountText))):(k.subscriberCountText&&(K=g.sl(k.subscriberCountText)),k.subscriberCountWithSubscribeText&&(t=g.sl(k.subscriberCountWithSubscribeText)));let V=g.y(k.signInEndpoint?.commandMetadata,g.OE)?.url||"";k={subscribeText:g.sl(k.unsubscribedButtonText),subscribeCount:K||
"",unsubscribeText:g.sl(k.subscribedButtonText),unsubscribeCount:t||"",enabled:k.enabled||!1,classic:!1,subscribed:k.subscribed||!1,feature:"iv",signInUrl:V};F.standalone_subscribe_button_data=k}G=new y2L(v,"branding","branding",G,F);F=l3V(e);e.player.O("web_player_overlay_positioned_layout")?(F.setAttribute("data-overlay-order","11"),e.player.nj(F,4,!0)):e.V.element.appendChild(F);G=new MdK(F,H9(e),G);G.Vp();g.w(G,G);e.K[v]=G}};
g.nR.prototype.ZO=g.KE(43,function(e,k){var v=g.Ea(this.X5());v&&v.ZO(e,k)});
var OA={},qC=null;g.QU(ZP,g.IM);g.Y=ZP.prototype;g.Y.getDuration=function(){return this.duration};
g.Y.play=function(e){if(e||this.W==0)this.progress=0,this.coords=this.V;else if(this.isPlaying())return!1;Y6(this);this.startTime=e=g.ih();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.A=this.startTime;this.progress||this.MA();this.gj("play");this.isPaused()&&this.gj("resume");this.W=1;var k=g.qM(this);k in OA||(OA[k]=this);POy();aZn(this,e);return!0};
g.Y.stop=function(e){Y6(this);this.W=0;e&&(this.progress=1);hQn(this,this.progress);this.onStop();this.iy()};
g.Y.pause=function(){this.isPlaying()&&(Y6(this),this.W=-1,this.gj("pause"))};
g.Y.Qp=function(){this.W==0||this.stop(!1);this.gj("destroy");ZP.xz.Qp.call(this)};
g.Y.destroy=function(){this.dispose()};
g.Y.B9=function(){this.gj("animate")};
g.Y.gj=function(e){this.dispatchEvent(new USp(e,this))};
g.QU(USp,g.lo);g.QU(w3,ZP);w3.prototype.Y=function(){};
w3.prototype.B9=function(){this.Y();w3.xz.B9.call(this)};
w3.prototype.iy=function(){this.Y();w3.xz.iy.call(this)};
w3.prototype.MA=function(){this.Y();w3.xz.MA.call(this)};
g.QU(iI,w3);iI.prototype.Y=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var kOg=class extends g.Qa{constructor(e){super();this.V=e||window;this.W=[]}listen(e,k,v,F){v=(0,g.YQ)(v,F||this.V);e=g.qs(e,k,v);this.W.push(e);return e}Go(e,k,v,F){v=(0,g.YQ)(v,F||this.V);e=ydL(e,k,v);this.W.push(e);return e}Z4(e){g.Y5(e);g.vS(this.W,e)}removeAll(){g.Y5(this.W);this.W.length=0}Qp(){this.removeAll();super.Qp()}};var zJL=class extends g.u1{constructor(e){super(e);this.A=this.endscreen=null;this.V={};this.K={};this.U=this.Y=null;this.D=[];this.W=null;this.YV=!0;this.X=0;e=e.G();this.C=g.tF(e)||e.Hw==="profilepage";this.events=new g.Lv(this);g.w(this,this.events);this.events.N(this.player,g.Ds("creatorendscreen"),this.onCueRangeEnter);this.events.N(this.player,g.yG("creatorendscreen"),this.onCueRangeExit);this.events.N(this.player,"resize",this.CV);this.events.N(window,"focus",this.j);this.load();var k=g.Sz("STYLE");
(g.o$("HEAD")[0]||document.body).appendChild(k);this.addOnDisposeCallback(()=>{g.dV(k)});
k.sheet&&(k.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),k.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))}load(){super.load();if(!cL(this)){var e=g.Z7Q(this.player.getVideoData());e?(e=r3(e,bT7(this)),sA(this,e,!1)):FjK(this)}}unload(){sA(this,null);this.A&&(this.A.abort(),this.A=null);super.unload()}Vi(e,k){return cL(this)?e==="loadCustomEndscreenRenderer"?(e=r3(k,"new"),sA(this,e),!0):null:null}getOptions(){return cL(this)?["loadCustomEndscreenRenderer"]:[]}CV(){if(this.endscreen&&this.endscreen.elements){var e=this.player.getVideoContentRect();if(e&&e.width!==0&&e.height!==0){var k=this.player.getPlayerSize();
if(k&&k.width!==0&&k.height!==0){var v=e.width/e.height;var F=0;var K=-1;for(var G=0;G<tIy.length;G++){var t=Math.abs(k.width-tIy[G]);if(K===-1||F>=t)K=G,F=t}F=VIK[K];this.Y&&g.Cj(this.Y.element,"outline-width",Math.max(k.width,k.height)+"px");for(k=0;k<this.endscreen.elements.length;++k){G=this.endscreen.elements[k].id;K=this.V[G];t=this.K[G];if(!K||!t)continue;let T=t.width*v/t.aspectRatio;var V=Math.round(t.width*e.width);G=Math.round(T*e.height);let H=e.left+Math.round(t.left*e.width),z=e.top+
Math.round(t.top*e.height);g.Sq(K.element,V,G);g.GC(K.element,H,z);g.BW(K.element,TdK);V>256||G>256?g.Qw(K.element,"ytp-ce-large-round"):V>96||G>96?g.Qw(K.element,"ytp-ce-medium-round"):g.Qw(K.element,"ytp-ce-small-round");g.BW(K.element,HJS);V=t.left+t.width/2;t=t.top+T/2;g.Qw(K.element,V<=.5&&t<=.5?"ytp-ce-top-left-quad":V>.5&&t<=.5?"ytp-ce-top-right-quad":V<=.5&&t>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.BW(K.element,VIK);g.Qw(K.element,F);(K=g.ez(document,"div","ytp-ce-expanding-overlay-body",
K.element)[0])&&g.Cj(K,"height",`${G}px`)}}}}}onCueRangeEnter(e){if(this.endscreen)if(e.getId()==="ytp-ce-in-endscreen")m4(this,this.endscreen.impressionUrls),(e=g.MV())&&this.endscreen.visualElement&&g.Ol(e,this.endscreen.visualElement),this.W&&(g.Qw(this.W,"ytp-ce-element-show"),this.W.removeAttribute("aria-hidden"),this.player.U3()?g.Qw(this.W,"ytp-ce-hide-button-lower"):g.sI(this.W,"ytp-ce-hide-button-lower"));else{e=e.getId().substring(15);var k=this.V[e],v=this.K[e];g.Qw(k.element,"ytp-ce-element-show");
k.element.removeAttribute("aria-hidden");k=this.player.getRootNode();g.Qw(k,"ytp-ce-shown");m4(this,v.impressionUrls);(k=g.MV())&&g.Ol(k,v.visualElement);this.player.G().YV&&g.iM(this.player,"endscreenelementshown",e)}}onCueRangeExit(e){if(e.getId()==="ytp-ce-in-endscreen")this.W&&(g.sI(this.W,"ytp-ce-element-show"),this.W.setAttribute("aria-hidden","true"));else{e=e.getId().substring(15);var k=this.V[e];g.sI(k.element,"ytp-ce-element-show");k.element.setAttribute("aria-hidden","true");k=this.player.getRootNode();
g.sI(k,"ytp-ce-shown");this.player.G().YV&&g.iM(this.player,"endscreenelementhidden",e)}}j(e){e.target===window&&(new g.Y1(()=>{for(let k of Object.values(this.V))g.BW(k.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()}xv(e){for(let k of Object.values(this.V))e?k.element.setAttribute("hidden",""):k.element.removeAttribute("hidden")}Yr(e){this.W&&this.player.getRootNode().removeChild(this.W);
e&&(g.Qw(e,"ytp-ce-hide-button-container"),this.W=e,g.Au(this.player,this.W,4))}},tIy=[346,426,470,506,570,640,853,1280,1920],VIK="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),HJS=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],TdK=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var zj4=class{constructor(e,k,v,F){this.value=e;this.target=k;this.showLinkIcon=v;this.V=F}W(){return this.value?this.value:null}},H_J={nP:"current",zO:"new"};var gPn=class{constructor(e,k,v){this.type=e;this.trigger=k;this.url=v}},XEL={CLOSE:"close",EA:"openUrl",SUBSCRIBE:"subscribe"},S4x={yl:"click",CLOSE:"close",uW:"hidden",yzn:"rollOut",AzH:"rollOver",Iei:"shown"};var y2L=class{constructor(e,k,v,F,K){this.id=e;this.type=k;this.style=v;this.data=K;this.action=F||[]}a7(){var e=WjS(this,k=>k.type==="openUrl"&&k.url!=null);
return e?e.url:null}},Dz4={qC:"anchored",Ez:"branding",CHANNEL:"channel",b7:"cta",oL:"highlightText",uZ:"label",PLAYLIST:"playlist",POPUP:"popup",ZdX:"speech",SUBSCRIBE:"subscribe",knX:"title",VIDEO:"video",XXk:"website"},f37={Ez:"branding",xq:"card",u7:"drawer",NE:"highlight",UA:"marker",Io:"promotion",TEXT:"text",jHz:"widget"};var XB7=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
SvS=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];var g_p=class{constructor(e,k){this.context=e;this.W=k}};var hjy=class{constructor(e,k){this.merchant=e;this.price=k}};var RJx=class extends g.Qa{constructor(e,k){super();this.element=e;this.context=k;this.Cd=!1;this.De=new Map;this.N3=new Map;this.context.J.addEventListener(g.Ds("annotations_module"),v=>{(v=this.De.get(v))&&v.apply(this)});
this.context.J.addEventListener(g.yG("annotations_module"),v=>{(v=this.N3.get(v))&&v.apply(this)})}addCueRange(e,k,v,F,K){e=new g.tO(e,k,{id:v,
namespace:"annotations_module"});F&&this.De.set(e,F);K&&this.N3.set(e,K);this.context.J.j3([e],1)}Vp(){this.context.V.subscribe("resize",this.rX,this)}Jq(){return this.element}Fk(e,k,v,F,K,G){if(this.Cd)return!1;G&&(G.stopPropagation(),G.preventDefault());this.navigate(e,v,F,K);return!1}show(){}hide(){}destroy(){g.dV(this.Jq())}rX(){}navigate(e,k,v,F){var K=e.W();if(K){var G=EPx(K,e.target),t=()=>{e.V&&this.context.J.pauseVideo();var V=this.context.videoData.Vd||!1,T=g.Hv(K||"");V&&T&&(T.v||T.list)?
this.context.J.GJ(T.v,k,T.list,!1):g.Y7(K||"",G==="current"?"_top":void 0,k)};
G==="new"&&(t(),t=null);T8(this.context.logger,v,t,F);dzg(K)||(v=g.MV(),F=k.itct,v&&F&&g.Zt(v,g.mu(F)))}}Qp(){this.De.clear();this.N3.clear();super.Qp()}createElement(e){e=new g.C(e);g.w(this,e);return e.element}};var KOS=class extends RJx{constructor(e,k,v){super(k,v);this.J=e;this.eventId=null;this.HX=this.I1=this.hq=this.Y=this.isInitialized=!1;this.cards=[];this.WX=this.D=this.iu=this.U=this.mH=this.W=null;this.YV=[];this.j=this.X=this.oM=this.Jz=null;this.K=0;this.Hw=new g.Y1(()=>{},v.Ww.tk?4E3:3E3);
g.w(this,this.Hw);this.SQ=new g.Y1(()=>{});
g.w(this,this.SQ);this.Az=new g_p(v,(F,K,G,t,V,T)=>{AN(this,F,K,G,t,V,T)});
this.C=new g.C({L:"div",Z:"iv-drawer",B:{id:"iv-drawer"},S:[{L:"div",Z:"iv-drawer-header",B:{"aria-role":"heading"},S:[{L:"span",Z:"iv-drawer-header-text"},{L:"button",M3:["iv-drawer-close-button","ytp-button"],B:{"aria-label":"Hide cards",tabindex:"0"}}]},{L:"div",Z:"iv-drawer-content"}]});g.w(this,this.C);this.A=this.C.element;this.cw=new g.y9(this.C,330);g.w(this,this.cw);this.Uj=g.kD("iv-drawer-header-text",this.A);this.V=g.kD("iv-drawer-content",this.A);this.addCueRange(0,v.videoData.lengthSeconds*
1E3,"",()=>{this.hq&&e_(this,"YOUTUBE_DRAWER_AUTO_OPEN")},()=>{(this.hq=this.Y)&&v9(this)});
this.R1=new g.Lv(this);g.w(this,this.R1);this.J.addEventListener("videodatachange",this.QY.bind(this))}QY(){this.j&&ka(this,this.j)}isAvailable(){var e;if(e=!!this.cards.length)(e=this.J.getRootNode())?(e=g.gN(e),e=173<e.width&&173<e.height):e=!1;return e}rX(){var e=this.isAvailable();g.RF(this.Jq(),e);g.jA(this.context.J.getRootNode(),g.E$.IV_DRAWER_ENABLED,e);LM(this.J)}destroy(){this.J.ZO(!1);try{this.J.getRootNode().removeChild(this.A)}catch(e){}g.wE(this.YV);this.R1.V();this.mH&&this.mH.dispose();
this.U&&this.U.dispose();super.destroy()}bq(){this.context.W.listen(g.kD("iv-drawer-close-button",this.A),"click",this.nV,this);this.context.W.listen(this.V,"touchend",()=>{this.Hw.start()});
this.context.W.listen(this.V,"scroll",this.F5,this);this.context.V.subscribe("onHideControls",()=>{this.I1=!0});
this.context.V.subscribe("onShowControls",()=>{this.I1=!1});
this.context.V.subscribe("onVideoAreaChange",()=>{this.I1=g.rS(this.J.getRootNode(),"ytp-autohide")});
this.YV.push(g.Za("iv-button-shown",this.BX,this));this.YV.push(g.Za("iv-button-hidden",this.m2,this));O_U(this)}findLastIndex(e){if(this.cards.length===0)return 0;var k=g.CE(this.cards,v=>e.nm.startMs>v.nm.startMs||e.nm.startMs===v.nm.startMs&&e.nm.timestamp>=v.nm.timestamp?!0:!1);
return k===-1?0:k+1}nV(){if(this.Y){T8(this.context.logger,G8(this).KE.close);var e=g.MV();e&&this.X&&g.Zt(e,this.X);v9(this)}}F5(){g.jA(this.A,"iv-drawer-scrolled",this.V.scrollTop>0)}BX(){var e=g.MV(),k=G8(this);k=k?k.oM:this.oM;e&&k&&g.q_(e,[k])}m2(){var e=g.MV(),k=G8(this);k=k?k.oM:this.oM;e&&k&&g.YL(e,[k])}oH(){var e=G8(this);T8(this.context.logger,e.KE.us);var k=g.MV();if(k&&e)if(this.J.O("web_infocards_teaser_show_logging_fix")){let v=[];e.CE&&v.push(e.CE);e.oM&&v.push(e.oM);v.length>0&&g.q_(k,
v)}else g.q_(k,[e.CE,e.oM])}j4(){var e=g.MV(),k=G8(this);e&&k&&g.YL(e,[k.CE])}IH(e){var k=G8(this),v=g.MV();this.W?e?(e=this.context.logger,T8(e,k.KE.UV),e.J.sendVideoStatsEngageEvent(4,void 0),v&&k.CE&&g.Zt(v,k.CE)):(e=this.context.logger,T8(e,k.KE.UV),e.J.sendVideoStatsEngageEvent(4,void 0),v&&k.oM&&g.Zt(v,k.oM)):(e=this.context.logger,T8(e,k.KE.UV),e.J.sendVideoStatsEngageEvent(4,void 0),v&&this.oM&&g.Zt(v,this.oM))}};var WOu=class extends RJx{constructor(e,k,v){super(e,k);this.annotation=v;this.isActive=!1}Vp(){super.Vp();r2n(this)}show(){super.show();var e=g.MV(),k=this.annotation.data;e&&k&&(k=k.session_data)&&g.q_(e,[g.mu(k.itct)])}hide(){super.hide();var e=g.MV(),k=this.annotation.data;e&&k&&(k=k.session_data)&&g.YL(e,[g.mu(k.itct)])}};var MdK=class extends WOu{constructor(e,k,v){super(e,k,v);this.W=null;this.V=!1}show(){if(!this.isActive){super.show();if(!this.V){g.Qw(this.Jq(),"iv-branding");let e=this.annotation.data;this.W=this.createElement({L:"img",M3:["branding-img","iv-click-target"],B:{"aria-label":"Channel watermark",src:e.image_url,width:e.image_width,height:e.image_height}});g.RF(this.W,!1);let k=this.createElement({L:"button",M3:["branding-img-container","ytp-button"]});k.appendChild(this.W);this.Jq().appendChild(k);
let v=this.annotation.a7();v&&AN(this,k,v,this.annotation.id,e.session_data);this.V=!0}g.RF(this.Jq(),!0);this.isActive=!0;if(this.W){try{QE7(this,this.W)}catch{}g.Qw(this.context.J.getRootNode(),"ytp-branding-shown");this.context.J.getRootNode().style.setProperty("--branding-image-width",`${this.W.getAttribute("width")}px`)}}}hide(){this.isActive&&(super.hide(),g.RF(this.Jq(),!1),this.isActive=!1,g.sI(this.context.J.getRootNode(),"ytp-branding-shown"))}destroy(){g.sI(this.context.J.getRootNode(),
"ytp-branding-shown");super.destroy()}};var v_4=class{constructor(e,k,v,F,K,G,t){this.W=e;this.Y=k;this.Ww=v;this.videoData=F;this.logger=K;this.J=G;this.V=t}};var PSV=class extends WOu{constructor(e,k,v){super(e,k,v);this.D=this.isCollapsed=this.C=!1;this.K=5E3;this.V=this.Y=this.W=this.A=null;this.X=this.createElement({L:"div",M3:["iv-promo-contents"]});this.U=new g.Y1(()=>{this.W.setAttribute("aria-hidden","true");g.RF(this.Y,!1);g.RF(this.V,!0)},700,this);
g.w(this,this.U)}show(){this.isActive||(super.show(),this.C||(BfV(this),this.C=!0),g.RF(this.Jq(),!0),g.lp(function(){g.sI(this.Jq(),"iv-promo-inactive")},100,this),this.Jq().removeAttribute("aria-hidden"),this.isActive=!0,Vl(this),c2J(this),sES(this,this.K))}hide(){this.isActive&&(g.Qw(this.Jq(),"iv-promo-inactive"),this.isActive=!1,this.Jq().setAttribute("aria-hidden","true"))}Fk(e,k,v,F,K,G){return this.isCollapsed?!1:super.Fk(e,k,v,F,K,G)}Hw(e){this.D=!0;
tw(this,500,e)}Az(){this.D=!1;jEy(this)}YV(e){e.stopPropagation();this.hide()}j(e){e.stopPropagation();Vl(this);this.isCollapsed=!0;g.Qw(this.Jq(),"iv-promo-collapsed-no-delay");this.U.start()}destroy(){this.U.dispose();super.destroy()}};var n_K=class{constructor(e){this.J=e}};g.Sp("annotations_module",class extends g.u1{constructor(e){super(e);this.YV=this.j=!1;this.loadNumber=0;this.K={};this.logger=new n_K(this.player);this.U=new g.Lv(this);this.X=this.A=null;this.events=new g.Lv(this);this.VC=this.D=this.W=null;this.Vp=[];g.w(this,this.U);this.U.N(this.player,"onVideoAreaChange",()=>{this.publish("onVideoAreaChange")});
this.U.N(this.player,"onHideControls",()=>{this.publish("onHideControls")});
this.U.N(this.player,"onShowControls",()=>{this.publish("onShowControls")});
this.U.N(this.player,"resize",v=>{this.publish("resize",v)});
this.U.N(this.player,"presentingplayerstatechange",v=>{this.publish("presentingplayerstatechange",v)});
this.subscribe("presentingplayerstatechange",this.Hw,this);this.subscribe("resize",this.C,this);this.player.G().I1.subscribe("vast_info_card_add",this.Az,this);g.w(this,this.events);this.rX=this.createElement({L:"div",Z:"video-custom-annotations"});this.V=new g.C({L:"div",M3:["ytp-player-content","ytp-iv-player-content"]});g.w(this,this.V);g.Au(this.player,this.V.element,4);this.V.hide();this.Y=new g.C({L:"div",M3:["ytp-iv-video-content"]});g.w(this,this.Y);e=this.createElement({L:"div",Z:"video-annotations"});
e.appendChild(this.rX);this.Y.element.appendChild(e);this.h_()?this.load():this.player.O("web_fix_annotations")&&(this.A=()=>{this.loaded||this.bu()||!this.h_()||(uRU(this),this.load())},this.player.addEventListener("videodatachange",this.A));
var k=this.createElement({L:"style"});(g.o$("HEAD")[0]||document.body).appendChild(k);this.addOnDisposeCallback(()=>{g.dV(k)});
if(e=k.sheet){for(let v of XB7)e.insertRule(v,0);for(let v of SvS)e.insertRule(v,0)}}Vi(e,k){if(!I3U(this.player.G().playerStyle))return null;switch(e){case "loadCustomAnnotationsXml":return(e=g.od(k))&&z8(this,e),!0;case "removeCustomAnnotationById":return k&&this.W&&(op(this.W,k),LM(this.player)),!0}return null}getOptions(){return I3U(this.player.G().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]}h_(){var e=this.player.getVideoData(),k=e.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer;
return e.Vd||this.player.isMutedByEmbedsMutedAutoplay()?!1:this.player.O("web_fix_annotations")?Uzn(this)?k?.isWatermarkEnforced===!0?!0:k?.isAnnotationsEnabled??!1:!1:Uzn(this)}C(){if(this.Y){var e=this.player.qg().getVideoContentRect(!0);g.Sq(this.Y.element,e.width,e.height);g.GC(this.Y.element,e.left,e.top)}if(this.W){var k=this.player.A0();e=this.W;k=k.width;g.jA(e.A,"iv-drawer-small",k<=426);g.jA(e.A,"iv-drawer-big",k>=1280)}}Hw(e){A2U(this,e.state);e.state.W(2)&&(this.U3()&&this.Eo()&&this.player.getPresentingPlayerType()!==
2&&this.sP(!1),this.ZO(!1))}load(){super.load();A2U(this,this.player.getPlayerStateObject());this.loadNumber++;var e=this.player.getVideoData();eJp(this,e);g.Au(this.player,this.Y.element,4);this.C();var k=g.X5(e),v=e.jv();if(this.player.O("web_fix_annotations")){if(k&&(k.featuredChannel&&GOL(this,k.featuredChannel,k.annotationId||"branding",e.videoId||null,e.eventId||null),k=this.player.getVideoData().getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer,k?.isWatermarkEnforced&&!k?.isAnnotationsEnabled))return;
v&&XL(this,v)}else v&&XL(this,v),k&&k.featuredChannel&&GOL(this,k.featuredChannel,k.annotationId||"branding",e.videoId||null,e.eventId||null);this.VC=g.kD("ytp-cards-button",this.player.getRootNode());e.be()&&b_x(this,e)}onVideoDataChange(){}unload(){this.player.Ku("annotations_module");for(let e of Object.keys(this.K))this.K[e].destroy();this.D=null;this.W&&(this.W.destroy(),this.W=null,LM(this.player));this.j=!1;this.X&&(this.X.abort(),this.X=null);this.YV=!1;this.K={};this.V.hide();super.unload();
this.Y.detach();uRU(this)}Az(e){e===this.player.getVideoData().videoId&&(this.loaded?FOy(this):this.load())}U3(){return this.W?.isAvailable()||this.YV}Eo(){return!!this.W&&this.W.Y}sP(e,k=!1,v){this.U3();this.W&&(e?v?e_(this.W,v,k):e_(this.W,"YOUTUBE_DRAWER_AUTO_OPEN",k):v9(this.W))}ZO(e,k){this.player.publish(e?"cardsteasershow":"cardsteaserhide",k)}Qp(){this.player.G().I1.unsubscribe("vast_info_card_add",this.Az,this);g.sI(this.player.getRootNode(),g.E$.IV_DRAWER_OPEN);var e=this.Vp,k=g.dS;for(let v=
0,F=e.length;v<F;v++)k.YW(e[v]);this.Vp.length=0;super.Qp()}createElement(e){e=new g.C(e);g.w(this,e);return e.element}});g.Sp("creatorendscreen",zJL);})(_yt_player);
