(function(g){var window=this;'use strict';var E_J=async function(e,k,v){e.V=g.wa(k,v)},S_=function(e){e.isActive()||e.start()},J5L=function(e,k){var v=new g.lB;
v.languageCode=e.languageCode;v.languageName=e.languageName;v.name=e.name;v.displayName=e.displayName;v.kind=e.kind;v.isDefault=!1;v.W=e.W;v.isTranslateable=e.isTranslateable;v.vssId=e.vssId;v.url=e.url;v.translationLanguage=k;e.xtags&&(v.xtags=e.xtags);e.captionId&&(v.captionId=e.captionId);return v},gK=function(e,k){return k?e.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},pBn=function(e){return g.JF(e)||e.O("web_enable_caption_language_preference_stickiness")},LOJ=async function(e,k){e=
e+"|"+k;
k=await g.jk();if(!k)throw g.Sk("gct");return(await g.Hj(k)).get("captions",e)},$bS=function(e,k,v){LOJ(e,k).then(F=>{F&&v(F.trackData,new g.lB(F.metadata))})},R5=function(e){if(!OJV.test(e))throw Error("'"+e+"' is not a valid hex color");
e.length==4&&(e=e.replace(qvx,"#$1$1$2$2$3$3"));e=e.toLowerCase();e=parseInt(e.slice(1),16);return[e>>16,e>>8&255,e&255]},Yvy=function(){var e={},k="suggest_correction"in g.NA?g.NA.suggest_correction:"Edit caption";
k=k||"";for(let v in e){let F=()=>String(e[v]);
k=k.replace(new RegExp("\\$\\{"+v+"\\}","gi"),F);k=k.replace(new RegExp("\\$"+v,"gi"),F)}return k},W9=function(){return g.QO("yt-player-caption-display-settings")},ZJg=function(e,k){var v=g.dU(e.segments,k);
v>=0||v<0&&(-v-1)%2===1||(v=-v-1,v>0&&k-e.segments[v-1]===1&&v<e.segments.length&&e.segments[v]-k===1?(g.kV(e.segments,v),g.kV(e.segments,v-1)):v>0&&k-e.segments[v-1]===1?e.segments[v-1]=k:v<e.segments.length&&e.segments[v]-k===1?e.segments[v]=k:(g.Xp(e.segments,v,0,k),g.Xp(e.segments,v+1,0,k)))},wBn=function(e){return e.W&&e.W.U?e.W.U+e.player.Ng()<e.player.getCurrentTime():!1},iJx=function(e,k){if(e.policy.rw&&e.player.V0()){var v=g.PU(k,e.policy,{});
v.set("pot",e.player.V0());v=v.a7()}else v=g.PU(k,e.policy,{}).a7();var F={format:"RAW",withCredentials:!0};if(e.policy.rX){F.method="POST";let t=k.A;t&&Object.keys(t).length>0?F.postBody=g.Oc(t,g.fc):F.postBody=(0,g.Dm)([120,0])}e.U&&(F.responseType="arraybuffer");var K=++e.Vp,G=(0,g.M)();e.V=g.ra(v,F,3,100,-1,t=>{t.errorCode==="net.timeout"&&e.player.yp("capnt",{rn:K++})}).then(t=>{if(e.policy.MK&&K%100===1){var V=(0,g.M)();
e.player.yp("caprsp",{rn:K,ms:V-G,kb:(t.xhr.responseText.length/1024).toFixed()})}a:{t=t.xhr;e.bu();if(e.Y){var T=!(e.U?t.response:t.responseText)||t.status>=400;if(V=g.x2n(t)){t=g.PU(e.Y,e.policy,{});e.Y.UW(t,V);iJx(e,e.Y);break a}T?e.player.yp("capfail",{status:t.status}):(g.D8("fcb_r",(0,g.M)(),e.player.getVideoData()?.C||""),V=e.Y.VF[0],T=V.Ze,e.D!=null&&e.K!==T&&(e.U?e.D(t.response,(V.segmentStartTime+e.player.Ng())*1E3):e.D(t.responseText,(V.segmentStartTime+e.player.Ng())*1E3),e.K=T))}e.Y=
null;e.V=null}}).WR(t=>{e.Y=null;
e.V=null;e.player.yp("capfail",{rn:K,status:t.xhr?.status})});
e.Y=k;ZJg(e.A,e.Y.VF[0].Ze)},NdL=function(e,k){return k!=null&&k in e.V.W?e.V.W[k]:null},xbK=function(e,k,v){var F=[];
for(let K in e.V.W){if(!e.V.W.hasOwnProperty(K))continue;let G=e.V.W[K];if(g.Wd(G,v||null)){let t=G.info.captionTrack;t&&t.languageCode===k&&F.push(G)}}return F.length?F[0]:null},r5n=function(e,k){var v=[];
for(let K in e.V.W){if(!e.V.W.hasOwnProperty(K))continue;var F=e.V.W[K];if(g.Wd(F,k||null)){let G=F.info.id,t=G,V=`.${G}`,T="",H="";if(F=F.info.captionTrack)G=F.languageCode,t=F.displayName,V=F.vssId,T=F.kind,H=F.id;v.push(new g.lB({id:K,languageCode:G,languageName:t,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:V,kind:T,captionId:H}))}}return v},QCg=function(e,k,v,F){var K=k/360*16;
k>=e&&(e=640,F>v*1.3&&(e=480),K=v/e*16);return K},c5S=function(e){var k=1+.25*(e.fontSizeIncrement||0);
if(e.offset===0||e.offset===2)k*=.8;return k},sCp=function(e,k){var v="vertical-rl";
e.W.LQ===1&&(v="vertical-lr");g.fg&&(v=v==="vertical-lr"?"tb-lr":"tb-rl");g.Cj(k,"-o-writing-mode",v);g.Cj(k,"-webkit-writing-mode",v);g.Cj(k,"writing-mode",v);g.Cj(k,"text-orientation","upright");g.Qw(k,"ytp-vertical-caption");e.V.params.u3===3&&(g.Cj(k,"text-orientation",""),g.Cj(k,"transform","rotate(180deg)"))},Bdy=function(e,k){var v={},F=k.background?k.background:e.W.EF.background;
if(k.backgroundOpacity!=null||k.background){var K=k.backgroundOpacity!=null?k.backgroundOpacity:e.W.EF.backgroundOpacity;F=R5(F);v.background="rgba("+F[0]+","+F[1]+","+F[2]+","+K+")";e.mH&&(v["box-decoration-break"]="clone",v["border-radius"]=`${e.De*.375}px`)}if(k.fontSizeIncrement!=null||k.offset!=null)v["font-size"]=`${e.N3*c5S(k)}px`;F=1;K=k.color||e.W.EF.color;if(k.color||k.textOpacity!=null)K=R5(K),F=k.textOpacity==null?e.W.EF.textOpacity:k.textOpacity,K="rgba("+K[0]+","+K[1]+","+K[2]+","+F+
")",v.color=K,v.fill=K;var G=k.charEdgeStyle;G===0&&(G=void 0);if(G){K=`rgba(34, 34, 34, ${F})`;let T=`rgba(204, 204, 204, ${F})`;k.cN&&(T=K=k.cN);let H=e.N3/16/2,z=Math.max(H,1);var t=Math.max(2*H,1),V=Math.max(3*H,1);let X=Math.max(5*H,1);F=[];switch(G){case 4:for(;V<=X;V+=H)F.push(`${t}px ${t}px ${V}px ${K}`);break;case 1:t=window.devicePixelRatio>=2?.5:1;for(G=z;G<=V;G+=t)F.push(`${G}px ${G}px ${K}`);break;case 2:F.push(`${z}px ${z}px ${T}`);F.push(`-${z}px -${z}px ${K}`);break;case 3:for(V=0;V<
5;V++)F.push(`0 0 ${t}px ${K}`)}v["text-shadow"]=F.join(", ")}K="";switch(k.fontFamily){case 1:K='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:K='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:K='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:K='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:K='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:K=g.Us()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:K='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}K&&(v["font-family"]=K);K=k.offset;K==null&&(K=e.W.EF.offset);switch(K){case 0:v["vertical-align"]="sub";break;case 2:v["vertical-align"]="super"}k.fontFamily===7&&(v["font-variant"]="small-caps");k.bold&&(v["font-weight"]="bold");k.italic&&(v["font-style"]="italic");k.underline&&
(v["text-decoration"]="underline");k.ZD&&(v.visibility="hidden");k.fb===1&&e.A&&(v["text-combine-upright"]="all",v["text-orientation"]="mixed",K=g.Yi||g.Hy,e.V.params.u3===3?v.transform=K?"rotate(90deg)":"rotate(180deg)":K&&(v.transform="rotate(-90deg)"));if(k.textEmphasis===1||k.textEmphasis===2||k.textEmphasis===3||k.textEmphasis===4||k.textEmphasis===5)if(g.Yi)v["font-weight"]="bold";else switch(v["text-emphasis-style"]="filled circle",v["text-emphasis-color"]="currentcolor",v["webkit-text-emphasis"]=
"filled circle",k.textEmphasis){case 4:case 3:v["text-emphasis-position"]="under left";v["webkit-text-emphasis-position"]="under left";break;case 5:case 2:v["text-emphasis-position"]="over right",v["webkit-text-emphasis-position"]="over right"}return v},jCp=function(e,k){if(e.cw&&k.length===0)return 0;
e=1;for(let v=0;v<k.length;v++){let F=k[v];typeof F.text==="string"&&(e+=F.text.split("\n").length-1,F.append||v===0||e++)}return e},nQ=function(e){e=e.split("px");
return e.length>0?(e=Number(e[0]))?e:0:0},lXU=function(e,k,v){e.Jz=e.Jz||!!v;
var F={};Object.assign(F,e.W.EF);Object.assign(F,v||k.W);Object.assign(F,e.i4.EF);(v=!e.U)&&IX4(e);var K=e.iu&&e.I1&&g.bn(F,e.I1)?e.iu:uaJ(e,F),G=typeof k.text==="string",t=G?k.text.split("\n"):[k.text];for(let T=0;T<t.length;T++){var V=T>0||!k.append;let H=t[T];V&&!v?(IX4(e),K=uaJ(e,F)):V&&v&&(v=!1);H&&(K.appendChild(G?g.gV(H):H),G||H.tagName!=="RUBY"||H.childElementCount!==4||g.Yi||!g.kB(H.children[2],"text-emphasis")||(V=e.A?"padding-right":"padding-top",g.kB(H.children[2],"text-emphasis-position")&&
(V=e.A?"padding-left":"padding-bottom"),g.VI?g.Cj(K,V,"1em"):g.Cj(K,V,"0.5em")))}e.I1=F;e.iu=K;e.X.push(k)},IX4=function(e){if(e.U){var k=e.U;
if(e.mH){var v=e.W.textAlign;v===0?(k=k.firstElementChild)&&g.Cj(k,{"border-bottom-left-radius":"0"}):v===1&&(k=k.lastElementChild)&&g.Cj(k,{"border-bottom-right-radius":"0"})}}e.U=g.Sz("SPAN");g.Cj(e.U,{display:"block"});g.Qw(e.U,"caption-visual-line");e.Y.appendChild(e.U)},uaJ=function(e,k){var v=g.Sz("SPAN");
g.Cj(v,{display:"inline-block","white-space":"pre-wrap"});g.Cj(v,Bdy(e,k));v.classList.add("ytp-caption-segment");e.U.appendChild(v);e.mH&&e.Y.children.length>1&&(e=e.W.textAlign,e===0?v.previousElementSibling||g.Cj(v,{"border-top-left-radius":"0"}):e===1&&g.Cj(v,{"border-top-right-radius":"0"}));v.previousElementSibling&&(g.Cj(v.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Cj(v,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return v},
fXV=function(e,k,v){if(e===255&&k===255||!e&&!k)return{dN:e,
PZ:k,result:0};e=mbu[e];k=mbu[k];if(e&128){var F;if(F=!(k&128))F=k,F=v.sF()&&v.PZ===F;if(F)return{dN:e,PZ:k,result:1}}else if(k&128&&1<=e&&e<=31)return{dN:e,PZ:k,result:2};return{dN:e,PZ:k,result:3}},y5y=function(e,k,v,F){k===255&&v===255||!k&&!v?(++e.Y===45&&e.reset(),e.A.V.clear(),e.U.V.clear()):(e.Y=0,DbK(e.A,k,v,F))},MIn=function(e,k){e.W.sort((v,F)=>{var K=v.time-F.time;
return K===0?v.order-F.order:K});
for(let v of e.W)e.time=v.time,v.type===0?y5y(e,v.cV,v.eK,k):v.type===1&&e.V&496&&DbK(e.U,v.cV,v.eK,k);e.W.length=0},A5n=function(e,k){switch(e){case 0:return PFp[(k&127)-32];
case 1:return aXx[k&15];case 2:return hJy[k&31];case 3:return UbL[k&31]}return 0},dK=function(e,k){if(e.style.type===3){var v=0,F=0,K=e.U.time+0,G="",t="",V=K;
for(var T=1;T<=15;++T){var H=!1;for(var z=F?F:1;z<=32;++z){var X=e.Y[T][z];if(X.W!==0){v===0&&(v=T,F=z);H=String.fromCharCode(X.W);var S=X.timestamp;S<K&&(K=S);X.timestamp=V;t&&(G+=t,t="");G+=H;H=!0}if((X.W===0||z===32)&&H){t="\n";break}else if(F&&!H)break}if(v&&!H)break}G&&k.A(v,F,K,V,G)}else for(F=v=0,G=K=e.U.time+0,t=1;t<=15;++t)for(V="",T=1;T<=32;++T)if(z=e.Y[t][T],X=z.W,X!==0&&(v===0&&(v=t,F=T),H=String.fromCharCode(X),S=z.timestamp,S<=K&&(K=S),V+=H,z.reset()),T===32||X===0)V&&k.A(v,F,K,G,V),
K=G,V="",F=v=0},EU=function(e){return e.Y[e.row][e.V]},Jw=function(e,k,v){k>=2&&e.V>1&&(--e.V,EU(e).W=0);
var F=EU(e);F.timestamp=e.U.time+0;F.W=A5n(k,v);e.V<32&&e.V++},CFS=function(e,k,v,F){for(let t=0;t<F;t++)for(let V=0;V<=32;V++){var K=e.Y[k+t][V],G=e.Y[v+t][V];
K.W=G.W;K.timestamp=G.timestamp}},pQ=function(e,k,v){for(let F=0;F<v;F++)for(let K=0;K<=32;K++)e.Y[k+F][K].reset()},LQ=function(e){e.row=e.W>0?e.W:1;
e.V=1;pQ(e,0,15)},o_p=function(e){e.style.set(1);
e.W=e.A;e.W.W=0;e.W.style=e.style;e.Y.mode=1<<e.W.A},$a=function(e,k,v){var F=e.V,K=!1;
switch(e.style.get()){case 4:case 1:case 2:e.style.get()===4&&F.W>0||(dK(F,v),LQ(e.V),LQ(e.A),F.row=15,F.W=k,K=!0)}e.style.set(3);e.W=F;e.W.style=e.style;e.Y.mode=1<<F.A;K?F.V=1:F.W!==k&&(F.W>k?(dK(F,v),pQ(F,F.row-F.W,k)):F.row<k&&(k=F.W),F.W=k)},bJK=function(e){e.style.set(4);
e.W=e.text;e.W.style=e.style;e.Y.mode=1<<e.W.A},DbK=function(e,k,v,F){e.V.update();
k=fXV(k,v,e.V);switch(k.result){case 0:return;case 1:case 2:return}var K=k.dN;k=k.PZ;if(32<=K||!K)e.W.mode&e.W.V&&(v=K,v&128&&(v=127),k&128&&(k=127),e=e.A.W,v&96&&Jw(e,0,v),k&96&&Jw(e,0,k),v!==0&&k!==0&&e.style.type===3&&dK(e,F));else if(K&16)a:if(!e.V.matches(K,k)&&(v=e.V,v.dN=K,v.PZ=k,v.state=2,v=K&8?e.K:e.Y,e.A=v,e.W.mode=1<<(e.U<<2)+(v.U<<1)+(v.style.type===4?1:0),(e.W.mode|1<<(e.U<<2)+(v.U<<1)+(v.style.type!==4?1:0))&e.W.V))if(k&64){F=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(K&7)<<1|k>>5&1];
e=k&16?((k&14)>>1)*4:0;k=v.W;switch(v.style.get()){case 4:F=k.row;break;case 3:if(F!==k.row){if(F<k.W&&(F=k.W,F===k.row))break;var G=1+k.row-k.W;let t=1+F-k.W;CFS(k,t,G,k.W);v=G;K=k.W;t<G?(G=t+K-G,G>0&&(v+=G,K-=G)):(G=G+K-t,G>0&&(K-=G));pQ(k,v,K)}}k.row=F;k.V=e+1}else switch(K&7){case 1:switch(k&112){case 32:Jw(v.W,0,32);break a;case 48:k===57?(F=v.W,EU(F).W=0,F.V<32&&F.V++):Jw(v.W,1,k&15)}break;case 2:k&32&&Jw(v.W,2,k&31);break;case 3:k&32&&Jw(v.W,3,k&31);break;case 4:case 5:if(32<=k&&k<=47)switch(k){case 32:o_p(v);
break;case 33:F=v.W;F.V>1&&(--F.V,EU(F).W=0);break;case 36:F=v.W;e=EU(F);for(k=0;k<=15;k++)for(v=0;v<=32;v++)if(F.Y[k][v]===e){for(;v<=32;v++)F.Y[k][v].reset();break}break;case 37:$a(v,2,F);break;case 38:$a(v,3,F);break;case 39:$a(v,4,F);break;case 40:Jw(v.W,0,32);break;case 41:F=v;F.style.set(2);F.W=F.V;F.W.W=0;F.W.style=F.style;F.Y.mode=1<<F.W.A;break;case 42:F=v;e=F.text;e.W=15;e.style.set(4);LQ(e);bJK(F);break;case 43:bJK(v);break;case 44:e=v;k=e.V;switch(e.style.get()){case 1:case 2:case 3:dK(k,
F)}pQ(k,0,15);break;case 45:b:{k=v;e=k.W;switch(k.style.get()){default:case 2:case 1:break b;case 4:if(e.row<15){++e.row;e.V=1;break b}break;case 3:}e.W<2&&(e.W=2,e.row<e.W&&(e.row=e.W));k=e.row-e.W+1;dK(e,F);CFS(e,k,k+1,e.W-1);pQ(e,e.row,1)}break;case 46:pQ(v.A,0,15);break;case 47:e=v,dK(e.V,F),e.A.updateTime(e.Y.time+0),F=e.A,e.A=e.V,e.V=F,o_p(e)}break;case 7:switch(k){case 33:case 34:case 35:F=v.W,(F.V+=k&3)>32&&(F.V=32)}}},kpg=function(e,k,v,F,K,G,t){var V=G[0],T=t[V.getAttribute("p")];
if(T.qJ===1){var H=G[1],z=G[2];G=G[3];V.getAttribute("t");H.getAttribute("t");z.getAttribute("t");G.getAttribute("t");V.getAttribute("p");H.getAttribute("p");G.getAttribute("p");t=t[z.getAttribute("p")];V=eg4(V.textContent,H.textContent,z.textContent,G.textContent,t);return new OU(e,k,K,v,V,F,T)}switch(T.qJ){case 9:case 10:T.textEmphasis=1;break;case 11:T.textEmphasis=2;break;case 12:T.textEmphasis=3;break;case 13:T.textEmphasis=4;break;case 14:T.textEmphasis=5}return new OU(e,k,K,v,V.textContent||
"",F,T)},eg4=function(e,k,v,F,K){var G=g.Us(),t=G?g.Sz("DIV"):g.Sz("RUBY"),V=g.Sz("SPAN");
V.textContent=e;t.appendChild(V);e=G?g.Sz("DIV"):g.Sz("RP");e.textContent=k;t.appendChild(e);k=G?g.Sz("DIV"):g.Sz("RT");k.textContent=v;t.appendChild(k);v=K.qJ;if(v===10||v===11||v===12||v===13||v===14)if(g.Cj(k,"text-emphasis-style","filled circle"),g.Cj(k,"text-emphasis-color","currentcolor"),g.Cj(k,"webkit-text-emphasis","filled circle"),K.qJ===11||K.qJ===13)g.Cj(k,"webkit-text-emphasis-position","under left"),g.Cj(k,"text-emphasis-position","under left");v=!0;if(K.qJ===4||K.qJ===7||K.qJ===12||
K.qJ===14)g.Cj(t,"ruby-position","over"),g.Cj(t,"-webkit-ruby-position","before");else if(K.qJ===5||K.qJ===6||K.qJ===11||K.qJ===13)g.Cj(t,"ruby-position","under"),g.Cj(t,"-webkit-ruby-position","after"),v=!1;K=G?g.Sz("DIV"):g.Sz("RP");K.textContent=F;t.appendChild(K);G&&(F=v,g.Cj(t,{display:"inline-block",position:"relative"}),G=t.firstElementChild.nextElementSibling,g.Cj(G,"display","none"),G=G.nextElementSibling,g.Cj(G,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Cj(t.lastElementChild,"display","none"),F?(g.Cj(t,"padding-top","0.6em"),g.Cj(G,"top","0")):(g.Cj(t,"padding-bottom","0.6em"),g.Cj(G,"bottom","0")));return t},v9V=function(e){var k="_"+q9++;
return new Ya(0,0x8000000000000,0,k,e)},ZR=function(e,k){e=e.getAttribute(k);
if(e!=null)return Number(e)},wK=function(e,k){e=e.getAttribute(k);
if(e!=null)return e==="1"},ic=function(e,k){e=ZR(e,k);
return e!==void 0?e:null},xa=function(e,k){e=e.getAttribute(k);
if(e!=null)return N9.test(e),e},FiK=function(e,k){var v={},F=k.getAttribute("ws");
Object.assign(v,F?e.C[F]:e.A);e=ic(k,"mh");e!=null&&(v.GS=e);e=ic(k,"ju");e!=null&&(v.textAlign=e);e=ic(k,"pd");e!=null&&(v.u3=e);e=ic(k,"sd");e!=null&&(v.LQ=e);e=xa(k,"wfc");e!=null&&(v.windowColor=e);k=ZR(k,"wfo");k!==void 0&&(v.windowOpacity=k/255);return v},KiK=function(e,k){var v={},F=k.getAttribute("wp");
F&&Object.assign(v,e.D[F]);e=ic(k,"ap");e!=null&&(v.CG=e);e=ZR(k,"cc");e!=null&&(v.rO=e);e=ZR(k,"ah");e!=null&&(v.GG=e);e=ZR(k,"rc");e!=null&&(v.bS=e);k=ZR(k,"av");k!=null&&(v.vr=k);return v},GpL=function(e,k,v,F){var K={};
Object.assign(K,KiK(e,k));Object.assign(K,FiK(e,k));F?g.bn(K,e.A)?(F=e.U,K=e.A):F="_"+q9++:F=k.getAttribute("id")||"_"+q9++;e=ZR(k,"t")+v;k=ZR(k,"d")||0x8000000000000;if(K.u3===2||K.u3===3)v=K.bS,K.bS=K.rO,K.rO=v;return new Ya(e,k,0,F,K)},rK=function(e){e=g.sf(Math.round(e),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-e.length)+e},t4u=function(e,k,v,F,K){F===0&&(F=0x8000000000000);
var G={};k.wpWinPosId&&Object.assign(G,e.A.get(k.wpWinPosId));k.wsWinStyleId&&Object.assign(G,e.U.get(k.wsWinStyleId));e=k.rcRowCount;e!==void 0&&(G.bS=e);k=k.ccColCount;k!==void 0&&(G.rO=k);if(G.u3===2||G.u3===3)k=G.bS,G.bS=G.rO,G.rO=k;return new Ya(v,F,0,K,G)},Ql=function(e){var k=e.byteOffset;
e.byteOffset+=1;return e.W.getUint8(k)},c9=function(e){var k=e.byteOffset;
e.byteOffset+=4;return e.W.getUint32(k)},H0g=function(e){if(typeof e==="string")return!1;
e=new V4g(e,0);return TBn(e)},TBn=function(e){if(!(e.byteOffset<e.W.byteLength)||c9(e)!==1380139777)return!1;
e.version=Ql(e);if(e.version>1)return!1;Ql(e);Ql(e);Ql(e);return!0},zgV=function(e,k){if(!k)return"";
e.A&&e.V.params.LQ!==1&&(k*=-1);return`translate${e.A?"X":"Y"}(${k}px)`},X0y=function(e){e.Hw=Array.from(e.element.getElementsByClassName("caption-visual-line"));
for(var k=e.V.params.bS,v=0,F=0,K=e.Hw.length-1;v<k&&K>-1;){var G=e.Hw[K];F+=e.A?G.offsetWidth:G.offsetHeight;v++;K--}e.j=F;k=Math;v=k.max;isNaN(e.rX)&&((F=e.W.rO)?(K=g.Sz("SPAN"),g.Jv(K,"\u2013".repeat(F)),g.Cj(K,Bdy(e,e.W.EF)),e.Y.appendChild(K),e.rX=K.offsetWidth,e.Y.removeChild(K)):e.rX=0);F=e.Y;e.Vp=v.call(k,e.rX,e.F5,(e.A?F.offsetHeight:F.offsetWidth)+1)},SG4=function(e,k){X0y(e);
var v=e.Hw.reduce((F,K)=>(e.A?K.offsetWidth:K.offsetHeight)+F,0);
v=e.j-v;if(v!==e.R1){let F=v>0&&e.R1===0,K=v<e.R1;k||isNaN(v)||F||!K||(g.Qw(e.element,"ytp-rollup-mode"),e.N(e.element,"transitionend",e.SQ));g.Cj(e.Y,"transform",zgV(e,v));e.R1=v}X0y(e)},RgJ=function(e,k,v,F){var {formatId:K,
Ze:G,startTimeMs:t,durationMs:V}=e.qF(k),T={formatId:K,startTimeMs:t,durationMs:V,ro:G,D4:G},H=g9g(e.aH,T.startTimeMs),z=H>=0?e.aH[H]:null,X=z?z.startTimeMs+z.durationMs:0,S=T.startTimeMs+T.durationMs;!z||T.startTimeMs-X>e.A?e.aH.splice(H+1,0,T):(z.durationMs=Math.max(X,S)-z.startTimeMs,z.D4=Math.max(z.D4,T.D4));F(e.aH);F=g.b4(k);e=e.U;F=F.buffer.slice(F.byteOffset,F.byteLength+F.byteOffset);k=k.info.A;e.Vp?e.D==null?g.AK(e.logger,350058965,"Null loaded track meta data at captions data received"):
v.Zk(F,e.D,k*1E3):g.AK(e.logger,350058965,"Null Representation at captions data received")},d4p=function(e,k){e.V=(v,F)=>{if(e.J.G().experiments.Ei("html5_sabr_live_support_subfragmented_captions"))(e.W?e.W=e.W.U(v):(e.W=v,WiS(e.W)),e.W)?v.info.Lu&&(n97(e.W),RgJ(e,e.W,k,F),e.W=null):g.AK(e.logger,350058965,"Empty slice");
else if(v.info.Lu){var K=v;if(e.IS.length>0){for(K=e.IS.shift();e.IS.length>0;)K=K?.U(e.IS.shift());K=K?.U(v)}K?(WiS(K),n97(K),RgJ(e,K,k,F)):g.AK(e.logger,350058965,"Empty slice")}else e.IS.push(v)};
e.J.addEventListener("sabrCaptionsDataLoaded",e.V)},g9g=function(e,k){e=g.dU(e,{startTimeMs:k},(v,F)=>v.startTimeMs-F.startTimeMs);
return e>=0?e:-e-2},WiS=function(e){try{var k=g.vG(e)*1E3}catch(v){k=e.info.segmentStartTime*1E3}k<0&&(k=e.info.segmentStartTime*1E3);
e.info.segmentStartTime=k/1E3;e.info.A=k/1E3},n97=function(e){try{var k=g.$2y(e)*1E3}catch(v){k=e.info.Y*1E3}k<0&&(k=e.info.Y*1E3);
e.info.Y=k/1E3;e.info.K=k/1E3},E9L=function(e,k){if(!g.wRK(e)||e.W!=null&&g.RK(k,e.W)&&e.W.W.rawcc!=null)return!1;
k=!!e.W&&e.W.isManifestless&&Object.values(e.W.W).some(v=>g.Wd(v,"386"));
e=!!e.W&&!e.W.isManifestless&&g.C6Q(e.W);return k||e},Jbn=function(e,k,v){var F=[];
for(let K in e.V.W){if(!e.V.W.hasOwnProperty(K))continue;let G=e.V.W[K];if(g.Wd(G,v||null)){let t=G.info.captionTrack;t&&t.languageCode===k&&F.push(G)}}return F.length?F[0]:null},p0L=function(e,k){var v=[];
for(let K in e.V.W){if(!e.V.W.hasOwnProperty(K))continue;var F=e.V.W[K];if(g.Wd(F,k||null)){let G=F.info.id,t=G,V=`.${G}`,T="",H="";if(F=F.info.captionTrack)G=F.languageCode,t=F.displayName,V=F.vssId,T=F.kind,H=F.id;v.push(new g.lB({id:K,languageCode:G,languageName:t,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:V,kind:T,captionId:H}))}}return v},$4g=function(e){var k=LiJ.length;
if(e.byteLength<k)return!1;e=new Uint8Array(e,0,k);for(let v=0;v<k;v++)if(LiJ[v]!==e[v])return!1;return!0},sU=function(e){e=e.split(":");
var k=0;for(let v of e)k=k*60+Number(v);return k*1E3},O0g=function(e,k,v,F){F=Object.assign({GS:0},F);
return new Ya(e,k,v,"_"+q9++,F)},qGJ=function(e,k,v,F,K,G,t,V,T){switch(t.tagName){case "b":V.bold=!0;
break;case "i":V.italic=!0;break;case "u":V.underline=!0}for(let z=0;z<t.childNodes.length;z++){var H=t.childNodes[z];if(H.nodeType===3)H=new OU(k,v,F,K.id,H.nodeValue,G||z>0,g.mL(V)?void 0:V),T.push(H),K.W.push(H);else{let X={};Object.assign(X,V);qGJ(e,k,v,F,K,!0,H,X,T)}}},Z07=function(e,k,v){if(typeof k==="string"||H0g(k))return[{trackData:k,
V6:v}];if(typeof k==="string"&&k.substring(0,6)==="WEBVTT"||typeof k!=="string"&&$4g(k))return[{trackData:k,V6:v}];var F=new DataView(k);if(F.byteLength<=8||F.getUint32(4)!==1718909296)return[];var K=g.rUh(F);if(e.GN&&K){var G=g.$NU(K),t=g.OfE(K);K=K.segmentNumber;G&&K&&e.GN.Th(K,G,t)}e=g.K1(F,1835295092);if(!e||!e.length||!e[0].size)return[];G=[];for(t=0;t<e.length;t++)K=e[t],K=new Uint8Array(k,K.dataOffset,K.size-(K.dataOffset-K.offset)),K=g.tB(K),G.push({trackData:K,V6:v+t*1E3});YGV(F,G,v);return G=
G.filter(V=>!!V.trackData)},i0L=function(e,k,v){e.W||(e.W=new w0L);
e=e.W.Y(k,v);Math.random()<.01&&g.kL(Error("Deprecated subtitles format in web player: WebVTT"));return e},YGV=function(e,k,v){var F=g.b8(e,0,1836476516),K=9E4;
F&&(K=g.eU(F)||9E4);F=0;var G=g.K1(e,1836019558);for(let V=0;V<G.length;V++){var t=G[V];V<k.length&&(t=g.b8(e,t.dataOffset,1953653094))&&(t=g.b8(e,t.dataOffset,1952867444))&&(t=g.FE(t)/K*1E3,V===0&&(F=t),k[V].V6=t-F+v||v*V*1E3)}},NBp=function(e){var k={};
if(e=g.O$(e))k.lang=e,g.GwQ.test(e)&&(k.u3=1);return k},B9=function(e){return e.Y==="HLS"&&e.HX?!0:e.iu&&e.HX&&e.Y!=="LIVE"&&e.Y!=="SABR_LIVE"},x4K=function(e){return!e.A&&e.iu&&e.cw&&(e.Y==="LIVE"||e.Y==="SABR_LIVE")},j_=function(e,k,v=!1){var F=e.Ww.O("enable_player_captions_new_style_defaults")?rbg:Qqu,K=F.EF;
e.U={};Object.assign(e.U,F);e.U.EF={};Object.assign(e.U.EF,K);e.K={EF:{}};var G=k.backgroundOverride?e.K:e.U,t=k.background||K.background;N9.test(t);G.EF.background=t;G=k.colorOverride?e.K:e.U;t=k.color||K.color;N9.test(t);G.EF.color=t;G=k.windowColorOverride?e.K:e.U;t=k.windowColor||F.windowColor;N9.test(t);G.windowColor=t;G=k.backgroundOpacityOverride?e.K:e.U;t=k.backgroundOpacity;t==null&&(t=K.backgroundOpacity);G.EF.backgroundOpacity=t;G=k.fontSizeIncrementOverride?e.K:e.U;t=k.fontSizeIncrement;
t==null&&(t=K.fontSizeIncrement);G.EF.fontSizeIncrement=t;t=k.fontStyleOverride?e.K:e.U;G=k.fontStyle;G==null&&(G=K.bold&&K.italic?3:K.bold?1:K.italic?2:0);t=t.EF;switch(G){case 1:t.bold=!0;delete t.italic;break;case 2:delete t.bold;t.italic=!0;break;case 3:t.bold=!0;t.italic=!0;break;default:delete t.bold,delete t.italic}G=k.textOpacityOverride?e.K:e.U;t=k.textOpacity;t==null&&(t=K.textOpacity);G.EF.textOpacity=t;G=k.windowOpacityOverride?e.K:e.U;t=k.windowOpacity;t==null&&(t=F.windowOpacity);G.windowOpacity=
t;F=k.charEdgeStyleOverride?e.K:e.U;G=k.charEdgeStyle;G==null&&(G=K.charEdgeStyle);F.EF.charEdgeStyle=G;F=k.fontFamilyOverride?e.K:e.U;G=k.fontFamily;G==null&&(G=K.fontFamily);F.EF.fontFamily=G;e.loaded&&e.WX();v&&g.rO("yt-player-caption-display-settings",k,2592E3)},I5=function(e,k,v){k&&!e.YV?(k=v9V({u3:0,
lang:"en"}),e.YV=[k,new OU(k.start,k.end-k.start,0,k.id,v??"Captions look like this")],e.player.j3(e.YV)):!k&&e.YV&&(cbS(e,e.YV),e.YV=null)},BBy=function(e){if(e.Ww.O("enable_player_captions_persistence_state_machine")){var k=g.QO("yt-player-caption-persistence");
if(k==null){let v=g.ug().hz(65);if(v===!0)k=!1;else{let F=g.JF(e.Ww)?uc(e):sqJ(e);F!=null?k=!!F:v===!1&&(k=!0)}k!==void 0&&lc(e,k)}return k}},uc=function(e){if(!e.J.isInline())return g.QO("yt-player-sticky-caption")},sqJ=function(e){if(!e.storage)return null;
try{var k=e.storage.get("module-enabled")}catch(v){e.storage.remove("module-enabled")}return k},mZ=function(e){if(e.Ww.O("enable_player_captions_persistence_state_machine"))return BBy(e);
var k=void 0,v=g.ug().hz(65);if(g.JF(e.Ww)&&v!=null){if(uc(e)!=null)return!1;k=!v}return k},jqS=function(e){if(e.Ww.J_===1||e.videoData.Lz===1||g.Gy(e.videoData,"yt:cc")==="alwayson")return!0;
if(e.videoData.captionTracks.length)var k=e.getAudioTrack().V;if(e.Ww.O("enable_player_captions_persistence_state_machine")){var v=BBy(e);if(v!==void 0)return!!v}else if(e.Ww.J_===2&&(g.JF(e.Ww)?v=uc(e):v=sqJ(e),v!=null))return!!v;v=gK(e.player.getAudioTrack(),g.JF(e.Ww));var F=g.Gy(e.videoData,"yt:cc");if(mZ(e)===void 0){if(v==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return F?F==="on":!0;if(v==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return F==="on"}else return F==="on";return k==="ON"||g.Gy(e.videoData,
"yt:cc")==="on"},fQ=function(e,k=!1){if(e.V&&!k||!e.videoData.captionTracks.length)return!1;
e=e.getAudioTrack();return!!e.W||e.V==="FORCED_ON"},Icg=function(e,k){if(e.V){var v=e.J.F7().Jq().textTracks,F=null;
e.Y==="HLS"?F=e.V.getId():F=e.V.toString();for(let G=0;G<v.length;G++){var K=v[G];K.id===F&&(k?K.mode!=="showing"&&(K.mode="showing",K=e.V,e.Mk(K,!!K,DR(e)?"g":e.X?"m":"s")):K.mode==="showing"&&(K.mode="disabled"))}}},DR=function(e){var k=yl(e);
return!!k&&e.V===k},uYn=function(e,k){if(e.Y==="HLS")return!1;
g.Rw(e.videoData)&&(k=!0);k||(k=e.Y==="TTS"?!1:e.Y==="INNERTUBE"?!1:!0);return k||e.Ww.O("web_watch_disable_account_level_captions_settings")&&g.JF(e.Ww)?!0:!!g.ug().hz(66)},yl=function(e){return e.C&&e.C.W},M9=function(e,k){if(!e.W)return null;
if(e.C&&e.C.A)return e.C.A;k=uYn(e,k);k=g.aI(e.W.W,k);var v=null;if(pBn(e.Ww)){var F=e.J.isInline()?void 0:g.QO("yt-player-caption-sticky-language");var K=[F,e.videoData.captionsLanguagePreference,e.Ww.captionsLanguagePreference,g.Gy(e.videoData,"yt:cc_default_lang")];let V=!1;for(let T=0;T<K.length;T++){let H=K[T];if(H){V=!0;for(var G=0;G<k.length;G++)if(g.O$(k[G])===H)return k[G];for(G=0;G<k.length;G++)if(g.O$(k[G]).split("-")[0]===H.split("-")[0])return k[G]}}if(V&&e.W&&(K=e.W.C,K.length))for(var t of K)if(t.languageCode===
F){v=t;break}}else for(t=[e.videoData.captionsLanguagePreference,e.Ww.captionsLanguagePreference,g.Gy(e.videoData,"yt:cc_default_lang")],F=0;F<t.length;F++)for(K=0;K<k.length;K++)if(g.O$(k[K])===t[F])return k[K];t=null;e.C&&e.C.Y&&(t=e.C.Y);t||(t=k.find(V=>V.isDefault)||null);
t||(t=k[0]||yl(e));t&&v&&g.O$(t).split("-")[0]!==v.languageCode.split("-")[0]&&(t=J5L(t,v));return t},UU=function(e,k,v){e.loaded&&e.unload();
v!=null&&(e.X=v,e.X&&(e.Ww.O("enable_player_captions_persistence_state_machine")?lc(e,!!k):g.JF(e.Ww)?P9(e,!!k):a5(e,!!k)));k!==null||fQ(e,!0)||e.Mk(k,!!k,e.X?"m":"s");e.V=k;fQ(e)&&(e.V=yl(e));hw(e,e.V??void 0);e.load()},lc=function(e,k){e.Ww.O("enable_player_captions_persistence_state_machine")&&g.rO("yt-player-caption-persistence",k,3122064E3)},P9=function(e,k){e.J.isInline()||g.rO("yt-player-sticky-caption",k,2592E3)},a5=function(e,k){if(e.storage)try{e.storage.set("module-enabled",k)}catch(v){}},
hw=function(e,k){e.Ww.O("html5_modify_caption_vss_logging")&&(e.videoData.ee=k)},m4S=function(e,k){var v=e.Az[k.id];
v&&v.V!==k&&(v.dispose(),delete e.Az[k.id],v=null);v||(v=lcU(e,k))&&(e.Az[k.id]=v)},fcy=function(e,k){var v=k.windowId;
e.mH[v]||(e.mH[v]=[]);e.mH[v].push(k)},lcU=function(e,k){var v=D4g(e);
if(!v)return null;var F=e.V?g.O$(e.V):null;F&&g.GwQ.test(F)&&(k.params.u3=1);var K=e.SQ.getPlayerSize();F=K.height*e.Vp.height;K=K.width*e.Vp.width;e.Ww.playerStyle!=="google-live"||e.U.isDefault||Object.assign(k.params,e.U);switch(k.params.GS!=null?k.params.GS:k.W.length>1?1:0){case 1:return new yb7(k,e.U,e.K,v.width,v.height,K,F,e.Ww.experiments,e.De.bind(e),e.J);case 2:return new M4L(k,e.U,e.K,v.width,v.height,K,F,e.Ww.experiments,e.De.bind(e),e.J);default:return new Aw(k,e.U,e.K,v.width,v.height,
K,F,e.Ww.experiments,e.De.bind(e),e.J)}},D4g=function(e){var k=e.SQ.getVideoContentRect(!0).height,v=e.SQ.getVideoContentRect(!0).width;
if(!k||!v)return null;k*=e.Vp.height;v*=e.Vp.width;return{width:v,height:k}},cbS=function(e,k){e.player.Sa(k);
for(let v of k)g.vS(e.rX,v);S_(e.Jz)},P_g=function(e,k){if(!e.W)return{};
if(k){g.mL(k)||e.ol(k.vss_id,"m");if(e.A&&e.Y!=="HLS"||!g.$Q(k))return;if(g.mL(k)){UU(e,null,!0);return}let F;var v=g.aI(e.W.W,!0);for(let K=0;K<v.length;K++){let G=v[K];G.languageCode!==k.languageCode||F&&(G.languageName!==k.languageName||(G.captionId||"")!==(k.captionId||"")||g.L3(G)!==k.displayName)||(F=k.translationLanguage?J5L(G,k.translationLanguage):G)}e.zh(k.position);!F||F===e.V&&e.loaded||(k=g.n3(),v=g.O$(F),k.length&&v===k[k.length-1]||(k.push(v),g.rO("yt-player-caption-language-preferences",
k)),pBn(e.Ww)&&!e.J.isInline()&&g.rO("yt-player-caption-sticky-language",v,2592E3),UU(e,F,!0))}else return e.loaded&&e.V&&!DR(e)?g.$X(e.V):{};return""};
g.b1.prototype.Th=g.KE(68,function(e,k,v){this.V.set(e,{Fz:k,NP:v})});
g.et.prototype.Th=g.KE(67,function(e,k,v){this.Vp.Th(e,k,v)});
g.l1.prototype.j=g.KE(66,function(){return!1});
g.l1.prototype.A=g.KE(65,function(){});
g.mQ.prototype.A=g.KE(64,function(e,k,v){this.bu();k=this.K(e,k);var F=this.zn.G().O("html5_report_captions_ctmp_qoe"),K=(0,g.M)();this.Y();E_J(this,k,{format:"RAW",onSuccess:G=>{this.V=null;if(F){var t=(G.responseText.length/1024).toFixed();let V=(0,g.M)();this.videoData.yp("capresp",{ms:V-K,kb:t})}t=G.getResponseHeader&&G.getResponseHeader("Content-Length")?Number(G.getResponseHeader("Content-Length")):0;v.Zk(G.responseText,e,void 0,void 0,t)},
onError:F?G=>{this.videoData.yp("capfail",{status:G?.status??0})}:void 0,
withCredentials:!0})});
g.fR.prototype.A=g.KE(63,function(e,k,v){this.bu();k=this.K(e,k);this.Y();this.V=g.wa(k,{format:"RAW",onSuccess:F=>{this.V=null;var K=F.getResponseHeader&&F.getResponseHeader("Content-Length")?Number(F.getResponseHeader("Content-Length")):0;v.Zk(F.responseText,e,void 0,void 0,K)},
withCredentials:!0})});
g.wJ.prototype.X=g.KE(62,function(){this.mediaElement.X()});
g.O5.prototype.X=g.KE(61,function(){var e=g.ez(document,"track",void 0,this.W);for(let k=0;k<e.length;k++)g.dV(e[k])});
g.wJ.prototype.Jz=g.KE(60,function(){return this.mediaElement.Jz()});
g.O5.prototype.Jz=g.KE(59,function(){return!(!this.W.textTracks||!this.W.textTracks.addEventListener)});
g.wJ.prototype.rX=g.KE(58,function(){return this.mediaElement.rX()});
g.O5.prototype.rX=g.KE(57,function(){return!!this.W.textTracks});
g.wJ.prototype.YV=g.KE(56,function(e){this.mediaElement.YV(e)});
g.O5.prototype.YV=g.KE(55,function(e){for(let k=0;k<e.length;k++)this.W.appendChild(e[k])});
g.nR.prototype.ol=g.KE(42,function(e,k){this.app.xV().ol(e,k)});
g.M3.prototype.ol=g.KE(41,function(e,k){this.q3.ol(e,k)});
g.rz.prototype.ol=g.KE(40,function(e,k){e=[e,k];g.ES(this,g.Lh(this.provider),"cfi",e)});
g.cO.prototype.ol=g.KE(39,function(e,k){this.qoe&&this.qoe.ol(e,k)});
g.oD.prototype.ol=g.KE(38,function(e,k){this.pV.ol(e,k)});
g.UL.prototype.ol=g.KE(37,function(){});
g.nR.prototype.Mk=g.KE(36,function(e,k,v){this.app.xV().Mk(e,k,v)});
g.M3.prototype.Mk=g.KE(35,function(e,k,v){this.q3.Mk(e,k,v)});
g.rz.prototype.Mk=g.KE(34,function(e,k,v){if(this.iu!==e||this.Uj!==k)k=k==="rawcc"?"":k,v=[e,k,this.iu,v],g.ES(this,g.Lh(this.provider),"cfs",v),this.iu=e,this.Uj=k});
g.cO.prototype.Mk=g.KE(33,function(e,k,v){this.qoe&&this.qoe.Mk(e,k,v)});
g.oD.prototype.Mk=g.KE(32,function(e,k,v){this.pV.Mk(e,k,v)});
g.UL.prototype.Mk=g.KE(31,function(){});
g.Gi.prototype.QD=g.KE(10,function(e){return(e=this.Y(e))?e.W:0});
g.VC.prototype.QD=g.KE(9,function(){return 0});
g.lB.prototype.V=g.KE(8,function(){return this.vssId});
var qvx=/#(.)(.)(.)/,OJV=/^#(?:[0-9a-f]{3}){1,2}$/i,acx={en:"English"},hgL=class extends g.l1{constructor(e){super(e);this.V=new Set}U(e){var k=this.zn.F7();if(k&&k.Jq()){k=k.Jq().textTracks;for(let v of k)v.kind==="subtitles"&&!this.V.has(v.language)&&v.language&&(g.gp(this.W,new g.lB({languageCode:v.language,languageName:v.language,kind:v.kind,id:v.id,displayName:acx[v.label]||v.label,vss_id:`.${v.language}`})),this.V.add(v.language))}g.aI(this.W).length>0&&e.kT()}},U4n=class{constructor(){this.segments=
[]}contains(e){e=g.dU(this.segments,e);return e>=0||e<0&&(-e-1)%2===1}length(){return this.segments.length/2}},AbL=class extends g.Qa{constructor(e,k,v,F,K,G){super();this.policy=e;this.player=k;this.Pw=v;this.D=F;this.U=K;this.j=G;this.A=new U4n;this.K=-1;this.V=this.Y=this.W=null;this.Vp=0;this.X=new g.Y1(this.YV,1E3,this);this.events=new g.Lv(this);g.w(this,this.X);g.w(this,this.events);this.events.N(k,"SEEK_COMPLETE",this.C);this.C();this.YV()}Qp(){super.Qp();this.V&&this.V.cancel()}C(){this.seekTo(this.player.getCurrentTime())}seekTo(e){e-=
this.player.Ng();var k=this.W;this.W=g.lh(this.Pw.K(e).VF);k!==this.W&&this.j&&this.j()}reset(){this.A=new U4n;this.K=-1;this.V&&(this.V.cancel(),this.V=null)}YV(){this.bu();var e;if(e=this.W!=null)e=this.W,e=e.Pw.A(e);if(e&&!this.V&&!(this.W&&this.W.segmentStartTime-this.player.getCurrentTime()>30)){e=this.W;e=e.Pw.Jz(e);let K=e.VF[0];if(this.player.getVideoData()?.enableServerStitchedDai){var k=this.player.pf();if(k){var v=K.Pw.info.id;let G=K.Ze;var F=e.VF[0].A;if(this.policy.rX){if(k=g.CB0(k,
F,G,v,3))e.A=k}else if(v=k.Eu(F,G,v,3))if(F=2,k.oS.has(G)?F=0:g.Ae(k,G)&&(F=1),k=F,k===0)v&&(e.W=new g.jz(v));else if(k===2){this.X.start();wBn(this)&&this.seekTo(this.player.getCurrentTime());return}}}K.Pw.index.AJ(K.Ze)?(this.A.contains(e.VF[0].Ze)||iJx(this,e),this.W=g.lh(e.VF)):wBn(this)&&this.seekTo(this.player.getCurrentTime())}this.X.start()}},C_4=class extends g.l1{constructor(e,k){super(k);this.V=e;this.J=k;this.D=null;this.YV=!1;this.logger=new g.UV("caps");this.Vp=g.RK(this.J,this.V)}A(e,
k,v){this.Y();k=NdL(this,e.getId());k||(k=e.languageCode,k=this.V.isManifestless?xbK(this,k,"386"):xbK(this,k));if(k){var F=(k.index.QD(k.index.WB())-k.index.getStartTime(k.index.WB()))*1E3,K=new g.nnH(this.J.G());this.D=new AbL(K,this.J,k,(G,t)=>{v.Zk(G,e,t,F)},this.Vp||g.V4(k.info),()=>{this.D&&this.D.reset();
this.YV=!0})}}j(){var e=this.YV;
this.YV=!1;return e}U(e){var k=this.J.G().O("html5_fallback_if_rawcc_missing");var v=this.V.W.rawcc!=null;if(!this.Vp||!v&&k)k=this.V.isManifestless?r5n(this,"386"):r5n(this);else{if(!v){g.AK(this.logger,386248249,"rawcc used but unavailable");return}k=[new g.lB({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.lB({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(let F of k)g.gp(this.W,
F);e.kT()}Y(){this.D&&(this.D.dispose(),this.D=null)}K(){return""}},N9=/^#(?:[0-9a-f]{3}){1,2}$/i;var o9K=["left","right","center","justify"];var OU=class extends g.tO{constructor(e,k,v,F,K,G=!1,t=null){super(e,e+k,{priority:v,namespace:"captions"});this.windowId=F;this.text=K;this.append=G;this.W=t}toString(){return super.toString()}};var Aw=class extends g.C{constructor(e,k,v,F,K,G,t,V,T,H){var z=H.isInline()&&!0,X={};Object.assign(X,k);Object.assign(X,e.params);Object.assign(X,v);var S={};Object.assign(S,k.EF);e.params.EF&&Object.assign(S,e.params.EF);Object.assign(S,v.EF);z&&(X.windowOpacity=.6,S.backgroundOpacity=0);X.EF=S;var R=X.u3===1,J=[{L:"span",Z:"captions-text",B:{style:"word-wrap: normal; display: block;"}}],Z=V.Ei("caption_edit_on_hover")&&H.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
Z&&J.unshift({L:"button",Z:"caption-edit",B:{tabindex:"0","aria-label":Yvy()},S:[{L:"svg",B:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},S:[{L:"path",B:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({L:"div",Z:"caption-window",B:{id:`caption-window-${e.id}`,dir:R?"rtl":"ltr",tabindex:"0",lang:X.lang},S:J});this.experiments=
V;this.X=[];this.Jz=!1;this.V=e;this.I1=this.iu=null;this.yd=G;this.Eb=t;this.U=null;this.maxWidth=G*.96;this.maxHeight=t*.96;this.W=X;this.i4=v;this.Az=k;this.Y=this.wX("captions-text");e=this.Y.style;this.mH=V.Ei("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in e||"WebkitBoxDecorationBreak"in e);this.N3=QCg(F,K,G,t);this.PG=T;Z&&(this.K=this.wX("caption-edit"),this.N(this.K,"click",()=>{this.PG()}));
this.type=0;this.De=this.N3*c5S(S);this.IH=z;this.cw=V.Ei("enable_centered_caption_for_tvfilm_video")&&H.getVideoData().isTvfilmVideo;this.C=H.G().o1().W.hz(g.m7g);F=new g.UH(this.element,!0);g.w(this,F);F.subscribe("dragstart",this.pR,this);F.subscribe("dragmove",this.X7,this);F.subscribe("dragend",this.MZ,this);this.WX=this.Cd=this.HX=this.Uj=0;F="";this.W.windowOpacity&&(F=R5(this.W.windowColor),F="rgba("+F[0]+","+F[1]+","+F[2]+","+this.W.windowOpacity+")");K={"background-color":F,display:this.W.isVisible===
!1?"none":"","text-align":o9K[this.W.textAlign]};this.mH&&(K["border-radius"]=F?`${this.De*.375}px`:"");(this.A=this.V.params.u3===2||this.V.params.u3===3)&&sCp(this,this.element);g.Cj(this.element,K);z&&this.element.parentElement?.style.setProperty("--caption-window-color",F);switch(this.W.CG){case 0:case 1:case 2:g.Qw(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Qw(this.element,"ytp-caption-window-bottom")}}pR(e,k){this.Cd=e;this.WX=k;var v=g.Xg(this.element,this.element.parentElement);
this.Uj=e-v.x;this.HX=k-v.y}X7(e,k){if(e!==this.Cd||k!==this.WX){g.rS(this.element,"ytp-dragging")||g.Qw(this.element,"ytp-dragging");var v=g.gN(this.element);e=e-this.Uj-.02*this.yd;var F=k-this.HX-.02*this.Eb,K=(e+v.width/2)/this.maxWidth*3;K=Math.floor(g.sf(K,0,2));var G=(F+v.height/2)/this.maxHeight*3;G=Math.floor(g.sf(G,0,2));k=K+G*3;e=(e+K/2*v.width)/this.maxWidth;e=g.sf(e,0,1)*100;v=(F+G/2*v.height)/this.maxHeight;v=g.sf(v,0,1)*100;this.V.params.CG=k;this.V.params.vr=v;this.V.params.GG=e;this.V.params.isDefault=
!1;this.W.CG=k;this.W.vr=v;this.W.GG=e;this.W.isDefault=!1;this.Az.CG=k;this.Az.vr=v;this.Az.GG=e;this.Az.isDefault=!1;this.m2()}}MZ(){g.sI(this.element,"ytp-dragging")}m2(){this.D(this.X)}D(e){var k=this.IH?0:Math.min(this.nV(),this.maxWidth),v=this.oH(),F=this.IH;if(F){var K=getComputedStyle(this.Y.parentNode);K=nQ(K.borderLeftWidth)+nQ(K.borderRightWidth)+nQ(K.paddingLeft)+nQ(K.paddingRight)}else K=0;var G=K;K="";this.V.params.u3===3&&(K="rotate(180deg)");var t=F?`calc(96% - ${G}px)`:"96%";g.Cj(this.element,
{top:0,left:0,right:"",bottom:"",width:k?`${k}px`:"",height:v?`${v}px`:"","max-width":t,"max-height":t,margin:"",transform:""});this.Fk(e);K={transform:K,top:"",left:"",width:k?`${k}px`:"",height:v?`${v}px`:"","max-width":"","max-height":""};t=this.W.CG;var V=this.W.GG,T=this.W.vr;this.cw&&t!=null&&(V=50,t=Math.floor(t/3)*3+1);V=V*.96+2;switch(t){case 0:case 3:case 6:(F=this.W.EF.fontSizeIncrement)&&F>0&&this.W.u3!==2&&this.W.u3!==3&&(V=Math.max(V/(1+F*2),2));K.left=`${V}%`;break;case 1:case 4:case 7:K.left=
`${V}%`;V=0;this.C||(V=this.Y.offsetWidth);k||V?(k=k||V+1,K.width=`${k}px`,K["margin-left"]=F?`${k/-2-G/2}px`:`${k/-2}px`):(this.C&&(K.width="max-content"),K.transform+=" translateX(-50%)");break;case 2:case 5:case 8:K.right=`${100-V}%`}F=T*.96+2;switch(t){case 0:case 1:case 2:K.top=`${F}%`;break;case 3:case 4:case 5:K.top=`${F}%`;F=0;this.C||(F=this.element.clientHeight);(v=v||F)?(K.height=`${v}px`,K["margin-top"]=`${v/-2}px`):K.transform+=" translateY(-50%)";break;case 6:case 7:case 8:K.bottom=
`${100-F}%`}g.Cj(this.element,K);this.K&&(this.C?v=this.De:(e=jCp(this,e),v=this.cw?e>0?this.Y.offsetHeight/e:0:this.Y.offsetHeight/e),this.K.style.height=`${v}px`,this.K.style.width=`${v}px`,this.element.style.paddingLeft=`${v+5}px`,this.element.style.paddingRight=`${v+5}px`,this.C||(e=Number(this.element.style.marginLeft.replace("px",""))-v-5,v=Number(this.element.style.marginRight.replace("px",""))-v-5,this.element.style.marginLeft=`${e}px`,this.element.style.marginRight=`${v}px`))}Fk(e){if(this.type===
0&&this.V.params.bS!==void 0&&this.experiments.Ei("web_enable_popon_asr_captions")){var k=e,v=this.V.params.bS;if(k.length===0||v<=0)e=[];else{e=[];for(let K=k.length-1;K>=0;K--){var F=k[K];e.unshift(F);let G=jCp(this,e);if(G>v){e.shift();typeof F.text==="string"&&(k=F.text.split("\n"),v=G-v,k.length-v>0&&(v=k.slice(v),F=new OU(F.start,F.end-F.start,F.priority||0,F.windowId,v.join("\n"),F.append,F.W),e.unshift(F)));break}}}}for(F=0;F<e.length&&e[F]===this.X[F];F++);if(this.Jz||this.X.length>F)F=0,
this.Jz=!1,this.X=[],this.U=this.I1=this.iu=null,g.WQ(this.Y);for(;F<e.length;F++)lXU(this,e[F])}nV(){return 0}oH(){return 0}toString(){return super.toString()}};var eyK=class{constructor(){this.Y=this.time=this.mode=this.V=0;this.A=new b0n(this);this.U=new b0n(this);this.W=[];this.clear()}clear(){this.Y=this.time=this.mode=0;this.W=[];this.reset()}reset(){this.mode=0;this.A.reset(0);this.U.reset(1)}},mbu=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],kju=class{constructor(){this.type=0}set(e){this.type=e}get(){return this.type}},voK=class{constructor(){this.state=this.PZ=this.dN=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}sF(){return this.state!==0}matches(e,k){return this.sF()&&e===this.dN&&k===this.PZ}},FkK=class{constructor(){this.timestamp=this.W=0}reset(){this.timestamp=
this.W=0}},CQ=class{constructor(e){this.U=e;this.Y=[];this.W=this.V=this.row=0;this.style=new kju;this.A=0;for(e=0;e<=15;e++){this.Y[e]=[];for(let k=0;k<=32;k++)this.Y[e][k]=new FkK}}updateTime(e){for(let k=1;k<=15;++k)for(let v=1;v<=32;++v)this.Y[k][v].timestamp=e}debugString(){var e="\n";for(let k=1;k<=15;++k){for(let v=1;v<=32;++v){let F=this.Y[k][v];e=F.W===0?e+"_":e+String.fromCharCode(F.W)}e+="\n"}return e}reset(e){for(let k=0;k<=15;k++)for(let v=0;v<=32;v++)this.Y[k][v].reset();this.A=e;this.W=
0;this.V=this.row=1}},PFp=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],aXx=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],hJy=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,
199,200,202,203,235,206,207,239,212,217,249,219,171,187],UbL=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],Kkg=class{constructor(e){this.Y=e;this.U=0;this.style=new kju;this.K=new CQ(this.Y);this.X=new CQ(this.Y);this.text=new CQ(this.Y);this.V=this.K;this.A=this.X;this.W=this.V}reset(e,k){this.U=k;this.style.set(2);this.V=this.K;this.A=this.X;this.W=this.V;var v=(e<<2)+(k<<1);this.K.reset(v);this.X.reset(v);this.text.reset((e<<
2)+(k<<1)+1)}},b0n=class{constructor(e){this.W=e;this.U=0;this.Y=new Kkg(this.W);this.K=new Kkg(this.W);this.V=new voK;this.A=this.Y}reset(e){this.U=e;this.V.clear();this.A=this.Y;this.Y.reset(e,0);this.K.reset(e,1)}};var Gj4=class{A(){}};var o5=class extends g.Qa{reset(){}};var Ya=class extends g.tO{constructor(e,k,v,F,K){super(e,e+k,{priority:v,namespace:"captions"});this.id=F;this.params=K;this.W=[]}toString(){return super.toString()}},q9=0;var tax=class extends o5{constructor(e){super();this.A=e;this.pens={};this.D={};this.C={};this.U="_"+q9++;this.X={};this.V=this.W=null;this.K=!0}reset(){this.X={};this.V=this.W=null;this.K=!0}Y(e,k){e=e.firstChild;e.getAttribute("format");k=k||0;Number.isFinite(k);e=Array.from(e.childNodes);for(var v of e)if(v.nodeType===1)switch(v.tagName){case "head":var F=v;break;case "body":var K=v}if(F){F=Array.from(F.childNodes);for(var G of F)if(G.nodeType===1)switch(G.tagName){case "pen":v=G.getAttribute("id");
F=this.pens;e={};var t=G.getAttribute("p");t&&Object.assign(e,this.pens[t]);t=wK(G,"b");t!=null&&(e.bold=t);t=wK(G,"i");t!=null&&(e.italic=t);t=wK(G,"u");t!=null&&(e.underline=t);t=ic(G,"et");t!=null&&(e.charEdgeStyle=t);t=ic(G,"of");t!=null&&(e.offset=t);t=xa(G,"bc");t!=null&&(e.background=t);t=xa(G,"ec");t!=null&&(e.cN=t);t=xa(G,"fc");t!=null&&(e.color=t);t=ic(G,"fs");t!=null&&t!==0&&(e.fontFamily=t);t=ZR(G,"sz");t!==void 0&&(e.fontSizeIncrement=t/100-1);t=ZR(G,"bo");t!==void 0&&(e.backgroundOpacity=
t/255);t=ZR(G,"fo");t!==void 0&&(e.textOpacity=t/255);t=ic(G,"rb");t!=null&&t!==10&&t!==0&&(e.qJ=t>10?t-1:t);t=ic(G,"hg");t!=null&&(e.fb=t);F[v]=e;break;case "ws":F=G.getAttribute("id");this.C[F]=FiK(this,G);break;case "wp":F=G.getAttribute("id"),this.D[F]=KiK(this,G)}}if(K){G=[];K=Array.from(K.childNodes);for(Z of K)if(Z.nodeType===1)switch(Z.tagName){case "w":this.W=GpL(this,Z,k,!1);(K=this.X[this.W.id])&&K.end>this.W.start&&(K.end=this.W.start);this.X[this.W.id]=this.W;G.push(this.W);break;case "p":var V=
Z;e=k;K=[];F=V.getAttribute("w")||this.U;v=!!wK(V,"a");e=(ZR(V,"t")||0)+e;t=ZR(V,"d")||5E3;v||(!this.K&&this.V&&this.V.windowId===F&&this.V.end>e&&(this.V.end=e),this.V&&this.V.text==="\n"&&(this.V.text=""));let B=v?6:5;var T=V.getAttribute("p");T=T?this.pens[T]:null;let l=Array.from(V.childNodes);l.length&&(this.K=V.getAttribute("d")!=null);for(V=0;V<l.length;V++){var H=l[V],z=void 0;V>0&&(v=!0);let f;H.nodeType===1&&(f=H);if(f&&f.tagName==="s"){if((H=(H=f.getAttribute("p"))?this.pens[H]:null)&&
H.qJ&&(H.qJ===1?(H=l.slice(V,V+4),H.length===4&&(z=kpg(e,t,F,v,B,H,this.pens),V+=3)):z=kpg(e,t,F,v,B,[f],this.pens)),!z){var X=f;z=e;H=t;var S=F,R=v;let D=X.textContent?X.textContent:"";var J=X.getAttribute("p");J=J?this.pens[J]:null;X=ZR(X,"t")||0;z=new OU(z+X,H-X,B,S,D,R,J)}}else z=new OU(e,t,B,F,H.textContent||"",v,T);K.push(z);this.V=z}if(K.length>0){K[0].windowId===this.U&&(this.W=GpL(this,Z,k,!0),G.push(this.W));for(let f of K)f.windowId=this.W.id,this.W.W.push(f),G.push(f)}}var Z=G}else Z=
[];return Z}};var Van=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),Txy=class extends o5{constructor(e){super();this.K=e;this.W=new Map;this.A=new Map;this.U=new Map;this.V=new Map}reset(){this.V.clear()}Y(e,k){e=JSON.parse(e);if(!e)return[];if(e.pens){var v=e.pens,F=0;for(var K of v){v={};var G=K.pParentId;G&&Object.assign(v,this.W.get(G));K.bAttr&&(v.bold=!0);K.iAttr&&(v.italic=!0);K.uAttr&&(v.underline=!0);G=K.ofOffset;G!=null&&(v.offset=G);K.szPenSize!==void 0&&(v.fontSizeIncrement=K.szPenSize/100-1);
G=K.etEdgeType;G!=null&&(v.charEdgeStyle=G);K.ecEdgeColor!==void 0&&(v.cN=rK(K.ecEdgeColor));G=K.fsFontStyle;G!=null&&G!==0&&(v.fontFamily=G);K.fcForeColor!==void 0&&(v.color=rK(K.fcForeColor));K.foForeAlpha!==void 0&&(v.textOpacity=K.foForeAlpha/255);K.bcBackColor!==void 0&&(v.background=rK(K.bcBackColor));K.boBackAlpha!==void 0&&(v.backgroundOpacity=K.boBackAlpha/255);(G=K.rbRuby)&&G!==10&&(v.qJ=G>10?G-1:G,v.textEmphasis=Van.get(v.qJ));K.hgHorizGroup&&(v.fb=K.hgHorizGroup);this.W.set(F++,v)}}if(e.wsWinStyles){F=
e.wsWinStyles;K=0;for(var t of F)F={},(v=t.wsParentId)?Object.assign(F,this.U.get(v)):Object.assign(F,this.K),t.mhModeHint!==void 0&&(F.GS=t.mhModeHint),t.juJustifCode!==void 0&&(F.textAlign=t.juJustifCode),t.pdPrintDir!==void 0&&(F.u3=t.pdPrintDir),t.sdScrollDir!==void 0&&(F.LQ=t.sdScrollDir),t.wfcWinFillColor!==void 0&&(F.windowColor=rK(t.wfcWinFillColor)),t.wfoWinFillAlpha!==void 0&&(F.windowOpacity=t.wfoWinFillAlpha/255),this.U.set(K++,F)}if(e.wpWinPositions){K=e.wpWinPositions;t=0;for(var V of K)K=
{},(F=V.wpParentId)&&Object.assign(K,this.A.get(F)),V.ahHorPos!==void 0&&(K.GG=V.ahHorPos),V.apPoint!==void 0&&(K.CG=V.apPoint),V.avVerPos!==void 0&&(K.vr=V.avVerPos),V.ccCols!==void 0&&(K.rO=V.ccCols),V.rcRows!==void 0&&(K.bS=V.rcRows),this.A.set(t++,K)}if(e.events){e=e.events;V=[];for(let P of e)if(t=(P.tStartMs||0)+k,K=P.dDurationMs||0,P.id)F=String(P.id),e=t4u(this,P,t,K,F),V.push(e),this.V.set(F,e);else{P.wWinId?F=P.wWinId.toString():(F="_"+q9++,e=t4u(this,P,t,K,F),V.push(e),this.V.set(F,e));
e=V;var T=P;K===0&&(K=5E3);v=this.V.get(F);let kQ=(G=!!T.aAppend)?6:5,nE=T.segs,wZ=null;T.pPenId&&(wZ=this.W.get(T.pPenId));for(T=0;T<nE.length;T++){var H=nE[T],z=H.utf8;if(z){var X=H.tOffsetMs||0;let Bc=null;H.pPenId&&(Bc=this.W.get(H.pPenId));if((v.params.GS!=null?v.params.GS:v.W.length>1?1:0)===2&&G&&z==="\n")continue;H=null;var S=[],R;if(R=Bc&&Bc.qJ===1)a:{R=nE;var J=T;if(J+3>=R.length||!R[J+1].pPenId||!R[J+2].pPenId||!R[J+3].pPenId){R=!1;break a}var Z=R[J+1].pPenId;(Z=this.W.get(Z))&&Z.qJ&&Z.qJ===
2?(Z=R[J+2].pPenId,Z=this.W.get(Z),!Z||!Z.qJ||Z.qJ<3?R=!1:(Z=R[J+3].pPenId,R=(Z=this.W.get(Z))&&Z.qJ&&Z.qJ===2?!0:!1)):R=!1}if(R)X=nE[T+1].utf8,H=nE[T+3].utf8,R=nE[T+2].utf8,J=this.W.get(nE[T+2].pPenId),z=eg4(z,X,R,H,J),H=new OU(t,K,kQ,F,z,G,Bc),T+=3;else{if(z.indexOf("<")>-1){S=Bc;R=wZ;J=t;Z=K;var B=X,l=kQ,f=G;let MM=[];var D=g.od(`<html>${z}</html>`);if(!D.getElementsByTagName("parsererror").length&&D.firstChild?.childNodes.length)for(let og of D.firstChild.childNodes){D=og.textContent?.replace(/\n/g,
"")??"";if(og.nodeType===3&&(!D||D.match(/^ *$/)!=null))continue;let xY={};Object.assign(xY,S||R);switch(og?.tagName){case "b":xY.bold=!0;break;case "i":xY.italic=!0;break;case "u":xY.underline=!0}MM.push(new OU(J+B,Z-B,l,v.id,D,f,xY))}S=MM}S.length||(S=[new OU(t+X,K-X,kQ,v.id,z,G,Bc||wZ)])}if(S.length)for(let MM of S)e.push(MM),v.W.push(MM);else H&&(e.push(H),v.W.push(H))}G=!0}}k=V}else k=[];return k}};var HbL=class extends g.l1{constructor(e,k,v){super(e);this.videoData=k;this.audioTrack=v;this.C=k.W7}A(e,k,v){$bS(this.videoData.videoId,e.vssId,v.Zk)}U(e){if(this.audioTrack)for(let k of this.audioTrack.captionTracks)g.gp(this.W,k);e.kT()}};var yb7=class extends Aw{constructor(e,k,v,F,K,G,t,V,T,H){super(e,k,v,F,K,G,t,V,T,H);this.type=1}Fk(e){var k=this.V.W;super.Fk(e);for(e=e.length;e<k.length;e++){let K=k[e],G;if(F&&K.W===v)G=F;else{G={};Object.assign(G,K.W);Object.assign(G,zy4);var v=K.W;var F=G}lXU(this,K,G)}}},zy4={ZD:!0};var V4g=class extends Gj4{constructor(e,k){super();this.trackData=e;this.K=k;this.version=this.U=this.Y=this.byteOffset=0;this.V=[];this.W=new DataView(this.trackData)}A(e,k,v,F,K){if(v<F){let G="_"+q9++;v=v/1E3-this.K;F=F/1E3-this.K;e=new Ya(v,F-v,5,G,{textAlign:0,CG:0,GG:k*2.5,vr:e*5.33});K=new OU(v,F-v,5,G,K);this.V.push(e);this.V.push(K)}}},XH7=class extends o5{constructor(e,k){super();this.V=e;this.A=k;this.track=this.A.languageName==="CC3"?4:0;this.W=new eyK;this.W.V=1<<this.track}Y(e){e=new V4g(e,
this.V);if(TBn(e)){for(;e.byteOffset<e.W.byteLength;)for(e.version===0?e.Y=c9(e)*(1E3/45):e.version===1&&(e.Y=c9(e)*4294967296+c9(e)),e.U=Ql(e);e.U>0;e.U--){var k=Ql(e);let v=Ql(e),F=Ql(e);k&4&&(k&3)===this.track&&(this.track===0||this.track===1)&&(k=this.W,k.W.push({time:e.Y,type:this.track,cV:v,eK:F,order:k.W.length}))}MIn(this.W,e);return e.V}return[]}reset(){this.W.clear()}};var M4L=class extends Aw{constructor(e,k,v,F,K,G,t,V,T,H){super(e,k,v,F,K,G,t,V,T,H);this.type=2;this.Hw=[];this.Vp=this.j=this.R1=0;this.rX=NaN;this.F5=0;this.j4=null;this.BX=new g.Y1(this.SQ,433,this);this.K&&(H.createClientVe(this.K,this,167342),this.N(this.K,"click",()=>{H.logClick(this.K)}),e=new g.UH(this.element,!0),g.w(this,e),e.subscribe("hoverstart",()=>{H.logVisibility(this.K,!0)},this));
g.Qw(this.element,"ytp-caption-window-rollup");g.w(this,this.BX);g.Cj(this.element,"overflow","hidden")}m2(){g.wS(this.BX)}SQ(){this.element.removeEventListener("transitionend",this.SQ,!1);g.sI(this.element,"ytp-rollup-mode");this.D(this.j4,!0)}oH(){return this.A?this.Vp:this.j}nV(){return this.A?this.j:this.Vp}D(e,k){this.j4=e;if(this.V.params.bS){var v=0;for(let F=0;F<this.X.length&&v<e.length;F++)this.X[F]===e[v]&&v++;v>0&&v<e.length&&(e=this.X.concat(e.slice(v)));this.F5=this.Vp;this.j=this.Vp=
0;super.D(e);SG4(this,k)}super.D(e)}};var SKx=class{constructor(e,k,v,F){this.J=e;this.U=k;this.logger=v;this.r9=F;this.aH=[];this.W=null;this.Y=[];this.IS=[];this.V=null;this.Ej={WmH:()=>this.V,
Uy:()=>this.aH,
HLi:K=>{this.Y=K},
qaQ:()=>this.Y};
e=g.zT(this.J.G().experiments,"html5_override_micro_discontinuities_threshold_ms");this.A=e>0?e:10}unload(){this.V!=null&&(this.J.removeEventListener("sabrCaptionsDataLoaded",this.V),this.V=null);this.aH=[];this.W=null;this.Y=[];this.J.publish("sabrCaptionsBufferedRangesUpdated",this.aH)}qF(e){return{formatId:g.Ha(e.info.Pw.info,this.r9),Ze:e.info.Ze+(this.r9?0:1),startTimeMs:e.info.A*1E3,durationMs:e.info.K*1E3}}};var gop=class extends g.l1{constructor(e,k){super(k);this.V=e;this.J=k;this.logger=new g.UV("caps");this.D=this.Vp=null;this.YV=new SKx(this.J,this,this.logger,this.V.r9)}A(e,k,v){this.Y();k=e.getId();k=k!=null&&k in this.V.W?this.V.W[k]:null;k||(k=e.languageCode,k=this.V.isManifestless?Jbn(this,k,"386"):Jbn(this,k));k&&(this.D=e,this.Vp=k,d4p(this.YV,v),this.J.publish("sabrCaptionsTrackChanged",g.Ha(k.info,this.V.r9)))}U(e){var k=this.V.isManifestless?p0L(this,"386"):p0L(this);for(let v of k)g.gp(this.W,
v);e.kT()}Y(){this.D&&(this.D=this.Vp=null,this.YV.unload(),this.J.publish("sabrCaptionsTrackChanged",null))}K(){return""}};var LiJ="WEBVTT".split("").map(e=>e.charCodeAt(0)),w0L=class extends o5{constructor(){super()}Y(e,k){e instanceof ArrayBuffer&&(e=g.tB(new Uint8Array(e)));
var v=[];e=e.split(Ryg);for(let J=1;J<e.length;J++){var F=e[J],K=k;if(F!==""&&!Wky.test(F)){var G=bc.exec(F);if(G&&G.length>=4){var t=sU(G[1]),V=sU(G[2])-t;t+=K;var T=(G=G[3])?G.split(" "):[];G={};var H=null;var z="";var X=null,S="";for(let Z of T){T=Z.split(":");if(T.length!==2)continue;var R=T[1];switch(T[0]){case "line":T=R.split(",");T[0].endsWith("%")&&(H=T[0],G.vr=Number.parseInt(H,10),T.length===2&&(z=T[1].trim()));break;case "position":T=R.split(",");X=T[0];G.GG=Number.parseInt(X,10);T.length===
2&&(S=T[1].trim());break;case "align":switch(R){case "start":G.textAlign=0;break;case "middle":G.textAlign=2;break;case "end":G.textAlign=1}}}H||z||(z="end");if(!X)switch(G.textAlign){case 0:G.GG=0;break;case 1:G.GG=100;break;case 2:G.GG=50}if(G.textAlign!=null){H=0;switch(z){case "center":H+=3;break;case "end":H+=6;break;default:H+=0}switch(S){case "line-left":H+=0;break;case "center":H+=1;break;case "line-right":H+=2;break;default:switch(G.textAlign){case 0:H+=0;break;case 2:H+=1;break;case 1:H+=
2}}z=H<0||H>8?7:H;G.CG=z}F=F.substring(bc.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");S=G;G={};if(F.indexOf("<")<0&&F.indexOf("&")<0)K=O0g(t,V,5,S),t=new OU(t,V,5,K.id,F,!1,g.mL(G)?void 0:G),v.push(K),v.push(t),K.W.push(t);else for(z=F.split(noU),z.length===1?(F=5,S=O0g(t,V,F,S)):(H=F=6,S=Object.assign({rO:32},S),S=new Ya(t,V,H,"_"+q9++,S)),v.push(S),H=t,X=0;X<z.length;X++)if(T=z[X],X%2===0){R=g.od(`<html>${T}</html>`);let Z;R.getElementsByTagName("parsererror").length?(Z=R.createElement("span"),
Z.appendChild(R.createTextNode(T))):Z=R.firstChild;qGJ(this,H,V-(H-t),F,S,X>0,Z,G,v)}else H=sU(T)+K}bc.lastIndex=0}}return v}},Wky=/^NOTE/,Ryg=/(?:\r\n|\r|\n){2,}/,bc=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),noU=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var dLg=class extends g.Qa{constructor(e,k){super();this.J=e;this.Ww=k;this.W=null;this.GN=this.J.pf();this.logger=new g.UV("caps")}clear(){this.W&&this.W.dispose();this.W=null}reset(){this.W&&this.W.reset()}Qp(){super.Qp();this.clear()}};var Qqu={windowColor:"#080808",windowOpacity:0,textAlign:2,CG:7,GG:50,vr:100,isDefault:!0,EF:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},rbg={windowColor:"#080808",windowOpacity:0,textAlign:0,CG:7,GG:50,vr:100,isDefault:!0,EF:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.Sp("captions",class extends g.u1{constructor(e){super(e);this.J=e;this.rX=[];this.Az={};this.mH={};this.X=!1;this.Y="NONE";this.W=this.C=this.YV=this.R1=this.N3=null;this.Cd={kT:()=>{this.kT()},
Zk:(F,K,G,t,V=0)=>{var T=Number(this.videoData.G().o1().W.hz(g.beZ)??0);V>0&&T>0&&this.videoData.lengthSeconds>0&&V/this.videoData.lengthSeconds>T?this.J.yp("tts",{dropcap:V}):this.Zk(F,K,G,t)}};
this.V=null;this.Uj="";this.Ww=this.J.G();this.videoData=this.J.getVideoData();this.SQ=this.J.qg();this.U={EF:{}};this.K={EF:{}};this.videoData.hq()?this.Y="OFFLINE":g.aMQ(this.videoData,this.J)?this.Y="HLS":E9L(this.videoData,this.J)?this.Y="SABR_LIVE":g.hdH(this.videoData,this.J)?this.Y="LIVE":this.videoData.captionTracks.length?this.Y="INNERTUBE":this.videoData.HX&&(this.Y="TTS");this.iu=this.Ww.controlsType==="3";this.Fk=new dLg(this.J,this.Ww);this.Hw=new g.Lv(this);this.D=new g.C({L:"div",Z:"ytp-caption-window-container",
B:{id:"ytp-caption-window-container"}});this.Vp={top:0,right:0,bottom:0,left:0,width:1,height:1};var k=null,v=g.Hq("yt-html5-player-modules::subtitlesModuleData");v&&(k=new g.eT(v));this.storage=k;k=e.F7();this.HX=!!k?.rX();this.cw=!!k?.Jz();this.A=B9(this);this.j=x4K(this);g.w(this,this.Fk);this.A?this.I1=this.Jz=null:(this.Jz=new g.qZ(this.IH,void 0,this),g.w(this,this.Jz),this.I1=new g.Y1(this.BX,2E3,this),g.w(this,this.I1));g.w(this,this.Hw);g.Au(this.player,this.D.element,4);g.w(this,this.D);
this.A||this.Hw.N(e,"resize",this.WX);k=g.GK(this.Ww)&&!g.p9()&&!this.J.isFullscreen();v=this.Ww.o1().W.hz(g.ECh)&&g.UQ(this.Ww)&&g.rb;(this.hq=(k||v)&&!this.A&&!this.j)&&this.Hw.N(e,k?"resize":"fullscreentoggled",this.nV);this.Hw.N(e,"onPlaybackAudioChange",this.oH);this.Hw.N(e,g.Ds("captions"),F=>{this.onCueRangeEnter(F)});
this.Hw.N(e,g.yG("captions"),F=>{this.onCueRangeExit(F)});
j_(this,W9()||{});g.QB(this.player,"onCaptionsModuleAvailable");this.Y==="HLS"&&this.A&&(e=this.J.F7().Jq(),this.cw&&this.Hw.N(e.textTracks,"addtrack",this.F5))}Qp(){if(this.A||this.j){let e=this.J.F7();e&&!e.bu()&&e.X()}else I5(this,!1);super.Qp()}Be(){return this.Ww.O("html5_honor_caption_availabilities_in_audio_track")&&this.Y!=="LIVE"&&this.Y!=="SABR_LIVE"}h_(){if(this.iu)return this.A||this.j;if(this.Y==="HLS")return this.A;var e=this.getAudioTrack();if(this.Be()){if(!e.captionTracks.length)return!1;
if(!this.W)return!0}e=gK(e,g.JF(this.Ww));return e==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:e==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?fQ(this):mZ(this)||fQ(this)?!0:jqS(this)}load(){super.load();this.C=this.getAudioTrack();if(this.W)this.V&&(this.Fk.clear(),this.A?Icg(this,!0):this.player.getPresentingPlayerType()!==3&&this.W.A(this.V,"json3",this.Cd),this.Y!=="HLS"&&this.A||this.j||DR(this)||g.QB(this.player,"captionschanged",g.$X(this.V)));else{let e;this.Y==="OFFLINE"?e=new HbL(this.player,this.videoData,
this.getAudioTrack()):this.Y==="SABR_LIVE"?e=new gop(this.videoData.W,this.player):this.Y==="HLS"?e=new hgL(this.player):this.Y==="LIVE"?e=new C_4(this.videoData.W,this.player):this.Y==="INNERTUBE"?e=new g.mQ(this.player,this.videoData,this.getAudioTrack()):e=new g.fR(this.player,this.videoData.HX,this.videoData.videoId,g.x0g(this.videoData),this.videoData.pm,this.videoData.eventId);this.W=e;g.w(this,this.W);this.W.U(this.Cd)}}unload(){this.A&&this.V?Icg(this,!1):(this.I1&&this.I1.eW(),this.player.Ku("captions"),
this.rX=[],this.W&&this.W.Y(),this.Fk.clear(),this.YV&&this.player.j3(this.YV),this.WX());super.unload();this.player.TJ();g.QB(this.player,"captionschanged",{})}create(){this.h_()&&this.load();var e;a:{if(this.Ww.O("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(e=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(let k of e)if(k.kind==="asr"&&k.languageCode===
"en"){e=!0;break a}e=!1}e&&this.J.publish("showpromotooltip",this.D.element)}kT(){var e=gK(this.player.getAudioTrack(),g.JF(this.Ww));var k=e==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?M9(this,this.X):e==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&fQ(this)?yl(this):mZ(this)||this.X||jqS(this)?M9(this,this.X):fQ(this)?yl(this):null;if(this.Y!=="HLS"&&this.A||this.j){let v=g.aI(this.W.W,!0);e=[];for(let F=0;F<v.length;F++){let K=v[F],G=g.Sz("TRACK");G.setAttribute("kind","subtitles");G.setAttribute("label",
g.L3(K));G.setAttribute("srclang",g.O$(K));G.setAttribute("id",K.toString());this.j||G.setAttribute("src",this.W.K(K,"vtt"));K===k&&G.setAttribute("default","1");e.push(G)}k=this.J.F7();k.YV(e);e=k.Jq();this.cw&&this.Hw.N(e.textTracks,"change",this.m2)}else!this.V&&k&&UU(this,k),g.QB(this.player,"onCaptionsTrackListChanged"),g.cV(this.player,"onApiChange")}getTrackById(e){var k=g.aI(this.W.W,!0);for(let v=0;v<k.length;v++)if(k[v].toString()===e)return k[v];return null}m2(){var e=this.J.F7().Jq().textTracks,
k=null;for(let v=0;v<e.length;v++)e[v].mode==="showing"&&(k=this.getTrackById(e[v].id));(this.loaded?this.V:null)!==k&&UU(this,k,!0)}F5(){this.W?.U(this.Cd)}S6(){!this.V&&this.A||this.unload()}Zk(e,k,v,F){if(e){hw(this,this.V??void 0);this.W.j()&&(this.rX=[],this.J.Ku("captions"),S_(this.Jz),this.Fk.reset());a:{var K=this.Fk;F=F||0;v=Z07(K,e,v||0);e=[];try{for(let l of v){let f=l.trackData,D=l.V6,P=K.Ww.O("safari_live_drm_captions_fix");if(typeof f!=="string"){v=e;var G=v.concat;if(P&&$4g(f))var t=
i0L(K,f,D);else{var V=K,T=k,H=f,z=D,X=F;if(!H0g(H))throw Error("Invalid binary caption track data");V.W||(V.W=new XH7(X,T));t=V.W.Y(H,z)}var S=G.call(v,t)}else{if(f.substring(0,6)==="WEBVTT")var R=e.concat(i0L(K,f,D));else{v=e;var J=v.concat;b:{T=K;V=k;if(f[0]==="{")try{T.W||(T.W=new Txy(NBp(V)));var Z=T.W.Y(f,D);break b}catch(wZ){g.b3(wZ);Z=[];break b}let kQ=g.od(f);if(!kQ||!kQ.firstChild){let wZ=Error("Invalid caption track data");wZ.params=f;throw wZ;}if(kQ.firstChild.tagName==="timedtext"){if(Number(kQ.firstChild.getAttribute("format"))===
3){H=kQ;T.W||(T.W=new tax(NBp(V)));Z=T.W.Y(H,D);break b}let wZ=Error("Unsupported subtitles format in web player (Format2)");wZ.params=f;throw wZ;}if(kQ.firstChild.tagName==="transcript"){let wZ=Error("Unsupported subtitles format in web player (Format1)");wZ.params=f;throw wZ;}let nE=Error("Invalid caption track data");nE.params=f;throw nE;}R=J.call(v,Z)}S=R}e=S}var B=e;break a}catch(l){g.AK(K.logger,187101178,`Captions parsing failed: ${l.message}. `);K.clear();B=[];break a}B=void 0}this.Ww.O("html5_sabr_live_support_subfragmented_captions")&&
this.W instanceof gop&&(k=this.W.YV,K=[],B.length>0&&(K=B.slice(k.Y.length)),k.Y=!k.W||k.W.info.Lu?[]:B,B=K);k=this.Ww.o1().W.hz(g.VjE);B.length>0&&(!k||this.Uj!==this.V?.V())&&(K=this.V,this.Mk(K,!!K,DR(this)?"g":this.X?"m":"s"),k&&(this.Uj=this.V?.V()||""));this.player.j3(B,void 0,this.Y==="LIVE"||this.Y==="SABR_LIVE");!this.X||this.j||DR(this)||g.N2(this.Ww)||g.KF(this.Ww)||g.dH(this.Ww)||this.Ww.Hw==="shortspage"||this.player.isInline()||(this.I1.eW(),B=v9V({CG:0,GG:5,vr:5,bS:2,textAlign:0,u3:0,
lang:"en"}),this.R1=[B],k=["Click "," for settings"],this.N3||(K=new g.Ih(g.Aa()),g.w(this,K),this.N3=K.element),K=B.end-B.start,(S=g.L3(this.V))&&this.R1.push(new OU(B.start,K,0,B.id,S)),this.R1.push(new OU(B.start,K,0,B.id,k[0]),new OU(B.start,K,0,B.id,this.N3,!0),new OU(B.start,K,0,B.id,k[1],!0)),this.player.j3(this.R1),g.Zo(this.I1));!this.X||this.j||DR(this)||(this.Ww.O("enable_player_captions_persistence_state_machine")?lc(this,!0):g.JF(this.Ww)?P9(this,!0):a5(this,!0),this.C&&(this.C.A=this.V),
this.player.TJ());this.X=!1}}onCueRangeEnter(e){this.rX.push(e);S_(this.Jz)}onCueRangeExit(e){g.vS(this.rX,e);this.W instanceof C_4&&this.W.Vp&&this.player.Sa([e]);S_(this.Jz)}getCaptionWindowContainerId(){return this.D.element.id}BX(){cbS(this,this.R1);this.R1=null}IH(){if(!this.hq||!this.A){this.Jz.stop();g.fy(this.mH);this.rX.sort(g.fW);var e=this.rX;if(this.YV){let k=g.fE(e,function(v){return this.YV.indexOf(v)===-1},this);
k.length&&(e=k)}for(let k of e)k instanceof Ya?m4S(this,k):fcy(this,k);for(let [k,v]of Object.entries(this.Az)){let F=k,K=v;this.mH[F]?(K.element.parentNode||(K instanceof M4L||K instanceof yb7||g.Ng(this.Az,(G,t)=>{t!==F&&G.V.params.CG===K.V.params.CG&&G.V.params.GG===K.V.params.GG&&G.V.params.vr===K.V.params.vr&&(G.dispose(),delete this.Az[t]);return t===F},this),this.D.element.appendChild(K.element)),K.D(this.mH[F])):(K.dispose(),delete this.Az[F])}}}cY(){j_(this,{},!0);
g.QB(this.player,"captionssettingschanged")}Lk(){var e=this.Ww.O("enable_player_captions_new_style_defaults")?rbg:Qqu,k=e.EF;e={background:k.background,backgroundOpacity:k.backgroundOpacity,charEdgeStyle:k.charEdgeStyle,color:k.color,fontFamily:k.fontFamily,fontSizeIncrement:k.fontSizeIncrement,fontStyle:k.bold&&k.italic?3:k.bold?1:k.italic?2:0,textOpacity:k.textOpacity,windowColor:e.windowColor,windowOpacity:e.windowOpacity};k=W9()||{};k.background!=null&&(e.background=k.background);k.backgroundOverride!=
null&&(e.backgroundOverride=k.backgroundOverride);k.backgroundOpacity!=null&&(e.backgroundOpacity=k.backgroundOpacity);k.backgroundOpacityOverride!=null&&(e.backgroundOpacityOverride=k.backgroundOpacityOverride);k.charEdgeStyle!=null&&(e.charEdgeStyle=k.charEdgeStyle);k.charEdgeStyleOverride!=null&&(e.charEdgeStyleOverride=k.charEdgeStyleOverride);k.color!=null&&(e.color=k.color);k.colorOverride!=null&&(e.colorOverride=k.colorOverride);k.fontFamily!=null&&(e.fontFamily=k.fontFamily);k.fontFamilyOverride!=
null&&(e.fontFamilyOverride=k.fontFamilyOverride);k.fontSizeIncrement!=null&&(e.fontSizeIncrement=k.fontSizeIncrement);k.fontSizeIncrementOverride!=null&&(e.fontSizeIncrementOverride=k.fontSizeIncrementOverride);k.fontStyle!=null&&(e.fontStyle=k.fontStyle);k.fontStyleOverride!=null&&(e.fontStyleOverride=k.fontStyleOverride);k.textOpacity!=null&&(e.textOpacity=k.textOpacity);k.textOpacityOverride!=null&&(e.textOpacityOverride=k.textOpacityOverride);k.windowColor!=null&&(e.windowColor=k.windowColor);
k.windowColorOverride!=null&&(e.windowColorOverride=k.windowColorOverride);k.windowOpacity!=null&&(e.windowOpacity=k.windowOpacity);k.windowOpacityOverride!=null&&(e.windowOpacityOverride=k.windowOpacityOverride);return e}IK(e,k){var v={};Object.assign(v,W9());Object.assign(v,e);j_(this,v,k);g.QB(this.player,"captionssettingschanged")}WX(){!this.A&&this.loaded&&(g.YV(this.Az,function(e,k){e.dispose();delete this.Az[k]},this),this.IH())}Vi(e,k){switch(e){case "fontSize":if(isNaN(k))break;
e=g.sf(k,-2,4);this.IK({fontSizeIncrement:e});return e;case "reload":k&&!this.A&&UU(this,this.V,!0);break;case "stickyLoading":k!==void 0&&this.Ww.YV&&(this.Ww.O("enable_player_captions_persistence_state_machine")?lc(this,!(!k||!k.userInitiated)):g.JF(this.Ww)?P9(this,!!k):a5(this,!!k));break;case "track":return P_g(this,k);case "tracklist":return this.W?g.DH(g.aI(this.W.W,!(!k||!k.includeAsr)),v=>g.$X(v)):[];
case "translationLanguages":return this.W?this.W.C.map(v=>Object.assign({},v)):[];
case "sampleSubtitles":this.A||k===void 0||I5(this,!!k);break;case "sampleSubtitlesCustomized":this.A||I5(this,!!k,k);break;case "recommendedTranslationLanguages":return g.n3();case "defaultTranslationSourceTrackIndices":return this.W?this.W.Az:[]}}getOptions(){var e="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Ww.YV&&e.push("stickyLoading");return e}o8(){var e=this.V;if(this.J.gw("captions")){if(this.Ww.O("html5_modify_caption_vss_logging"))return(e=this.videoData.ee??
null)?{cc:g.UTn(e)}:{};if(e){let k=e.vssId;e.translationLanguage&&k&&(k=`t${k}.${g.O$(e)}`);return{cc:k}}}return{}}ur(e){this.isSubtitlesOn()?(this.Ww.O("enable_player_captions_persistence_state_machine")&&e?lc(this,!1):g.JF(this.Ww)?P9(this,!1):a5(this,!1),hw(this),UU(this,null,!0)):this.c5(e)}c5(e){var k=DR(this)||!this.V?M9(this,!0):this.V;k&&this.ol(k.vssId,"m");this.isSubtitlesOn()||UU(this,k,this.Ww.O("enable_player_captions_persistence_state_machine")?e:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.V&&!DR(this)}oH(){var e=DR(this);fQ(this,e)?UU(this,this.getAudioTrack().W,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Be()&&(this.X=!1,this.V=null,this.W&&(this.W.dispose(),this.W=null)),this.h_()&&(e?UU(this,M9(this,!1),!1):this.load()))}zh(e){e&&(this.Vp={top:e.top,right:e.right,bottom:e.bottom,left:e.left,width:1-e.left-e.right,height:1-e.top-e.bottom},this.D.element.style.top=`${this.Vp.top*100}%`,this.D.element.style.left=`${this.Vp.left*100}%`,this.D.element.style.width=
`${this.Vp.width*100}%`,this.D.element.style.height=`${this.Vp.height*100}%`,this.D.element.style.position="absolute",e=D4g(this))&&(this.D.element.style.width=`${e.width}px`,this.D.element.style.height=`${e.height}px`)}onVideoDataChange(e,k){e==="newdata"&&(this.videoData=k,this.loaded&&this.unload(),this.X=!1,this.V=null,this.W&&(this.W.dispose(),this.W=null,g.QB(this.player,"captionschanged",{})),this.h_()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}nV(){if(this.Ww.o1().W.hz(g.ECh)){if(this.loaded&&
this.unload(),this.iu=this.J.isFullscreen()||this.Ww.controlsType==="3",this.A=B9(this),this.j=x4K(this),this.A||this.j){var e=this.J.F7();e&&!e.bu()&&e.X();this.kT()}}else(e=this.J.F7())&&!e.bu()&&e.X(),this.J.isFullscreen()?(this.A=this.iu=!0,this.loaded&&this.kT()):(this.iu=this.Ww.controlsType==="3",this.A=B9(this));UU(this,this.V)}De(){var e=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;e&&g.iM(this.player,"innertubeCommand",e)}Mk(e,k,v){var F=
/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,K="";e&&(K=e.vssId,K=K.replace(F,""));var G="";if(e&&e.getId()&&this.Ww.o1().W.hz(g.VjE))if(G=e.getId()||"",G.includes(";"))G=G.split(";").map(V=>V.replace(F,"")).join(";");
else{G=G.replace(F,"");var t="";e.getXtags()&&(t=e.getXtags(),t=t.replace(F,""),G=G.concat(`;${t}`))}else e&&e.getId()&&(G=e.getId()||""),t="",e&&e.getXtags()&&(t=e.getXtags(),t=t.replace(F,""),G=G.concat(`;${t}`));this.Y==="HLS"&&(G="");this.J.Mk(k?K:"",k?G:"",v)}ol(e,k){e=(e||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");e.length>0&&this.J.ol(e,k)}});})(_yt_player);
