(function(g){var window=this;'use strict';var mLV=function(e,k){g.iM(e,"onAutonavCoundownStarted",k)},fKg=function(e){return e.isBackground()&&e.vQ()},DLL=function(e,k){k=k.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.nextButton?.buttonRenderer;
e.j=k?.navigationEndpoint;k=k?.trackingParams;e.playButton&&k&&e.J.setTrackingParams(e.playButton.element,k)},zU=function(e){var k=TU(e),v=Math,F=v.min;
var K=e.X?Date.now()-e.X:0;v=F.call(v,K,k);HC(e,Math.ceil((k-v)/1E3));k-v<=500&&e.W()?e.select(!0):e.W()&&e.D.start()},X2=function(e){var k=e.J.A0(!0,e.J.isFullscreen());
g.jA(e.container.element,"ytp-autonav-endscreen-small-mode",e.mg(k));g.jA(e.container.element,"ytp-autonav-endscreen-is-premium",!!e.suggestion&&!!e.suggestion.HD);g.jA(e.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!e.J.ZP());g.jA(e.J.getRootNode(),"countdown-running",e.W());g.jA(e.container.element,"ytp-player-content",e.J.ZP());e.J.O("web_post_play_autonav_embiggening")||g.Cj(e.overlay.element,{width:`${k.width}px`});if(e.J.O("web_post_play_autonav_embiggening")){var v=e.J.getRootNode().getBoundingClientRect();
k=Math.min(720,v.width*.5);var F=k*.5625;v=v.height-36-60;F>v&&(F=v,k=16/9*F);g.Cj(e.V.wX("ytp-autonav-endscreen-upnext-thumbnail"),{height:`${F}px`,width:`${k}px`});g.Cj(e.container.element,{width:`${k}px`})}e.W()||(e.J.ZP()?HC(e,Math.round(TU(e)/1E3)):HC(e),k=!!e.suggestion&&!!e.suggestion.ZE,F=e.J.getVideoData(),F=F?.autonavState===1&&F?.MZ&&e.J.ZP()?!1:e.J.ZP()||!(e.suggestion&&e.suggestion.ZE),g.jA(e.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!F&&k),g.jA(e.container.element,
"ytp-autonav-endscreen-upnext-no-alternative-header",F&&!k),e.K.xv(e.J.ZP()))},HC=function(e,k=-1){e=e.V.wX("ytp-autonav-endscreen-upnext-header");
g.WQ(e);if(k>=0){k=String(k);let F="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],K="Up next in $SECONDS".indexOf(F);if(K>=0){var v=g.gV("Up next in $SECONDS".slice(0,K));e.appendChild(v);v=g.Sz("span");g.x1(v,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Jv(v,k);e.appendChild(v);k=g.gV("Up next in $SECONDS".slice(K+F.length));e.appendChild(k);return}}g.Jv(e,"Up next")},TU=function(e){return e.J.isFullscreen()?(e=e.J.getVideoData()?.g8,e===-1||e===void 0?8E3:e):e.J.DM()>=0?
e.J.DM():g.zT(e.J.G().experiments,"autoplay_time")||1E4},SY=function(e,k){k=yEV(e,k);
var v=Math,F=v.min;var K=(0,g.M)()-e.X;v=F.call(v,K,k);k=k===0?1:Math.min(v/k,1);e.rX.setAttribute("stroke-dashoffset",`${-211*(k+1)}`);k>=1&&e.W()&&!e.isCasting()?e.select(!0):e.W()&&e.V.start()},yEV=function(e,k){return k?k:e.api.isFullscreen()?(e=e.api.getVideoData()?.g8,e===-1||e===void 0?8E3:e):e.api.DM()>=0?e.api.DM():g.zT(e.api.G().experiments,"autoplay_time")||1E4},gj=function(e){return g.CN(e.player)&&e.D()&&!e.A},Rf=function(e){var k=e.ZP();
k!==e.C&&(e.C=k,e.player.publish("autonavvisibility"))},WC=function(e){return g.CN(e.player)&&e.D()&&!e.U},nV=function(e){var k=e.ZP();
k!==e.Vp&&(e.Vp=k,e.player.publish("autonavvisibility"))},Ma7=function(e){e=e.G();
return e.PG&&!e.disableOrganicUi},PHK=function(e){var k=e.player.getVideoData();
if(!k||e.W===k.IH)return!1;e.W=k.IH;return!0},aKJ=function(e){e.player.Ku("endscreen");
var k=e.player.getVideoData();k=new g.tO(Math.max((k.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var v=new g.tO(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});e.player.j3([k,v])};
g.nR.prototype.DM=g.KE(16,function(){return this.app.DM()});
g.vL.prototype.DM=g.KE(15,function(){return this.getVideoData().nM});
g.WO.prototype.m$=g.KE(14,function(e){this.hX().m$(e)});
g.K8.prototype.m$=g.KE(13,function(e){this.Fu!==e&&(this.Fu=e,this.As())});
var dj=class extends g.C{constructor(e){super({L:"div",Z:"ytp-autonav-endscreen-countdown-overlay"});this.cancelCommand=this.j=void 0;this.X=0;e.O("web_post_play_autonav_embiggening")&&g.Qw(this.element,"ytp-autonav-endscreen-upnext-updated");this.container=new g.C({L:"div",Z:"ytp-autonav-endscreen-countdown-container"});g.w(this,this.container);this.container.Kd(this.element);var k=e.G(),v=k.A;this.J=e;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.N(e,"videodatachange",
this.onVideoDataChange);this.V=new g.C({L:"div",Z:"ytp-autonav-endscreen-upnext-container",B:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{L:"div",Z:"ytp-autonav-endscreen-topbar-container",S:[{L:"div",Z:"ytp-autonav-endscreen-upnext-header"},{L:"div",Z:"ytp-autonav-endscreen-upnext-alternative-header",Ui:"{{autoplayAlternativeHeader}}"}]},{L:"a",Z:"ytp-autonav-endscreen-link-container",
B:{href:"{{url}}",target:v?k.j:""},S:[{L:"div",Z:"ytp-autonav-endscreen-upnext-thumbnail",B:{style:"{{background}}"},S:[{L:"div",B:{"aria-label":"{{timestamp}}"},M3:["ytp-autonav-timestamp"],Ui:"{{duration}}"},{L:"div",M3:["ytp-autonav-live-stamp"],Ui:"Live"},{L:"div",M3:["ytp-autonav-upcoming-stamp"],Ui:"Upcoming"}]},{L:"div",Z:"ytp-autonav-endscreen-video-info",S:[{L:"div",Z:"ytp-autonav-endscreen-premium-badge"},{L:"div",Z:"ytp-autonav-endscreen-upnext-title",Ui:"{{title}}"},{L:"div",Z:"ytp-autonav-endscreen-upnext-author",
Ui:"{{author}}"},{L:"div",Z:"ytp-autonav-view-and-date",Ui:"{{views_and_publish_time}}"},{L:"div",Z:"ytp-autonav-author-and-view",Ui:"{{author_and_views}}"}]}]}]});g.w(this,this.V);this.V.Kd(this.container.element);v||this.N(this.V.wX("ytp-autonav-endscreen-link-container"),"click",this.Hw);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.V.wX("ytp-autonav-endscreen-link-container"),this,115128);this.closeButton=new g.C({L:"button",Z:"ytp-autonav-endscreen-upnext-header-close-button",
B:{"aria-label":"Cancel autoplay"}});g.w(this,this.closeButton);e.O("web_post_play_autonav_embiggening")&&(this.closeButton.listen("click",this.Az,this),this.J.createClientVe(this.closeButton.element,this,115129),this.V.wX("ytp-autonav-endscreen-topbar-container").appendChild(this.closeButton.element));this.overlay=new g.C({L:"div",Z:"ytp-autonav-overlay"});g.w(this,this.overlay);this.overlay.Kd(this.container.element);this.K=new g.C({L:"div",Z:"ytp-autonav-endscreen-button-container"});g.w(this,
this.K);this.K.Kd(this.container.element);this.cancelButton=new g.C({L:"button",M3:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],B:{"aria-label":"Cancel autoplay"},Ui:"Cancel"});g.w(this,this.cancelButton);this.cancelButton.Kd(this.K.element);this.cancelButton.listen("click",this.Az,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.C({L:"a",M3:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button","ytp-autonav-endscreen-upnext-button-rounded"],B:{href:"{{url}}",role:"button","aria-label":"Play next video"},Ui:"Play Now"});g.w(this,this.playButton);this.playButton.Kd(this.K.element);this.playButton.listen("click",this.Hw,this);this.J.createServerVe(this.playButton.element,this.playButton,!0);(k=this.J.getVideoData())&&DLL(this,k);this.D=new g.Y1(()=>{zU(this)},500);
g.w(this,this.D);this.Vp();this.N(e,"autonavvisibility",this.Vp)}C(e){this.suggestion!==e&&(this.suggestion=e,g.b2(this.V,e),this.playButton.updateValue("url",this.suggestion.TG()),X2(this))}W(){return this.X>0}U(){this.W()||(this.X=Date.now(),zU(this),mLV(this.J,TU(this)),g.jA(this.J.getRootNode(),"countdown-running",this.W()))}A(){this.Y();zU(this);var e=this.V.wX("ytp-autonav-endscreen-upnext-header");e&&g.Jv(e,"Up next")}Y(){this.W()&&(this.D.stop(),this.X=0)}select(e=!1){this.J.nextVideo(!1,
e);this.Y()}Hw(e){g.zc(e,this.J)&&(e.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):e.currentTarget===this.V.wX("ytp-autonav-endscreen-link-container")&&(e=this.V.wX("ytp-autonav-endscreen-link-container"),this.J.logVisibility(e,!0),this.J.logClick(e)),this.j?(g.iM(this.J,"innertubeCommand",this.j),this.Y()):this.select())}Az(){this.J.logClick(this.cancelButton.element);g.D_(this.J,!0);this.cancelCommand&&g.iM(this.J,"innertubeCommand",this.cancelCommand)}onVideoDataChange(e,
k){DLL(this,k);this.cancelCommand=k.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.cancelButton?.buttonRenderer?.command}Vp(){var e=this.J.ZP();this.w9!==e&&this.xv(e);X2(this);this.J.logVisibility(this.container.element,e);this.J.logVisibility(this.cancelButton.element,e);this.J.logVisibility(this.V.wX("ytp-autonav-endscreen-link-container"),e);this.J.logVisibility(this.playButton.element,e)}mg(e){return e.width<400||e.height<459}};var E1=class extends g.C{constructor(e,k){super({L:"div",M3:["html5-endscreen","ytp-player-content",k||"base-endscreen"]});this.created=!1;this.player=e}create(){this.created=!0}destroy(){this.created=!1}D(){return!1}ZP(){return!1}j(){return!1}};var hyg=class extends g.C{constructor(e){super({L:"div",M3:["ytp-upnext","ytp-player-content"],B:{"aria-label":"{{aria_label}}"},S:[{L:"div",Z:"ytp-cued-thumbnail-overlay-image",B:{style:"{{background}}"}},{L:"span",Z:"ytp-upnext-top",S:[{L:"span",Z:"ytp-upnext-header",Ui:"Up Next"},{L:"span",Z:"ytp-upnext-title",Ui:"{{title}}"},{L:"span",Z:"ytp-upnext-author",Ui:"{{author}}"}]},{L:"a",Z:"ytp-upnext-autoplay-icon",B:{role:"button",href:"{{url}}","aria-label":"Play next video"},S:[{L:"svg",B:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},S:[{L:"circle",Z:"ytp-svg-autoplay-circle",B:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{L:"circle",Z:"ytp-svg-autoplay-ring",B:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{L:"path",Z:"ytp-svg-fill",B:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{L:"span",Z:"ytp-upnext-bottom",S:[{L:"span",Z:"ytp-upnext-cancel"},
{L:"span",Z:"ytp-upnext-paused",Ui:"Autoplay is paused"}]}]});this.api=e;this.cancelButton=null;this.rX=this.wX("ytp-svg-autoplay-ring");this.D=this.notification=this.V=this.suggestion=null;this.j=new g.Y1(this.K,5E3,this);this.X=0;var k=this.wX("ytp-upnext-cancel");this.cancelButton=new g.C({L:"button",M3:["ytp-upnext-cancel-button","ytp-button"],B:{tabindex:"0","aria-label":"Cancel autoplay"},Ui:"Cancel"});g.w(this,this.cancelButton);this.cancelButton.listen("click",this.Az,this);this.cancelButton.Kd(k);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.w(this,this.j);this.api.createClientVe(this.element,this,18788);k=this.wX("ytp-upnext-autoplay-icon");this.N(k,"click",this.Hw);this.api.createClientVe(k,this,115130);this.Vp();this.N(e,"autonavvisibility",this.Vp);this.N(e,"mdxnowautoplaying",this.Jz);this.N(e,"mdxautoplaycanceled",this.iu);g.jA(this.element,"ytp-upnext-mobile",this.api.G().Y)}K(){this.notification&&(this.j.stop(),this.Z4(this.D),this.D=null,this.notification.close(),
this.notification=null)}C(e){this.suggestion=e;g.b2(this,e,"hqdefault.jpg")}Vp(){this.xv(this.api.ZP());this.api.logVisibility(this.element,this.api.ZP());this.api.logVisibility(this.wX("ytp-upnext-autoplay-icon"),this.api.ZP());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.ZP())}I1(){window.focus();this.K()}U(e){this.W()||(g.iJ("a11y-announce",`Up Next ${this.suggestion.title}`),this.X=(0,g.M)(),this.V=new g.Y1(()=>{SY(this,e)},25),SY(this,e),mLV(this.api,yEV(this,
e)));
g.sI(this.element,"ytp-upnext-autoplay-paused")}hide(){super.hide()}W(){return!!this.V}isCasting(){return this.api.getPresentingPlayerType()===3}A(){this.Y();this.X=(0,g.M)();SY(this);g.Qw(this.element,"ytp-upnext-autoplay-paused")}Y(){this.W()&&(this.V.dispose(),this.V=null)}select(e=!1){if(this.api.G().O("autonav_notifications")&&e&&window.Notification&&typeof document.hasFocus==="function"){let k=Notification.permission;k==="default"?Notification.requestPermission():k!=="granted"||document.hasFocus()||
(this.K(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.X$()}),this.D=this.N(this.notification,"click",this.I1),this.j.start())}this.Y();this.api.nextVideo(!1,e)}Hw(e){!g.EO(this.cancelButton.element,e.target)&&g.zc(e,this.api)&&(this.api.ZP()&&this.api.logClick(this.wX("ytp-upnext-autoplay-icon")),this.select())}Az(){this.api.ZP()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.D_(this.api,!0)}Jz(e){this.isCasting();this.show();this.U(e)}iu(){this.isCasting();
this.Y();this.hide()}Qp(){this.Y();this.K();super.Qp()}};var ULV=class extends E1{constructor(e){super(e,"videowall-endscreen");this.J=e;this.stills=[];this.A=this.videoData=null;this.U=this.C=!1;this.Vp=null;g.Qw(this.element,"modern-videowall-endscreen");this.V=new g.Lv(this);g.w(this,this.V);this.K=new g.Y1(()=>{g.Qw(this.element,"ytp-show-tiles")},0);
g.w(this,this.K);this.table=new g.Ih({L:"div",Z:"ytp-modern-endscreen-content"});g.w(this,this.table);this.table.Kd(this.element);e.getVideoData().IH?this.W=new dj(e):this.W=new hyg(e);g.w(this,this.W);g.Au(this.player,this.W.element,4);e.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var e=this.player.getVideoData();e&&(this.videoData=e);this.Y();this.V.N(this.player,"appresize",this.Y);this.V.N(this.player,"onVideoAreaChange",this.Y);this.V.N(this.player,"videodatachange",
this.onVideoDataChange);this.V.N(this.player,"autonavchange",this.X);this.V.N(this.player,"onAutonavCancelled",this.Az);e=this.videoData.autonavState;e!==this.Vp&&this.X(e,!1);this.V.N(this.element,"transitionend",this.Hw)}destroy(){this.V.V();g.rd(this.stills);this.stills=[];super.destroy();g.sI(this.element,"ytp-show-tiles");this.K.stop();this.Vp=this.videoData.autonavState}D(){return this.videoData?.MZ||this.videoData.autonavState!==1}show(){var e=this.w9;super.show();g.sI(this.element,"ytp-show-tiles");
this.player.G().Y?g.wS(this.K):this.K.start();(this.U||this.A&&this.A!==this.videoData.clientPlaybackNonce)&&g.D_(this.player,!1);gj(this)?(Rf(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||fKg(this.player.l3())&&this.player.O("web_player_pip_logging_fix")?this.W.select(!0):this.W.U():this.videoData.autonavState===3&&this.W.A()):(g.D_(this.player,!0),Rf(this));e!==this.w9&&this.player.logVisibility(this.element,!0)}hide(){var e=this.w9;super.hide();this.W.A();Rf(this);
e!==this.w9&&this.player.logVisibility(this.element,!1)}Hw(e){e.target===this.element&&this.Y()}Y(){var e=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.YV()];if(e.length){var k=this.J.A0(!0,this.J.isFullscreen()),v=Math.floor((k.width-64+16)/(g.sf(k.width*.27,250,450)+16));k=Math.min(3,Math.floor((k.height-64)/((k.width-64-(v-1)*16)/v*.5625+70)));g.BW(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.Qw(this.element,`ytp-modern-endscreen-limit-rows-${k}`);g.jA(this.element,"ytp-modern-endscreen-single-item",v===1);g.jA(this.element,"ytp-modern-endscreen-row-0",k===0);v=this.table.element;v.ariaLive="polite";this.W.C(this.videoData.YV());this.W instanceof dj&&X2(this.W);g.jA(this.element,"ytp-endscreen-takeover",gj(this));Rf(this);k=0;v.ariaBusy="true";var F=e.length;for(let K=0;K<F;K++){let G=K%F,t=this.stills[K];t||(t=new g.Ty7(this.player),this.stills[K]=t,v.appendChild(t.element));g.ZxU(t,
e[G]);k++}this.stills.length=k}}onVideoDataChange(){var e=this.player.getVideoData({playerType:1});this.videoData!==e&&(e?.YV()?(this.videoData=e,this.Y()):this.player.yp("missg",{vid:e?.videoId||"",cpn:e?.clientPlaybackNonce||""}))}j(){return this.W.W()}X(e,k=!1){var v=this.videoData?.MZ;if(e===1){if(!v||k)this.U=!1,this.A=this.videoData.clientPlaybackNonce;this.W.Y();this.w9&&this.Y()}else this.U=!0,this.w9&&gj(this)&&(e===2?this.W.U():e===3&&this.W.A())}Az(e){if(e){for(e=0;e<this.stills.length;e++)this.J.logVisibility(this.stills[e].element,
!0);this.X(1,!0)}else this.A=null,this.U=!1;this.Y()}ZP(){return this.w9&&gj(this)}};var AEg=class extends g.C{constructor(e){var k=e.G(),v=g.NP||g.qO?{style:"will-change: opacity"}:void 0,F=k.A,K=["ytp-videowall-still"];k.Y&&K.push("ytp-videowall-show-text");super({L:"a",M3:K,B:{href:"{{url}}",target:F?k.j:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},S:[{L:"div",Z:"ytp-videowall-still-image",B:{style:"{{background}}"}},{L:"span",Z:"ytp-videowall-still-info",B:{"aria-hidden":"true"},S:[{L:"span",Z:"ytp-videowall-still-info-bg",
S:[{L:"span",Z:"ytp-videowall-still-info-content",B:v,S:[{L:"span",Z:"ytp-videowall-still-info-title",Ui:"{{title}}"},{L:"span",Z:"ytp-videowall-still-info-author",Ui:"{{author_and_views}}"},{L:"span",Z:"ytp-videowall-still-info-live",Ui:"Live"},{L:"span",Z:"ytp-videowall-still-info-duration",Ui:"{{duration}}"}]}]}]},{L:"span",M3:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],B:{"aria-hidden":"true"},S:[{L:"span",Z:"ytp-videowall-still-listlabel-icon"},"Playlist",{L:"span",
Z:"ytp-videowall-still-listlabel-length",S:[" (",{L:"span",Ui:"{{playlist_length}}"},")"]}]},{L:"span",M3:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],B:{"aria-hidden":"true"},S:[{L:"span",Z:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{L:"span",Z:"ytp-videowall-still-listlabel-length",Ui:" (50+)"}]}]});this.suggestion=null;this.V=F;this.api=e;this.W=new g.Lv(this);g.w(this,this.W);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.W.N(e,"videodatachange",
this.onVideoDataChange);e.createServerVe(this.element,this);this.onVideoDataChange()}select(){this.api.GJ(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.ho||void 0)&&this.api.logClick(this.element)}onClick(e){if(g.TK(this.api.G())&&this.api.O("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);let k=this.suggestion.TG(),v={};g.aw(this.api,v);k=g.aE(k,v);g.XS(k,this.api,e)}else g.zc(e,this.api,
this.V,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(e){switch(e.keyCode){case 13:case 32:e.defaultPrevented||(this.select(),e.preventDefault())}}onVideoDataChange(){var e=this.api.getVideoData(),k=this.api.G();this.V=e.Vd?!1:k.A}};var CHp=class extends E1{constructor(e){super(e,"videowall-endscreen");this.J=e;this.A=0;this.stills=[];this.U=this.videoData=null;this.K=this.Vp=!1;this.Az=null;this.Y=new g.Lv(this);g.w(this,this.Y);this.X=new g.Y1(()=>{g.Qw(this.element,"ytp-show-tiles")},0);
g.w(this,this.X);var k=new g.C({L:"button",M3:["ytp-button","ytp-endscreen-previous"],B:{"aria-label":"Previous"},S:[g.I_()]});g.w(this,k);k.Kd(this.element);k.listen("click",this.Jz,this);this.table=new g.Ih({L:"div",Z:"ytp-endscreen-content"});g.w(this,this.table);this.table.Kd(this.element);k=new g.C({L:"button",M3:["ytp-button","ytp-endscreen-next"],B:{"aria-label":"Next"},S:[g.uU()]});g.w(this,k);k.Kd(this.element);k.listen("click",this.rX,this);e.getVideoData().IH?this.W=new dj(e):this.W=new hyg(e);
g.w(this,this.W);g.Au(this.player,this.W.element,4);e.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var e=this.player.getVideoData();e&&(this.videoData=e);this.V();this.Y.N(this.player,"appresize",this.V);this.Y.N(this.player,"onVideoAreaChange",this.V);this.Y.N(this.player,"videodatachange",this.onVideoDataChange);this.Y.N(this.player,"autonavchange",this.C);this.Y.N(this.player,"onAutonavCancelled",this.Hw);e=this.videoData.autonavState;e!==this.Az&&this.C(e,!1);this.Y.N(this.element,
"transitionend",this.iu)}destroy(){this.Y.V();g.rd(this.stills);this.stills=[];super.destroy();g.sI(this.element,"ytp-show-tiles");this.X.stop();this.Az=this.videoData.autonavState}D(){return this.videoData?.MZ||this.videoData?.autonavState!==1}show(){var e=this.w9;super.show();g.sI(this.element,"ytp-show-tiles");this.player.G().Y?g.wS(this.X):this.X.start();(this.K||this.U&&this.U!==this.videoData.clientPlaybackNonce)&&g.D_(this.player,!1);WC(this)?(nV(this),this.videoData.autonavState===2?this.player.getVisibilityState()===
3||fKg(this.player.l3())&&this.player.O("web_player_pip_logging_fix")?this.W.select(!0):this.W.U():this.videoData.autonavState===3&&this.W.A()):(g.D_(this.player,!0),nV(this));e!==this.w9&&this.player.logVisibility(this.element,!0)}hide(){var e=this.w9;super.hide();this.W.A();nV(this);e!==this.w9&&this.player.logVisibility(this.element,!1)}iu(e){e.target===this.element&&this.V()}V(){var e=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.YV()];if(e.length){g.Qw(this.element,
"ytp-endscreen-paginate");var k=this.J.A0(!0,this.J.isFullscreen()),v=g.BV(this.J);v&&(v=v.JW()?48:32,k.width-=v*2);var F=k.width/k.height,K=96/54,G=v=2,t=Math.max(k.width/96,2),V=Math.max(k.height/54,2),T=e.length;var H=T*4;for(H-=4;H>0&&(v<t||G<V);){var z=v/2,X=G/2,S=v<=t-2&&H>=X*4,R=G<=V-2&&H>=z*4;if((z+1)/X*K/F>F/(z/(X+1)*K)&&R)H-=z*4,G+=2;else if(S)H-=X*4,v+=2;else if(R)H-=z*4,G+=2;else break}K=!1;H>=12&&T*4-H<=6&&(G>=4||v>=4)&&(K=!0);H=v*96;t=G*54;F=H/t<F?k.height/t:k.width/H;F=Math.min(F,2);
H=Math.floor(Math.min(k.width,H*F));t=Math.floor(Math.min(k.height,t*F));k=this.table.element;k.ariaLive="polite";g.Sq(k,H,t);g.Cj(k,{marginLeft:`${H/-2}px`,marginTop:`${t/-2}px`});this.W.C(this.videoData.YV());this.W instanceof dj&&X2(this.W);g.jA(this.element,"ytp-endscreen-takeover",WC(this));nV(this);H+=4;t+=4;F=0;k.ariaBusy="true";for(V=0;V<v;V++)for(z=0;z<G;z++)if(S=F,R=0,K&&V>=v-2&&z>=G-2?R=1:z%2===0&&V%2===0&&(z<2&&V<2?z===0&&V===0&&(R=2):R=2),S=g.Bb(S+this.A,T),R!==0){X=this.stills[F];X||
(X=new AEg(this.player),this.stills[F]=X,k.appendChild(X.element));var J=Math.floor(t*z/G);let Z=Math.floor(H*V/v),B=Math.floor(t*(z+R)/G)-J-4,l=Math.floor(H*(V+R)/v)-Z-4;g.GC(X.element,Z,J);g.Sq(X.element,l,B);g.Cj(X.element,"transitionDelay",(z+V)/20+"s");g.jA(X.element,"ytp-videowall-still-mini",R===1);g.jA(X.element,"ytp-videowall-still-large",R>2);R=Math.max(l,B);g.jA(X.element,"ytp-videowall-still-round-large",R>=256);g.jA(X.element,"ytp-videowall-still-round-medium",R>96&&R<256);g.jA(X.element,
"ytp-videowall-still-round-small",R<=96);S=e[S];X.suggestion!==S&&(X.suggestion=S,R=X.api.G(),J=g.rS(X.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.b2(X,S,J),g.TK(R)&&!X.api.O("web_player_log_click_before_generating_ve_conversion_params")&&(R=S.TG(),J={},g.rc(X.api,"addEmbedsConversionTrackingParams",[J]),R=g.aE(R,J),X.updateValue("url",R)),(S=(S=S.sessionData)&&S.itct)&&X.api.setTrackingParams(X.element,S));F++}k.ariaBusy="false";g.jA(this.element,"ytp-endscreen-paginate",
F<T);for(e=this.stills.length-1;e>=F;e--)v=this.stills[e],g.dV(v.element),g.x_(v);this.stills.length=F}}onVideoDataChange(){var e=this.player.getVideoData({playerType:1});this.videoData!==e&&(e?.YV()?(this.A=0,this.videoData=e,this.V()):this.player.yp("missg",{vid:e?.videoId||"",cpn:e?.clientPlaybackNonce||""}))}rX(){this.A+=this.stills.length;this.V()}Jz(){this.A-=this.stills.length;this.V()}j(){return this.W.W()}C(e,k=!1){var v=this.videoData?.MZ;if(e===1){if(!v||k)this.K=!1,this.U=this.videoData.clientPlaybackNonce;
this.W.Y();this.w9&&this.V()}else this.K=!0,this.w9&&WC(this)&&(e===2?this.W.U():e===3&&this.W.A())}Hw(e){if(e){for(e=0;e<this.stills.length;e++)this.J.logVisibility(this.stills[e].element,!0);this.C(1,!0)}else this.U=null,this.K=!1;this.V()}ZP(){return this.w9&&WC(this)}};var oon=class extends g.C{constructor(e){super({L:"button",M3:["ytp-watch-on-youtube-button","ytp-button"],Ui:"{{content}}"});this.J=e;this.buttonType=this.buttonType=1;this.W();this.buttonType===2&&g.Qw(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.W);this.xv(!0)}W(){switch(this.buttonType){case 1:var e="Watch again on YouTube";var k=156915;break;case 2:e="Continue watching on YouTube";k=156942;break;default:e="Continue watching on YouTube",
k=156942}this.update({content:e});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,k)}onClick(e){this.J.O("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.XS(this.getVideoUrl(),this.J,e);this.J.O("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)}getVideoUrl(){var e=!0;switch(this.buttonType){case 1:e=!0;break;case 2:e=!1}e=this.J.getVideoUrl(e,!1,!1,!0);var k=
this.J.G();if(g.TK(k)){let v={};g.TK(k)&&g.rc(this.J,"addEmbedsConversionTrackingParams",[v]);e=g.aE(e,v)}return e}logVisibility(){this.J.logVisibility(this.element,this.w9&&this.YV)}show(){super.show();this.logVisibility()}hide(){super.hide();this.logVisibility()}wV(e){super.wV(e);this.logVisibility()}};var bbS=class extends E1{constructor(e){super(e,"watch-again-on-youtube-endscreen");this.watchButton=new oon(e);g.w(this,this.watchButton);this.watchButton.Kd(this.element);g.N3g(e)&&(this.W=new g.fZL(e),g.w(this,this.W),this.V=new g.C({L:"div",M3:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],B:{tabIndex:"-1"},S:[this.W]}),g.w(this,this.V),this.W.Kd(this.V.element),this.V.Kd(this.element));e.createClientVe(this.element,this,156914);this.hide()}hasSuggestions(){return this.W?.hasSuggestions()}show(){if(this.player.getPlayerState()!==
3){super.show();let k=this.V;if(k){var e=this.W.hasSuggestions();g.jA(this.element,"ytp-shorts-branded-ui",e);e?k.show():k.hide()}g.BV(this.player)?.m$(!0);this.player.logVisibility(this.element,!0);this.watchButton.wV(!0)}}hide(){super.hide();g.BV(this.player)?.m$(!1);this.player.logVisibility(this.element,!1);this.watchButton.wV(!1)}};g.Sp("endscreen",class extends g.u1{constructor(e){super(e);this.endScreen=null;this.W=this.V=!1;this.listeners=new g.Lv(this);g.w(this,this.listeners);var k=e.G();e.isEmbedsShortsMode()?this.endScreen=new bbS(e):Ma7(e)?(this.V=!0,PHK(this),k.O("delhi_modern_endscreen")?this.endScreen=new ULV(e):this.endScreen=new CHp(e)):this.endScreen=new E1(e);g.w(this,this.endScreen);g.Au(e,this.endScreen.element,4);aKJ(this);this.listeners.N(e,"videodatachange",this.onVideoDataChange,this);this.listeners.N(e,
g.Ds("endscreen"),v=>{this.onCueRangeEnter(v)});
this.listeners.N(e,g.yG("endscreen"),v=>{this.onCueRangeExit(v)})}h_(){var e=this.player.getVideoData(),k=e.mutedAutoplay&&(e.limitedPlaybackDurationInSeconds>0||e.endSeconds>0||e.mutedAutoplayDurationMode!==2);
if(this.player.isEmbedsShortsMode()&&!k)return!0;var v=!(!e?.YV()&&!e?.suggestions?.length);v=!Ma7(this.player)||v;var F=e.f5,K=this.player.B_();return(v||!!e?.MZ)&&!F&&!K&&!k}ZP(){return this.endScreen.ZP()}kC(){return this.ZP()?this.endScreen.j():!1}Qp(){this.player.Ku("endscreen");super.Qp()}load(){{let v=this.player.getVideoData(),F=v.transitionEndpointAtEndOfStream;if(F&&F.videoId){var e=this.player.X5().Lm.get("heartbeat");var k=v.YV();!k||F.videoId!==k.videoId||v.Pf?(this.player.GJ(F.videoId,
void 0,void 0,!0,!0,F),e&&e.gF("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),e=!0):e=!1}else e=!1}e||(super.load(),this.endScreen.show())}unload(){super.unload();this.endScreen.hide();this.endScreen.destroy()}onCueRangeEnter(e){this.h_()&&(this.endScreen.created||this.endScreen.create(),e.getId()==="load"&&this.load())}onCueRangeExit(e){e.getId()==="load"&&this.loaded&&this.unload()}onVideoDataChange(){aKJ(this);this.V&&PHK(this)&&
(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.endScreen=new CHp(this.player),g.w(this,this.endScreen),g.Au(this.player,this.endScreen.element,4))}});})(_yt_player);
