(function(g){var window=this;'use strict';var JL=function(e,k){if(!Number.isFinite(e))return String(e);e=String(e);var v=e.indexOf(".");v===-1&&(v=e.length);var F=e[0]==="-"?"-":"";F&&(e=e.substring(1));k="0".repeat(Math.max(0,k-v));return F+k+e},LV=function(e){typeof e==="number"?(this.date=e$n(e,0,1),pV(this,1)):g.$Q(e)?(this.date=e$n(e.getFullYear(),e.getMonth(),e.getDate()),pV(this,e.getDate())):(this.date=new Date(g.ih()),e=this.date.getDate(),this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),
pV(this,e))},e$n=function(e,k,v){k=new Date(e,k,v);
e>=0&&e<100&&k.setFullYear(k.getFullYear()-1900);return k},pV=function(e,k){e.getDate()!=k&&e.date.setUTCHours(e.date.getUTCHours()+(e.getDate()<k?1:-1))},$x=function(e){if(e.toggleButtonRenderer){var k=e.toggleButtonRenderer;
if(k.isToggled){var v=k.toggledText?g.sl(k.toggledText):"";e.update({text:v,icon:kBp(k.toggledIcon)})}else v=k.defaultText?g.sl(k.defaultText):"",e.update({text:v,icon:kBp(k.defaultIcon)});e.show()}else e.hide()},vk7=function(e,k){!e.toggleButtonRenderer&&k&&k.toggleButtonRenderer?e.toggleButtonRenderer=k.toggleButtonRenderer:k&&k.toggleButtonRenderer||(e.toggleButtonRenderer=null);
$x(e)},kBp=function(e){if(!e)return null;
switch(e.iconType){case "NOTIFICATIONS":return{L:"svg",B:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},S:[{L:"path",B:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]};case "NOTIFICATIONS_NONE":return{L:"svg",B:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},S:[{L:"path",B:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]};
case "NOTIFICATIONS_ACTIVE":return g.DLH();default:return null}},tFn=function(e,k){var v=g.y(k,FNn),F=g.y(k,KNy);
if(k&&(v||F)){if(v){var K=v;var G="notification/add_upcoming_event_reminder"}else F&&(K=F,G="notification/remove_upcoming_event_reminder");G&&K&&K.params&&GBL(e,G,K.params)}},GBL=function(e,k,v){var F=e.J.G();
e.W||(e.W=new g.IX(F.Wa));var K={context:g.al(e.W.config_||g.Py())};g.MV()&&(K.context.clientScreenNonce=g.MV());K.params=v;v={timeout:5E3,onError:()=>{VFL(e)},
onTimeout:()=>{VFL(e)}};
F.o1().W.hz(g.tjQ)&&(v.onSuccess=G=>{if(G=G.actions)for(let t of G)g.iM(e.J,"innertubeCommand",t)});
g.LZ(e.W,k,K,v)},VFL=function(e){e.toggleButtonRenderer&&(e.toggleButtonRenderer.isToggled=!e.toggleButtonRenderer.isToggled,$x(e))},O1=function(e,k,v){if(k){var F=k.subtitleText!=null?g.sl(k.subtitleText):"";
v=v?v:k.mainText!=null?g.sl(k.mainText):"";e.update({mainText:v,subtitleText:F,label:k.mainText?.accessibility?.accessibilityData?.label??v});g.jA(e.element,"ytp-offline-slate-single-text-line",!F);g.jA(e.Y,"ytp-offline-slate-bar-hidden",!v&&!F)}},T_x=function(e){try{let k=JSON.parse(e);
return k!=null?k:void 0}catch(k){}},gku=async function(e){var k=e.player.G(),v=e.getVideoData();
qt(e)&&(HIL(e)?z$L(e,k,v):(XIS(e),await Sb4(e,k,v)))},XIS=function(e){var k=e.getVideoData();
if(k.KN)if(k.O("use_rta_for_player"))e.attestationResponse=R$x(e);else{let G=new g.Zng(k);if(g.TT.isInitialized()||e.sequenceNumber>=3){k=Promise;var v=k.resolve;let t=null;if(G.videoData.nz){var F=g.NrK(G);if(F){t={};let V={};F=F.split("&");for(K of F)F=K.split("="),F.length===2&&(V[F[0]]=F[1]);var K=V;K.r1a&&(t.webResponse=K.r1a);K.r1c&&(t.error=WNJ[Number(K.r1c)]);t.challenge=G.videoData.nz}}e.attestationResponse=v.call(k,t||void 0)}}},Eky=function(e){var k=e.getVideoData(),v=e.player.G();
if(k.isLivePlayback)if(g.o8(v.D)){e.A=!0;e.X=!0;if(!g.N2(v)||g.wl(v))e.offlineSlate=new nkU(e.player),g.w(e,e.offlineSlate),g.Au(e.player,e.offlineSlate.element,4);(k=k.getPlayerResponse())&&k.playabilityStatus&&(e.W=k.playabilityStatus);e.W?.status!=="UNPLAYABLE"&&(e.W?(k=dXu(void 0,e.W.liveStreamability&&e.W.liveStreamability.liveStreamabilityRenderer))?Yx(e,k):Yx(e,7500):Yx(e,1E3))}else e.player.bl("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");else g.bh(k.gr,"heartbeat")&&
e.player.IE("heartbeat",e.getPlayerType())},LNx=function(e,k,v){var F=v.liveStreamability&&v.liveStreamability.liveStreamabilityRenderer,K=!(!F||!(F.switchStreamsImmediately||F.transitionTiming&&F.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
k=dXu(k,F);var G=e.getVideoData(),t=e.player.getPlayerStateObject(e.getPlayerType()),V=t.isPlaying()&&!g.tu(G)&&!e.player.isAtLiveHead(e.getPlayerType());if(G.G().tq()){var T=e.player.F7()?.Vh()||{};T.status=v.status||"";T.dvr=`${+V}`;T["switch"]=`${+K}`;T.ended=`${+!(!F||!F.displayEndscreen)}`;e.player.yp("heartbeat",T)}T=F&&F.broadcastId;var H=e.W&&e.W.liveStreamability&&e.W.liveStreamability.liveStreamabilityRenderer&&e.W.liveStreamability.liveStreamabilityRenderer.broadcastId,z=T!==H&&T!=null;
z&&e.player.yp("lbidh",{broadcastId:T},!0);if(g.N2(G.G())&&F&&F.streamTransitionEndpoint){var X=g.y(F.streamTransitionEndpoint,g.gH)?.commands||[];for(var S of X)if(g.y(S,g.mA)?.signal==="RELOAD_PLAYER"){e.player.bl("qoe.restart",0,void 0,"sa.reload","7");break}}S=e.player.O("always_cache_redirect_endpoint");if(V&&!K&&!S)return k;X=F&&F.streamTransitionEndpoint&&g.y(F.streamTransitionEndpoint,g.pw);if((F&&F.transitionTiming)==="STREAM_TRANSITION_TIMING_AT_STREAM_END")e.getVideoData().transitionEndpointAtEndOfStream=
X;else{if(X&&JpJ(e,X,v))return k;S&&!X&&e.getVideoData().transitionEndpointAtEndOfStream&&(e.getVideoData().transitionEndpointAtEndOfStream=void 0)}if(V&&!K&&S)return k;if(v.status.toUpperCase()==="OK"){if(!g.Ep(G)||z)return F={video_id:G.videoId},G.yJ&&(F.is_live_destination="1"),F.disable_watch_next=!0,F.raw_watch_next_response=G.getWatchNextResponse(),F.autonav_state=G.autonavState,F.oauth_token=G.oauthToken,F.Pr=G.Pr,G.IM&&(F.vss_credentials_token=G.IM,F.vss_credentials_token_type=G.Tk),G.Vp&&
(F.vvt=G.Vp),K=void 0,g.Ep(G)?z&&(K=new pIV("broadcastIdChanged",`${H},${T}`),e.gF("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",v)):(T&&(K=new pIV("formatsReceived",`${T}`)),e.gF("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",v)),z&&e.player.yp("lbidr",{broadcastId:T}),e.player.loadVideoByPlayerVars(F,void 0,void 0,void 0,K),k;e.player.IE("heartbeat",e.getPlayerType())}F&&F.displayEndscreen&&(e.offlineSlate?
(e=e.offlineSlate,e.K=!0,e.w9&&e.api.hC()):t.isBuffering()&&(G=e.player.F7()?.Vh()||{},e.player.yp("hbse",G,!0),e.player.hC(!0,"h"),g.iM(e.player,"onLiveMediaEnded",v)));return k},$X4=function(e){var k=e.getVideoData();
!k.O("use_rta_for_player")&&k.KN&&(k=k.botguardData)&&g.XW(k,e.player.G())},ZT=function(e){e.D=0;
e.V.stop();e.U=!1;e.sequenceNumber=0},R$x=async function(e){if(await g.AtK())return e=e.getVideoData(),g.UZg({cpn:e.clientPlaybackNonce,
encryptedVideoId:e.videoId||""},1500);if(e.sequenceNumber>=3)return{error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}},wj=function(e){var k=e.getVideoData();
return e.player.G().experiments.o1().W.hz(g.z_)||k.O("html5_use_server_init_heartbeat_delay")?e.heartbeatParams?.interval?e.heartbeatParams.interval*1E3:k.fD:2E3},Yx=function(e,k){if(!e.V.isActive()&&e.X){var v=e.getVideoData();
if(iV(e)||v.isLivePlayback)k===void 0&&(k=e.U?e.A?7500:e.heartbeatParams?.interval?e.heartbeatParams.interval*1E3:e.getVideoData().fD||6E4:1E3),e.V.start(k)}},HIL=function(e){var k=e.getVideoData();
if(!g.vV(e.getVideoData())||k.o2)return!1;if(k.U){e=k.U.flavor==="playready";let v=k.U.flavor==="widevine"&&k.O("html5_innertube_heartbeats_for_widevine");k=g.y_(k.U)&&k.O("html5_innertube_heartbeats_for_fairplay");return!(e||v||k)}return!0},iV=function(e){if(HIL(e))return!!e.heartbeatParams;
var k=e.getVideoData();return!g.vV(e.getVideoData())||k.zw||k.Ym?!!k.heartbeatToken:!1},YbV=function(e,k,v){k.YG&&(v=g.aE(v,{internalipoverride:k.YG}));
var F={cpn:k.clientPlaybackNonce};k.contextParams&&(F.context_params=k.contextParams);k.N3&&(F.kpt=k.N3);v=g.aE(v,F);g.wa(v,{format:"RAW",method:"GET",timeout:3E4,onSuccess:K=>{if(!e.V.isActive()&&qt(e)){e.K.reset();e.sequenceNumber++;K=K.responseText;var G=T_x(K);if(G){g.iM(e.player,"onHeartbeat",G);var t=G.status==="ok"?G.stop_heartbeat?2:0:G.status==="stop"?1:G.status==="live_stream_offline"?0:-1}else t=(t=K.match(OIK))?t[1]==="0"?0:1:-1;qbx(e,void 0,G,K,t)}},
onError:K=>{qt(e)&&Nt(e,!0,`net-${K.status}`)},
onTimeout:()=>{qt(e)&&Nt(e,!0,"timeout")},
withCredentials:!0})},qt=function(e){var k=e.getVideoData();
return e.player.getPresentingPlayerType()===3||!e.player.G().experiments.o1().W.hz(g.fyQ)&&e.player.getPlayerStateObject(e.getPlayerType()).W(4)?!1:iV(e)||k.isLivePlayback?!0:(ZT(e),!1)},z$L=function(e,k,v){if(e.heartbeatParams?.url){var F=g.aE(e.heartbeatParams.url,{request_id:g.OJQ()});
v.Vp&&(F=g.aE(F,{vvt:v.Vp}),v.mdxEnvironment&&(F=g.aE(F,{mdx_environment:v.mdxEnvironment})));g.xi(k,v.oauthToken).then(K=>{K&&(F=g.aE(F,{access_token:K}));YbV(e,v,F)})}},Sb4=async function(e,k,v){var F={videoId:v.videoId,
sequenceNumber:e.sequenceNumber,heartbeatServerData:e.Az??v.heartbeatServerData};e.C=e.attestationResponse;v.KN&&(F.attestationResponse=await e.C);var K=g.qm(v),G=K.client??{};G.utcOffsetMinutes=e.utcOffsetMinutes;F.context=K;F.cpn=v.clientPlaybackNonce;if(K=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)G.timeZone=K;G={heartbeatChecks:[]};if(K=v.getPlayerResponse())v.heartbeatToken&&(F.heartbeatToken=v.heartbeatToken),(K=K.playabilityStatus)&&(K=K.liveStreamability)&&
K.liveStreamabilityRenderer&&G.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");v.heartbeatToken&&G.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.wl(k)){G.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");var t=ZIS(e);K={};t!==null&&(K.clientPlayerPositionUtcMillis=t);t=e.player.X5()?.Hq()?.YC()||0;t>0&&(K.freePreviewWatchedDuration={seconds:`${t}`});G.unpluggedParams=K}F.heartbeatRequestParams=G;v.isLivePlayback?(G=ZIS(e),G!==null&&(F.playbackState||(F.playbackState={}),
F.playbackState.playbackPosition={utcTimeMillis:G})):k.O("enable_heartbeat_vod_playback_position")&&(G=wI4(e),G!==null&&(F.playbackState||(F.playbackState={}),F.playbackState.playbackPosition={streamTimeMillis:G}));e.player.publish("heartbeatRequest",F);var V={timeout:3E4,onSuccess:T=>{if(!e.V.isActive()&&qt(e)){var H=e.getVideoData(),z=H.KN&&e.C==null;H.KN=!!T.heartbeatAttestationConfig?.requiresAttestation||z;z=T.playabilityStatus;var X=JSON.stringify(z)||"{}";T.authenticationMismatch&&e.player.yp("authshear",
{});var S=-1;var R=T.playabilityStatus;R&&(g.iM(e.player,"onHeartbeat",R),R.status==="OK"?S=T.stopHeartbeat?2:0:R.status==="UNPLAYABLE"?S=1:R.status==="LIVE_STREAM_OFFLINE"&&(S=0));e.sequenceNumber&&S===-1||e.K.reset();e.sequenceNumber++;T.heartbeatServerData&&(e.Az=T.heartbeatServerData);H.U8=T;(R=T.playerCueRangeSet)&&g.Lw(H,R);T.playerCueRanges&&T.playerCueRanges.length>0&&(H.cueRanges=T.playerCueRanges);T.progressBarConfig?.progressBarStartPosition&&T.progressBarConfig?.progressBarEndPosition&&
(H.progressBarStartPosition=T.progressBarConfig.progressBarStartPosition,H.progressBarEndPosition=T.progressBarConfig.progressBarEndPosition);H.compositeLiveIngestionOffsetToken=T.compositeLiveIngestionOffsetToken;T.compositeLiveStatusToken!==H.compositeLiveStatusToken&&(H.compositeLiveStatusToken=T.compositeLiveStatusToken);H.heartbeatLoggingToken=T.heartbeatLoggingToken;H.publish("dataupdated");qbx(e,T,z,X,S)}},
onError:T=>{qt(e)&&Nt(e,!0,`net-${T.status}`)},
onTimeout:()=>{qt(e)&&Nt(e,!0,"timeout")}};
g.xi(k,v.K()).then(T=>{T&&(V.mp=`Bearer ${T}`);g.LZ(e.Vp,"player/heartbeat",F,V)})},ZIS=function(e){return(e=e.player.getProgressState(e.getPlayerType()).ingestionTime)&&isFinite(e)?`${Math.floor(e*1E3)}`:null},wI4=function(e){return(e=e.player.getCurrentTime({playerType:e.getPlayerType()}))&&isFinite(e)?`${Math.floor(e*1E3)}`:null},qbx=function(e,k,v,F,K){K===-1?(v=`decode ${g.PF(F,3)}`,Nt(e,!1,v)):K===2?(ZT(e),e.U=!0):(e.D=0,e.V.stop(),K===1?(e.U=!1,v&&v.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&
e.player.pE(!0),K=`pe.${v?.errorCode};ps.${v?.status}`,e.player.bl("heartbeat.stop",2,e.Ea(F),K,void 0,v?.errorScreen?.playerErrorMessageRenderer),g.u3("heartbeatActionPlayerHalted",iIy(v)),k?.videoTransitionEndpoint&&v&&(k=k.videoTransitionEndpoint,(F=g.y(k,g.pw))&&JpJ(e,F,v,{itct:k?.clickTrackingParams}))):(e.U=!0,F=0,e.A&&v&&(F=LNx(e,k,v),e.player.publish("livestatedata",v)),F?Yx(e,F):Yx(e)))},Nt=function(e,k,v){if(!e.V.isActive()){e.V.stop();
e.D++;var F=k?"heartbeat.net":"heartbeat.servererror";{let G=e.getVideoData();if(G.vF||k&&!g.vV(e.getVideoData())&&!iV(e)&&G.isLivePlayback)var K=!1;else e.heartbeatParams?.retries?K=e.heartbeatParams.retries:K=G.h3||5,K=e.D>=K}K?(g.u3("heartbeatActionPlayerHalted",k?{enforcedPolicyToHaltOnNetworkFailure:!0}:iIy()),(k=e.getVideoData())&&k.isLivePlayback?e.player.bl(F,1,"Video playback interrupted. Please try again.",v):e.player.bl(F,1,"Sorry, there was an error licensing this video.",v)):(Yx(e,e.K.getValue()),
g.Q$(e.K))}},iIy=function(e){var k={enforcedPolicyToHaltOnNetworkFailure:!1};
e&&(k.serializedServerContext=e.additionalLoggingData);return k},dXu=function(e,k){return(e=Number(e?.pollDelayMs))?e:(k=Number(k?.pollDelayMs))?k:0},JpJ=function(e,k,v,F){var K=k&&k.videoId;
return K?(e.player.GJ(K,{autonav:"1",...(F||{})},void 0,!0,!0,k,e.getVideoData().K()),e.gF("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",v),!0):!1},N_p={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},xx=N_p;xx=N_p;
var WNJ=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],xXx={300:"STREAMING_DEVICES_QUOTA_PER_24H_EXCEEDED",301:"ALREADY_PINNED_ON_A_DEVICE",303:"STOPPED_BY_ANOTHER_PLAYBACK",304:"TOO_MANY_STREAMS_PER_USER",305:"TOO_MANY_STREAMS_PER_ENTITLEMENT",400:"VIDEO_NOT_FOUND",401:"GEO_FAILURE",402:"STREAMING_NOT_ALLOWED",403:"UNSUPPORTED_DEVICE",405:"VIDEO_FORBIDDEN",500:"PURCHASE_NOT_FOUND",
501:"RENTAL_EXPIRED",502:"PURCHASE_REFUNDED",5E3:"BAD_REQUEST",5001:"CGI_PARAMS_MISSING",5002:"CGI_PARAMS_MALFORMED",5100:"AUTHENTICATION_MISSING",5101:"AUTHENTICATION_MALFORMED",5102:"AUTHENTICATION_EXPIRED",5200:"CAST_TOKEN_MALFORMED",5201:"CAST_TOKEN_EXPIRED",5202:"CAST_TOKEN_FAILED",5203:"CAST_SESSION_VIDEO_MISMATCHED",5204:"CAST_SESSION_DEVICE_MISMATCHED",6E3:"INVALID_DRM_MESSAGE",7E3:"SERVER_ERROR",8E3:"RETRYABLE_ERROR"};g.Y=LV.prototype;g.Y.ut=xx.FIRSTDAYOFWEEK;g.Y.aT=xx.FIRSTWEEKCUTOFFDAY;
g.Y.clone=function(){var e=new LV(this.date);e.ut=this.ut;e.aT=this.aT;return e};
g.Y.getFullYear=function(){return this.date.getFullYear()};
g.Y.getYear=function(){return this.getFullYear()};
g.Y.getMonth=function(){return this.date.getMonth()};
g.Y.getDate=function(){return this.date.getDate()};
g.Y.getTime=function(){return this.date.getTime()};
g.Y.getDay=function(){return this.date.getDay()};
g.Y.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.Y.getUTCMonth=function(){return this.date.getUTCMonth()};
g.Y.getUTCDate=function(){return this.date.getUTCDate()};
g.Y.getUTCDay=function(){return this.date.getDay()};
g.Y.getUTCHours=function(){return this.date.getUTCHours()};
g.Y.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.Y.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.Y.set=function(e){this.date=new Date(e.getFullYear(),e.getMonth(),e.getDate())};
g.Y.setFullYear=function(e){this.date.setFullYear(e)};
g.Y.setYear=function(e){this.setFullYear(e)};
g.Y.setMonth=function(e){this.date.setMonth(e)};
g.Y.setDate=function(e){this.date.setDate(e)};
g.Y.setTime=function(e){this.date.setTime(e)};
g.Y.setUTCFullYear=function(e){this.date.setUTCFullYear(e)};
g.Y.setUTCMonth=function(e){this.date.setUTCMonth(e)};
g.Y.setUTCDate=function(e){this.date.setUTCDate(e)};
g.Y.add=function(e){if(e.years||e.months){var k=this.getMonth()+e.months+e.years*12,v=this.getYear()+Math.floor(k/12);k%=12;k<0&&(k+=12);a:{switch(k){case 1:var F=v%4!=0||v%100==0&&v%400!=0?28:29;break a;case 5:case 8:case 10:case 3:F=30;break a}F=31}F=Math.min(F,this.getDate());this.setDate(1);this.setFullYear(v);this.setMonth(k);this.setDate(F)}e.days&&(v=this.getYear(),k=v>=0&&v<=99?-1900:0,e=new Date((new Date(v,this.getMonth(),this.getDate(),12)).getTime()+e.days*864E5),this.setDate(1),this.setFullYear(e.getFullYear()+
k),this.setMonth(e.getMonth()),this.setDate(e.getDate()),pV(this,e.getDate()))};
g.Y.equals=function(e){return!(!e||this.getYear()!=e.getYear()||this.getMonth()!=e.getMonth()||this.getDate()!=e.getDate())};
g.Y.toString=function(){var e=this.getFullYear(),k=e<0?"-":e>=1E4?"+":"";return[k+JL(Math.abs(e),k?6:4),JL(this.getMonth()+1,2),JL(this.getDate(),2)].join("")+""};
g.Y.valueOf=function(){return this.date.valueOf()};var FNn=new g.b("addUpcomingEventReminderEndpoint");var KNy=new g.b("removeUpcomingEventReminderEndpoint");var rpy=class extends g.C{constructor(e){super({L:"div",S:[{L:"button",M3:["ytp-offline-slate-button","ytp-button"],S:[{L:"div",Z:"ytp-offline-slate-button-icon",Ui:"{{icon}}"},{L:"div",Z:"ytp-offline-slate-button-text",Ui:"{{text}}"}]}]});this.J=e;this.W=this.toggleButtonRenderer=null;(this.V=this.wX("ytp-offline-slate-button"))&&this.N(this.V,"click",this.Y);this.hide()}Y(){if(this.toggleButtonRenderer){let e=this.toggleButtonRenderer;e.isToggled?tFn(this,e.toggledServiceEndpoint):tFn(this,e.defaultServiceEndpoint);
e.isToggled=!e.isToggled;$x(this)}}};var nkU=class extends g.C{constructor(e){super({L:"div",Z:"ytp-offline-slate",S:[{L:"div",Z:"ytp-offline-slate-background"},{L:"div",Z:"ytp-offline-slate-bar",S:[{L:"span",Z:"ytp-offline-slate-icon",S:[{L:"svg",B:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},S:[{L:"path",B:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{L:"circle",B:{cx:"12",cy:"12",r:"3"}}]}]},{L:"span",Z:"ytp-offline-slate-messages",S:[{L:"div",Z:"ytp-offline-slate-main-text",B:{"aria-label":"{{label}}"},Ui:"{{mainText}}"},{L:"div",Z:"ytp-offline-slate-subtitle-text",Ui:"{{subtitleText}}"}]},{L:"span",Z:"ytp-offline-slate-buttons"}]},{L:"button",M3:["ytp-offline-slate-close-button","ytp-button"],S:[g.uU()]},{L:"button",M3:["ytp-offline-slate-open-button","ytp-button"],S:[g.I_()]}]});this.api=e;this.W=this.V=null;this.background=this.wX("ytp-offline-slate-background");
this.Y=this.wX("ytp-offline-slate-bar");this.U=new g.Y1(()=>{g.Qw(this.Y,"ytp-offline-slate-bar-fade")},15E3);
this.K=!1;this.A=new g.Y1(()=>{g.Qw(this.element,"ytp-offline-slate-collapsed")},15E3);
g.w(this,this.A);g.w(this,this.U);this.countdownTimer=new g.Y1(this.X,1E3,this);this.N(e,"presentingplayerstatechange",this.D);this.N(e,"livestatedata",this.Gn);this.N(this.wX("ytp-offline-slate-close-button"),"click",()=>{g.Qw(this.element,"ytp-offline-slate-collapsed")});
this.N(this.wX("ytp-offline-slate-open-button"),"click",()=>{g.sI(this.element,"ytp-offline-slate-collapsed")});
this.hide();e=this.getVideoData();e.getPlayerResponse()&&(e=e.getPlayerResponse().playabilityStatus)&&this.Gn(e);e=this.api.getPresentingPlayerType()===8&&!this.getVideoData().lR;var k=this.api.getPresentingPlayerType()===8;g.jA(this.element,"ytp-offline-slate-premiere-trailer",e);g.jA(this.element,"ytp-offline-slate-hide-background",k)}getPlayerType(){if(this.api.getPresentingPlayerType()===8)return 1}getVideoData(){return this.api.getVideoData({playerType:this.getPlayerType()})}Gn(e){var k=e?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate;
if(k){this.V=e;k=k.liveStreamOfflineSlateRenderer;k.canShowCountdown?this.X():O1(this,k);var v=e?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate?.liveStreamOfflineSlateRenderer?.thumbnail;if(v){let F=0,K=null;v=v.thumbnails;for(let G=0;G<v.length;G++)v[G].width>F&&(F=v[G].width||0,K=v[G].url);K&&(this.background.style.backgroundImage=`url(${K})`)}else this.background.style.backgroundImage="";k.actionButtons?(this.W||(this.W=new rpy(this.api),this.W.Kd(this.wX("ytp-offline-slate-buttons")),
g.w(this,this.W)),vk7(this.W,k.actionButtons&&k.actionButtons[0])):this.W&&vk7(this.W,null);this.V=e}else this.V=null;this.D()}D(e){if(this.api.getPresentingPlayerType()===8)var k=!0;else{var v=this.api.getPlayerStateObject(),F=this.getVideoData();k=F.isLivePlayback&&(v.isBuffering()||v.W(2)||v.W(64));var K=F.autonavState===2&&v.W(2);v=v.isPlaying()&&!g.tu(F)&&!this.api.isAtLiveHead(void 0,!0);k=k&&!v&&!K}k&&this.V?this.w9?e?.nR(2)&&!this.getVideoData().lR&&(g.sI(this.element,"ytp-offline-slate-collapsed"),
this.A.stop(),g.sI(this.Y,"ytp-offline-slate-bar-fade"),this.U.start()):(this.show(),this.A.start(),this.api.publish("offlineslatestatechange"),this.K&&this.api.hC()):this.w9&&(this.hide(),this.api.publish("offlineslatestatechange"))}X(){var e=this.V?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate?.liveStreamOfflineSlateRenderer;if(e){var k=Math.floor(g.ih()/1E3),v=e.canShowCountdown&&Number(e.scheduledStartTime);!v||v<=k?(O1(this,e),this.countdownTimer.stop()):(O1(this,e,g.RV(v-k)),g.Zo(this.countdownTimer))}}Qp(){this.countdownTimer.dispose();
this.countdownTimer=null;super.Qp()}};var pIV=class{constructor(e,k){var v=(0,g.M)();this.trigger=e;this.W=k;this.Y=v}V(e){return this.trigger&&e.trigger?this.trigger===e.trigger&&this.W===e.W:!1}isExpired(){return(0,g.M)()-this.Y>6E4}toString(){return`heartbeat:${this.trigger}:${this.W}`}};var OIK=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.Sp("heartbeat",class extends g.u1{constructor(e){super(e);this.X=!1;this.D=0;this.U=!1;this.V=new g.Y1(()=>{gku(this)},0);
this.W=this.heartbeatParams=null;this.A=!1;this.K=new g.r_(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.Vp=new g.IX(void 0);this.attestationResponse=Promise.resolve(void 0);this.C=Promise.resolve(void 0);this.utcOffsetMinutes=-(new LV).getTimezoneOffset();this.Y=new g.Lv(this);g.w(this,this.V);g.w(this,this.Y);XIS(this);Eky(this);this.Y.N(e,"heartbeatparams",this.Qn);this.Y.N(e,"presentingplayerstatechange",this.YV);this.Y.N(e,"videoplayerreset",this.j);this.Y.N(e,g.Ds("heartbeat"),
this.onCueRangeEnter);this.A&&this.W&&LNx(this,void 0,this.W);var k=new g.tO(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),v=new g.tO(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});e.j3([k,v]);$X4(this)}Qp(){ZT(this);this.player.Ku("heartbeat");super.Qp()}onCueRangeEnter(){var e=this.getVideoData();this.X=!0;this.player.G().experiments.o1().W.hz(g.z_)||e.O("html5_use_server_init_heartbeat_delay")?(e=wj(this),isNaN(e)||Yx(this,e)):Yx(this,2E3)}Qn(e){var k=
this.getVideoData();this.heartbeatParams=e;this.player.G().experiments.o1().W.hz(g.z_)||k.O("html5_use_server_init_heartbeat_delay")?(e=wj(this),isNaN(e)||Yx(this,e)):Yx(this,2E3)}YV(e){if(this.player.getPresentingPlayerType()!==8&&this.W?.status!=="UNPLAYABLE")if(e.state.W(2)||e.state.W(64))ZT(this),this.A&&(this.X=!0,Yx(this,1E3));else{let k=this.player.G().experiments.o1().W.hz(g.fyQ);(e.state.W(1)||e.state.W(8)||k&&e.state.W(4))&&Yx(this,wj(this))}}j(){this.player.getPresentingPlayerType()!==
3&&Yx(this,wj(this))}getPlayerType(){if(this.player.getPresentingPlayerType()===8)return 1}getVideoData(){return this.player.getVideoData({playerType:this.getPlayerType()})}fT(e){switch(e){case 4:case 3:return!1}return!0}gF(e,k,v){e={trigger:e,reason:k};v&&(e.serializedServerContext=v.additionalLoggingData);g.u3("heartbeatActionPlayerTransitioned",e)}Ea(e){var k="LICENSE",v=T_x(e);if(v)return v.reason||g.rp[k]||"";if(e=e.match(OIK))if(e=Number(e[1]))k=(k=xXx[e.toString()])?k:"LICENSE";return g.rp[k]||
""}JT(){return!!this.offlineSlate&&this.offlineSlate.w9}});})(_yt_player);
